BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
    .string "训练师所需要的一切…\p知识…\n战术…\l幸运…\l斗志…\l精神…\l勇气…\l还有才能…\p我可是拥有这一切！\n在这里我必定是战无不胜的！\p嗯？宝可梦？\n那是什么？$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
    .string "你知道\n开拓之脑吗？\p亚希达是这么称呼\n管理对战开拓区七大设施的\l那七位特别的训练师的。$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
    .string "对战塔里有一位大姐姐\n告诉我我在战斗方面的才能\l非常出色！\p不过我更喜欢宝可梦华丽大赛！\p但我在华丽大赛上完全不行！\p我想也许喜欢和天赋\n是两码事吧。$"

