SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
    .string "似乎琉璃市与\n送神火山码头之间存在着某种联系。\p我还在研究所工作的时候\n和同事一起做过这方面的调查。$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
    .string "我哥哥曾经研究海洋。$"

