RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
    .string "训练师学校特别好，\p在那儿学习的话，\n甚至可能成为道馆馆主。$"

RustboroCity_House2_Text_RoxanneKnowsALot:
    .string "道馆馆主杜娟了解\n很多关于宝可梦的知识，\p而且她也很强大！$"

