gText_ApprenticeChallenge0::
    .string "嗯，我是{STR_VAR_1}的第{STR_VAR_2}名学徒。\n嗅…好紧张啊…$"

gText_ApprenticeChallenge1::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n我们上！$"

gText_ApprenticeChallenge2::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n接受我的挑战吧！$"

gText_ApprenticeChallenge3::
    .string "嗯，我是{STR_VAR_1}的第{STR_VAR_2}名学徒…\n你说像我这样的人能赢吗？$"

gText_ApprenticeChallenge4::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n尽管放马过来吧！$"

gText_ApprenticeChallenge5::
    .string "我现在忙得要死，但我碰巧是\n{STR_VAR_1}的第{STR_VAR_2}名学徒。$"

gText_ApprenticeChallenge6::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒。\n很高兴见到你！$"

gText_ApprenticeChallenge7::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒。\n可以开始了吗？$"

gText_ApprenticeChallenge8::
    .string "呀！我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n我会尽力的！$"

gText_ApprenticeChallenge9::
    .string "哟！我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n开始吧！$"

gText_ApprenticeChallenge10::
    .string "我是{STR_VAR_1}的第1000名学徒！\n事实上我是第{STR_VAR_2}名！来吧！$"

gText_ApprenticeChallenge11::
    .string "耶，我是{STR_VAR_1}的第{STR_VAR_2}名学徒！\n开始我们的摇滚之旅吧！$"

gText_ApprenticeChallenge12::
    .string "呀呼！我是路人皆知的\n{STR_VAR_1}的第{STR_VAR_2}名学徒！$"

gText_ApprenticeChallenge13::
    .string "咳！我是{STR_VAR_1}的第{STR_VAR_2}名学徒。\n很高兴见到你！咳！$"

gText_ApprenticeChallenge14::
    .string "真是令人忐忑不安啊…\n我是{STR_VAR_1}的第{STR_VAR_2}名学徒。$"

gText_ApprenticeChallenge15::
    .string "我是{STR_VAR_1}的第{STR_VAR_2}名学徒，\n骗你是小狗。$"

gText_ApprenticePleaseTeach0::
    .string "你是…{PLAYER}吗？\n噢！嗅…呜呜…\p噢！对-对不起…\n我太紧张了，一不小心就哭了出来…\p我是{STR_VAR_1}，我真的很\n敬佩你，{PLAYER}。\p我…我一直梦想着有一天能\n见到你，听你讲解宝可梦的知识。\p求求你，{PLAYER}！\n请教我有关宝可梦的知识吧！$"

gText_ApprenticeRejectTeaching0::
    .string "噢…可-可是…\n嗅…哇----！\p求求你！\n求求你教我吧！$"

gText_ApprenticeWhichLevelMode0::
    .string "噢，真的？你同意了？\n棒极了！太帅了！呜呜--！\p噢…对不起…\n我太高兴了，不知不觉地就哭了…\p嗯…那请告诉我吧！\n我想询问有关对战塔的事。\p哪一个比较适合我：\n50级还是自由级？$"

gText_ApprenticeLevelModeThanks0::
    .string "{STR_VAR_1}？\n哇哇--！\p噢！实在抱歉！\n你替我选择了级别\l我太高兴了，高兴得都哭出来了…\p嗅…\n太感谢你了！\l以后还请多多指教！$"

gText_ApprenticePleaseTeach1::
    .string "哇！你就是{PLAYER}吧？\n你是不是很强很强？\p我是{STR_VAR_1}！\n我刚刚成为训练师！\p求求你，{PLAYER}！\n你能不能当我的老师\l教我怎样做一个训练师？$"

gText_ApprenticeRejectTeaching1::
    .string "啊，为什么？\n噢，求求你？真的求求你？\l请当我的老师吧，求求你！$"

gText_ApprenticeWhichLevelMode1::
    .string "耶！太好了！\p我第一件想问你的事情是\n有关对战塔的！\p50级和自由级…\n哪一个最适合我？$"

gText_ApprenticeLevelModeThanks1::
    .string "{STR_VAR_1}，对吗？没错！\n我会尽力的！\p如果我们还能见面的话，\n请教我更多的知识吧，老师！$"

gText_ApprenticePleaseTeach2::
    .string "嗯…你是{PLAYER}？\n我是{STR_VAR_1}。\p我想成为一名宝可梦训练师，\n但我不知道从哪里做起…\p您这么有名\n或许我能向您讨教一下。\p{PLAYER}，您能给我一些建议吗？$"

gText_ApprenticeRejectTeaching2::
    .string "噢，可是…\p我真的想成为一名宝可梦\n训练师！\p求求你，能回答我的问题吗？$"

gText_ApprenticeWhichLevelMode2::
    .string "谢谢你！\n我现在就提第一个问题！\p对战塔有两个级别，\n50级和自由级，对吧？\p您认为哪一个\n更适合我？$"

gText_ApprenticeLevelModeThanks2::
    .string "噢，您是说{STR_VAR_1}？\n明白了！\p我如果还有问题的话，\n会回来请教您的！$"

gText_ApprenticePleaseTeach3::
    .string "噢？咦？你是…\n不，不可能。\p我这样的小人物\n怎么会碰到{PLAYER}。\p…你真的是{PLAYER}？\n真不敢相信我正在和你说话！\p可是福无双至，\n我以后肯定要倒霉的\l我就知道…\p…对不起…\n我…{STR_VAR_1}…\p我没有什么\n拿得出手的本事…\p我真不应该自我介绍\n你很快就会忘了我这种小人物…\p我一直梦想着如果有一天我能\n遇见你，{PLAYER}，我或许可以\l向你请教有关训练师的问题。\p我知道我只是\n在做白日梦。\p…不过或许您真的会\n给我一些建议？$"

gText_ApprenticeRejectTeaching3::
    .string "我就知道…\p我这种无趣的小人物\n只配这种结局…\p不过也许…\n您能再考虑考虑？\p我不能就这样放弃了。\n趁我现在还有福气，我不能放弃！\p求求你，您就网开一面\n给我点建议吧？$"

gText_ApprenticeWhichLevelMode3::
    .string "真的？我真不敢相信！\n您答应给我点建议了！\l我…我太高兴了…\p我想问你的都是些\n琐碎的事，怎么说呢…\p在对战塔，他们让我\n在50级和自由级中做出选择。\p我这种人选哪一个\n才会有点胜算？$"

gText_ApprenticeLevelModeThanks3::
    .string "{STR_VAR_1}？好的！\n不过您真的认为\l像我这样的人有机会取胜？\p虽说没什么希望\n我还是会尽力的。\p感谢您在百忙之中\n抽出时间回答我的问题。$"

gText_ApprenticePleaseTeach4::
    .string "噢！你就是{PLAYER}{KUN}吧？\p我听说你是\n宝可梦的专家！\p我是{STR_VAR_1}！\n我会做你的朋友的！\p你知道吗？\p光凭训练师学校\n所教授的知识\l是无法在对战开拓区取胜的。\p我愿意听一听你的建议。\n你肯定会同意的吧？$"

gText_ApprenticeRejectTeaching4::
    .string "啊？为什么拒绝我？\n问你的人可是我啊！\l你必须再考虑考虑！$"

gText_ApprenticeWhichLevelMode4::
    .string "很好，事情是这样的。\n我想让你替我决定一件事。\p你肯定知道在对战塔\n有50级和自由级两个房间吧？\p你说哪一个比较\n适合我，{PLAYER}{KUN}？$"

gText_ApprenticeLevelModeThanks4::
    .string "你是说，{STR_VAR_1}适合我？\n谢谢你！\p反正是你做的决定，\n{PLAYER}{KUN}，我即使输了\l也不丢人。\p就这样，以后我还会向你讨教的。\n再见！$"

gText_ApprenticePleaseTeach5::
    .string "噢，你好！{PLAYER}{KUN}！\n你可是个名人啊！\l叫我{STR_VAR_1}吧！很高兴见到你！\p我是一名三项全能运动员，所以在\n养宝可梦的同时还要注意保健。\p平时我还做一些其它的事情\n比如工作，睡觉，跳交际舞…\p因此我这种大忙人\n很难成为一名合格的训练师。\p我有个提议！\p你我相见肯定是有缘。\n所以，{PLAYER}{KUN}，你平时可不可以\l和我交流一些心得？$"

gText_ApprenticeRejectTeaching5::
    .string "噢，真的不行？\n可我这种人真的\l需要你，{PLAYER}{KUN}！\p我真的需要你的建议！$"

gText_ApprenticeWhichLevelMode5::
    .string "谢谢你！这就对了！\n那我们就先从简单的开始吧！\p你肯定知道对战塔的\n两种模式吧？\l也就是50级和自由级。\p我这种大忙人应该\n准备哪一种？$"

gText_ApprenticeLevelModeThanks5::
    .string "{STR_VAR_1}，是吗？我明白了。\n我会抽时间准备的！\p…哎呀，我要去工作了！\n谢谢你！回见！$"

gText_ApprenticePleaseTeach6::
    .string "不可能！天啊！\n你真的是{PLAYER}？\p啊哈！太棒了！我是{STR_VAR_1}，\n十分高兴见到你！\p{PLAYER}，听说你很强，\n是吗？\p最近大家都在议论你！\p噢！我想到了一个绝佳的主意！\n我要听取你的建议，{PLAYER}！\l这对我的成长肯定大有帮助！\p是不是很棒的主意？\n请给我点建议吧！$"

gText_ApprenticeRejectTeaching6::
    .string "啊哈哈，别装了，\n你骗不了我！\l你肯定愿意，对不对？$"

gText_ApprenticeWhichLevelMode6::
    .string "耶！我就知道你是个热心肠，\n{PLAYER}！\p我该先问什么呢？\n…噢，我想到了！\p来点鼓声！\n我的问题是…\p如果我在对战塔\n战斗，应该选哪一个？\p50级还是自由级？\n哪一个更适合我？$"

gText_ApprenticeLevelModeThanks6::
    .string "噢-噢-噢！\n你是说{STR_VAR_1}！\l这个回答太酷了！\p今天我就问\n这么多吧。\p以后再聊。\n谢谢！$"

gText_ApprenticePleaseTeach7::
    .string "打扰你一下…\n你是{PLAYER}吗？\p我是{STR_VAR_1}，很高兴\n能认识你。\p我一直是你的\n粉丝…\p… … … … … …\p嗯…我希望我的要求\n不是很过分…\p您能收我做徒弟吗，\n{PLAYER}？$"

gText_ApprenticeRejectTeaching7::
    .string "噢…！\p… … … … … …\n… … … … … …\p…我刚才肯定晕过去了。\n对不起，我一定是听错了。\p求求你！您就答应\n收我做徒弟吧！$"

gText_ApprenticeWhichLevelMode7::
    .string "噢…我太高兴了！\p我不希望浪费您的时间，\n您只要给我一点建议就行。\p我打算不久就在对战塔\n接受挑战。\p但那里有两个级别…\p哪一个更适合我？\n50级还是自由级？$"

gText_ApprenticeLevelModeThanks7::
    .string "应该选{STR_VAR_1}！\n我明白了。我会尽力的！\p谢谢你，{PLAYER}。\n希望我以后还能向你讨教。\l请多保重！$"

gText_ApprenticePleaseTeach8::
    .string "哇！哇！{PLAYER}！\n你和我说话了！\l我…我太高兴了！\p是我！我叫{STR_VAR_1}！\n我刚成为一名训练师！\p真高兴能见到你，{PLAYER}，\n宝可梦界的大名人！\p噢-噢-噢，对了！\n我能不能请你帮个大忙，{PLAYER}？\p请收我做徒弟吧！\n我想聆听你的教诲！$"

gText_ApprenticeRejectTeaching8::
    .string "哇啊！\n{PLAYER}拒绝了我…\l这…这真是难得的经历啊！\p求求你，{PLAYER}！这次我想\n得到肯定的答复！\p求求你指导一下我！$"

gText_ApprenticeWhichLevelMode8::
    .string "耶！{PLAYER}同意了！\n{PLAYER}同意了！\p今晚我肯定睡不着觉了…\n太感谢你了！\p那我就开始提问了！\p在对战塔，哪一个\n适合我，50级还是自由级？$"

gText_ApprenticeLevelModeThanks8::
    .string "{STR_VAR_1}！明白了！\n我完全明白！\l我真是有些欣喜若狂了！\p希望您以后还能\n教导教导我。$"

gText_ApprenticePleaseTeach9::
    .string "哇！你该不会是…\n你真的是…{PLAYER}{KUN}？！\l那个天下无敌的训练师？\l啊，你好，我真是个幸运儿！\p我叫{STR_VAR_1}！\p我一直在寻找一个\n宝可梦老师。\p就在我毫无头绪的时候，\n你出现了，{PLAYER}{KUN}！\p你知道的，{PLAYER}{KUN}！\n收我做徒弟吧！$"

gText_ApprenticeRejectTeaching9::
    .string "啊！\n你真的是很酷很强…\p请不要这样。\n我求你了！$"

gText_ApprenticeWhichLevelMode9::
    .string "哦，耶！真是爽快！\n不得不承认，你太优秀了！\p那就先讲一讲\n对战塔吧？\p如果我去的话，哪一个更适合我？\n50级还是自由级？$"

gText_ApprenticeLevelModeThanks9::
    .string "哦，是{STR_VAR_1}啊！\n好的，啊-好的！\l那我去奋斗了！\p以后我还会找你指导我的！\n再见！$"

gText_ApprenticePleaseTeach10::
    .string "哦，嘿，{PLAYER}{KUN}，对吧？\n警察正找你呢！\p… … …\n当然是开玩笑了！\p是我，{STR_VAR_1}。别看我长成这样，\n我可是宝可梦冠军！\l…当然这也是个玩笑！\p不过这次是认真的。\n我不擅长对战。\p因此我能不能拜你为师\n向你学习宝可梦的知识？$"

gText_ApprenticeRejectTeaching10::
    .string "如果你想这样耍酷，\n那我就要使绝招了！\p哇！哇！哇！\n嗝！\p哈哈哈，这就是我的鳄鱼的眼泪！\p行了，你愿意\n收我这个徒弟吗？$"

gText_ApprenticeWhichLevelMode10::
    .string "耶！\n我会买艘船送你的！\p当然还是个玩笑！\n不过…谢谢你，师傅！\p你知道对战塔有\n50级和自由级之分吧？\p我不知道该\n选哪一个…\p你能替我决定吗，师傅？$"

gText_ApprenticeLevelModeThanks10::
    .string "明白，{STR_VAR_1}更适合！\n那我就不选它了！\p开个玩笑！\n我会遵从你的教导的，师傅！\p谢谢你！\n希望你以后还能教我！$"

gText_ApprenticePleaseTeach11::
    .string "啊-呵！\n我是说啊呵，你好的意思！\p我是{STR_VAR_1}，无敌的\n快嘴皮水手！\p现在轮到你进行\n自我介绍了，试一试！\p啊-嗯，啊-嗯！\n你叫{PLAYER}{KUN}，\l玩的是宝可梦！\p年纪轻轻就已经\n登上了世界舞台！\p总之我的意思是，\n你是我今天碰到的\l第十名训练师。\p我们为什么不庆祝一下！\n庆祝内容是你当我的导师！$"

gText_ApprenticeRejectTeaching11::
    .string "别这样！\n你必须和我合作！\p不要这么刻薄嘛！\n你就当一回我的导师吧！$"

gText_ApprenticeWhichLevelMode11::
    .string "这就对了！\n{PLAYER}，要的就是这种精神！\p我第一个想要咨询的\n问题是这样的！\p在对战塔战斗\n要量力而行！\p有50级和自由级两种级别，\n哪一个适合我？$"

gText_ApprenticeLevelModeThanks11::
    .string "哦，你是说{STR_VAR_1}！\n我这就准备去！\p说到建议，\n{PLAYER}，你的话总会令我满意！$"

gText_ApprenticePleaseTeach12::
    .string "嘿，你不是{PLAYER}吗？\n我该怎么办？和你说话？\l为什么不？我已经在和你说话了！\p{PLAYER}，你对我感到很惊讶？\n那我就告诉你我的大名！\p你叫我{STR_VAR_1}好了。\n吉他界最耀眼的明星，\l那就是我！\p你接受我吗？\n你肯定会接受的！\p我的运气无与伦比，\n我的要求无懈可击！\p{PLAYER}，我来当你的下属！\n你来教我如何上路！$"

gText_ApprenticeRejectTeaching12::
    .string "你想拒绝我？\n那我只能再问一遍！\p{PLAYER}，我求你收我为下属！\n我需要你为我指明道路！$"

gText_ApprenticeWhichLevelMode12::
    .string "耶，真走运！\n那我能不能问你个问题？\p既然我们在对战塔旁边，\n我就以此发问吧？\p下列选择中，\n哪一个更适合我？$"

gText_ApprenticeLevelModeThanks12::
    .string "既然你建议我选{STR_VAR_1}，\n那这一定是最佳答案！\p好了，{PLAYER}，我要自由驰骋，\n你可别忘了我这名学生。\p再见，我的好朋友！$"

gText_ApprenticePleaseTeach13::
    .string "哦，喂！说你呢！\n你能不能为我捶一捶肩？\p…对，就是这！这里！\n嗷，嗷！哦，真舒服！\p我叫{STR_VAR_1}。\n我在练空手道，但我的身体\l好像不适合这种运动…\p于是我决定通过和宝可梦\n对战来锻炼自己。\p你是{PLAYER}{KUN}，对不对？\n那个宝可梦联盟冠军？\p听着，你能不能给我\n一些建议？$"

gText_ApprenticeRejectTeaching13::
    .string "哦，为什么？\p我保证不会给你惹麻烦！\n行不行？$"

gText_ApprenticeWhichLevelMode13::
    .string "谢谢。你真是太好了！\n…咳！咳！\p哦，我必须赶快变强…\p我马上就去对战塔\n但是哪一个级别更适合我？\l50级还是自由级？$"

gText_ApprenticeLevelModeThanks13::
    .string "嗯，好的。那就{STR_VAR_1}吧。\n我马上就去。\p真希望能一直向你\n咨询--你已经是我的导师了！$"

gText_ApprenticePleaseTeach14::
    .string "呃…嗯…\n{PLAYER}{KUN}…？\p请不要这样看着我。\n我都觉得不自然了。\p我…我是{STR_VAR_1}。\p虽然难以启齿，\n但我一直在研究古代遗迹。\p更让我难以启齿的是\n我对对战开拓区感兴趣。\p{PLAYER}{KUN}，你是出了名的\n高级训练师…\p请原谅我的无礼，\n我想求你件事。\p你能当我的老师\n给我些建议吗？$"

gText_ApprenticeRejectTeaching14::
    .string "请不要这样拒绝我！\n我无法忍受这种耻辱。\p请当我的老师吧！\n我需要你的建议！$"

gText_ApprenticeWhichLevelMode14::
    .string "谢-谢谢你…\p但请不要这样看着我。\n我会紧张的。\p答应我，回答问题的时候\n请不要看着我的眼睛。\p在对战塔…\n我应该尝试哪一个级别？$"

gText_ApprenticeLevelModeThanks14::
    .string "哦…好的！\n我会试一试的。\p希望我能勇于面对\n挑战，奋力拼搏…\p谢谢你，{PLAYER}{KUN}。\n如果我们还能见面的话\l请再给我些建议。$"

gText_ApprenticePleaseTeach15::
    .string "嗯？你好像是{PLAYER}{KUN}…\n真的吗？\p你可以叫我{STR_VAR_1}。\p我一直在琢磨着\n找一个训练师高手做我的老师。\p看来我今天真是走运！\n…你真的是{PLAYER}{KUN}？\p我是说，是真的就好。\n我只是想请你\l收我做徒弟。$"

gText_ApprenticeRejectTeaching15::
    .string "哦？\n但你出于什么原因拒绝了我？\p很抱歉我刚才在\n怀疑你的身份。\p请接受我的道歉\n收我做徒弟吧。$"

gText_ApprenticeWhichLevelMode15::
    .string "你真的同意了？\n我可不想高兴得太早。\p如果你真的同意了，那我道歉。\n我现在需要你的指点。\p如果我要去对战塔，\n哪一个适合我？\l50级还是自由级？$"

gText_ApprenticeLevelModeThanks15::
    .string "{STR_VAR_1}？\n你确定吗？\p我明白了。那就好。\n谢谢你抽空解答问题。\p我知道我不讨喜，但我很\n高兴你能接受我。\p回见！$"

gText_ApprenticeWhatHeldItem0::
    .string "唉…呜…\n哦，{PLAYER}！\p我现在进退两难\n举棋不定。\p我不知道该让我的{STR_VAR_1}\n携带什么道具。\p请告诉我，{PLAYER}。\n我应该选哪一个道具？$"

gText_ApprenticeHoldNothing0::
    .string "哦，真的？我不能让\n我的{STR_VAR_1}携带任何道具？$"

gText_ApprenticeThanksNoHeldItem0::
    .string "哦，好的！真高兴问题解决了！\n太酷了！棒极了！耶！\p太谢谢你了！$"

gText_ApprenticeThanksHeldItem0::
    .string "哦，我太高兴了…\n我记得我也有{STR_VAR_1}。\p真高兴问题解决了！\n太酷了！棒极了！耶！\p太谢谢你了！$"

gText_ApprenticeItemAlreadyRecommended0::
    .string "哇啊！请别这么小气！\p你之前已经推荐我\n选{STR_VAR_1}了，呜…\p你的意思是不是\n我的{STR_VAR_2}应该什么都不拿？$"

gText_ApprenticeWhatHeldItem1::
    .string "耶！是{PLAYER}！\n太好了！我想问你件事！\p你让不让你的宝可梦携带道具？\n我想这样做，可是…\p我的{STR_VAR_1}应该\n携带什么道具？\p你怎么想？$"

gText_ApprenticeHoldNothing1::
    .string "啊？你是说我的{STR_VAR_1}\n不需要携带任何道具？$"

gText_ApprenticeThanksNoHeldItem1::
    .string "哦，我明白了！我会这么做的！\n谢谢你的指点！$"

gText_ApprenticeThanksHeldItem1::
    .string "哦，哇！一个{STR_VAR_1}，是吗？\n我会这么做的！\p谢谢你的指点！$"

gText_ApprenticeItemAlreadyRecommended1::
    .string "哦，啊，我不是这个意思。\n我想了解一个\l以前没用过的道具。\p难道你的意思是我的宝可梦\n不需要携带任何道具？$"

gText_ApprenticeWhatHeldItem2::
    .string "{PLAYER}，你好！\n我想问问有关{STR_VAR_1}的事…\p我想让它携带一个合适的道具。\n你看哪一个比较好？$"

gText_ApprenticeHoldNothing2::
    .string "哦，那我的{STR_VAR_1}不需要\n携带任何道具？$"

gText_ApprenticeThanksNoHeldItem2::
    .string "我明白了！\n再见！$"

gText_ApprenticeThanksHeldItem2::
    .string "哦，{STR_VAR_1}？\n明白了！\p我会努力去找的！\n再见！$"

gText_ApprenticeItemAlreadyRecommended2::
    .string "已经有人告诉过我\n{STR_VAR_1}了。\p我想让我的宝可梦携带\n另一个道具。\p也许我的{STR_VAR_2}不需要\n携带任何道具？$"

gText_ApprenticeWhatHeldItem3::
    .string "你好，{PLAYER}…\n很抱歉打搅你，我想\l问你件事。\p我觉得光凭一己之力是\n无法赢得比赛的，所以我想让\l我的{STR_VAR_1}携带一个道具。\p但我不知道选哪个好。\p{PLAYER}，请问你能替我\n决定吗？$"

gText_ApprenticeHoldNothing3::
    .string "我这种人拥有的宝可梦\n最好不要拿道具？$"

gText_ApprenticeThanksNoHeldItem3::
    .string "我明白了…\n你是想说我不应该依赖于道具。\l我会尽力的！\p非常感谢！$"

gText_ApprenticeThanksHeldItem3::
    .string "{STR_VAR_1}，好的。\n不知道我能不能找到…\l不！我会努力去找的。\p非常感谢！$"

gText_ApprenticeItemAlreadyRecommended3::
    .string "哦，可是…\n我以前好像听说过这种道具…\p是不是我以前没有\n正确使用{STR_VAR_1}？\p还是说我的{STR_VAR_2}\n不需要携带道具？$"

gText_ApprenticeWhatHeldItem4::
    .string "哦，{PLAYER}{KUN}。\n我想问你件事。\p你记得你曾经替我\n选了一个宝可梦吧？\p但我当时却忘了问你\n它应该携带什么道具。\p既然你之前帮了我一回，\n那不如帮到底吧？\p哪一个好？我想让我的\n{STR_VAR_1}携带一个道具。$"

gText_ApprenticeHoldNothing4::
    .string "哦！这么说我的{STR_VAR_1}\n应该什么都不拿？$"

gText_ApprenticeThanksNoHeldItem4::
    .string "既然你这么想，那就定了。\p反正是你做的决定，\n{PLAYER}{KUN}，我即使输了\l也不丢人。\p就这样，我还会向你咨询的。\n再见！$"

gText_ApprenticeThanksHeldItem4::
    .string "选{STR_VAR_1}，是吗？\n还不错。我会用的！\p反正是你做的决定，\n{PLAYER}{KUN}，我即使输了\l也不丢人。\p就这样，我还会向你咨询的。\n再见！$"

gText_ApprenticeItemAlreadyRecommended4::
    .string "啊？你说什么？\n你之前已经\l告诉过我{STR_VAR_1}了。\p你是不是说我的{STR_VAR_2}\n应该什么都不拿？$"

gText_ApprenticeWhatHeldItem5::
    .string "嘿，{PLAYER}{KUN}！\p我们都很忙，可仍然\n能经常碰到对方！\p今天我想散散步，\n打扫一下卫生，做做家务。\p我之前都没时间为我的\n宝贝{STR_VAR_1}买东西。\p我时间不多，不如你给我\n一点建议吧，我的{STR_VAR_1}\l应该携带什么道具？$"

gText_ApprenticeHoldNothing5::
    .string "哦，我是个大忙人，因此\n我的{STR_VAR_1}不需要道具？$"

gText_ApprenticeThanksNoHeldItem5::
    .string "明白了。\n真是省了我不少时间。\p谢谢啊！\n回见！$"

gText_ApprenticeThanksHeldItem5::
    .string "明白了。\n我会抽空去找\l你推荐的那个{STR_VAR_1}。\p真高兴能碰到你这种导师。\n谢谢啊！再见！$"

gText_ApprenticeItemAlreadyRecommended5::
    .string "啊？我早就知道\n那个{STR_VAR_1}。\p哦，我明白了。\n你是说，我这种大忙人的\l{STR_VAR_2}不需要道具？$"

gText_ApprenticeWhatHeldItem6::
    .string "嘿，{PLAYER}！是我！\n今天我又要向你讨教了。\l我需要你的建议！\p来点鼓声！\n我的问题是…\p如果我想让我的{STR_VAR_1}\n携带一个道具，应该选哪一个？$"

gText_ApprenticeHoldNothing6::
    .string "是吗？你是说我的{STR_VAR_1}\n不需要携带任何道具？$"

gText_ApprenticeThanksNoHeldItem6::
    .string "那就这么定了！\p我今天想问你的\n就这么多。\p以后再见吧？\n谢谢你！$"

gText_ApprenticeThanksHeldItem6::
    .string "哦！一个{STR_VAR_1}。\n太酷了！\l我肯定会用的！\p我今天想问你的\n就这么多。\p以后再见吧？\n谢谢你！$"

gText_ApprenticeItemAlreadyRecommended6::
    .string "啊哈哈！太傻了！\n你之前已经跟我\l说过{STR_VAR_1}了！\p你没发烧吧，{PLAYER}？\p哦，等等！你是说我的{STR_VAR_2}\n不需要携带任何道具？$"

gText_ApprenticeWhatHeldItem7::
    .string "你好，{PLAYER}。你最近\n还好吧。\p我能不能向你咨询一件事？\p在最近的一场战斗中\n我的对手似乎给了他的宝可梦\l一个道具。\p结果我就被打败了…\p我不想落后于人。\n所以我也想让我的{STR_VAR_1}\l携带一个道具。\p我希望你能替我决定\n哪一个道具适合我的宝可梦…$"

gText_ApprenticeHoldNothing7::
    .string "也就是说…我的宝可梦\n不需要携带道具？$"

gText_ApprenticeThanksNoHeldItem7::
    .string "我完全明白了！\n我会努力的。\p谢谢你，{PLAYER}。\n希望下次还能找你帮忙。\l请多保重！$"

gText_ApprenticeThanksHeldItem7::
    .string "一个{STR_VAR_1}！\n我马上就去订购。\p谢谢你，{PLAYER}。\n希望下次还能找你帮忙。\l请多保重！$"

gText_ApprenticeItemAlreadyRecommended7::
    .string "你已经跟我说过了，\n我也已经买了。\p你的意思是…我的宝可梦\n不需要携带道具？$"

gText_ApprenticeWhatHeldItem8::
    .string "呀！{PLAYER}！\n我…真的很高兴能再次见到你！\p哦-哦-哦！正好我有件事\n想问你，{PLAYER}！\p我的{STR_VAR_1}应该\n携带什么道具？$"

gText_ApprenticeHoldNothing8::
    .string "哦，哇！没想到你会这样回答！\n这么说不需要道具？$"

gText_ApprenticeThanksNoHeldItem8::
    .string "明白了！\n我会坚持不使用道具的！\p希望你以后\n还能再教教我。$"

gText_ApprenticeThanksHeldItem8::
    .string "{STR_VAR_1}！我会用的！\p嗯…难道说，{PLAYER}，\n你的宝可梦也携带这个道具？\p我一定会弄到的！\n希望你以后\l还能再教教我。$"

gText_ApprenticeItemAlreadyRecommended8::
    .string "哦？你之前已经\n推荐过{STR_VAR_1}了。\p这是不是最佳选择？\n难道你的意思是我的{STR_VAR_2}\l不需要携带道具？$"

gText_ApprenticeWhatHeldItem9::
    .string "嗨！\n我的导师，{PLAYER}{KUN}！\p我想向你咨询\n有关宝可梦道具的事。\p你觉得我的{STR_VAR_1}\n应该携带什么道具？\p不要害羞。\n说出来吧！$"

gText_ApprenticeHoldNothing9::
    .string "哦？你是说我的{STR_VAR_1}\n不需要道具就能赢？$"

gText_ApprenticeThanksNoHeldItem9::
    .string "很好！\n我会努力争取的！\p多谢，你又帮了大忙！\n再见！$"

gText_ApprenticeThanksHeldItem9::
    .string "哦，一个{STR_VAR_1}？\n很好！\l我会努力去找的！\p多谢，你又帮了大忙！\n再见！$"

gText_ApprenticeItemAlreadyRecommended9::
    .string "不，不！你之前已经\n和我说过{STR_VAR_1}了。\p嗯，等一下…\n你是说我的{STR_VAR_2}\l不用道具就能赢？$"

gText_ApprenticeWhatHeldItem10::
    .string "{PLAYER}{KUN}，有一件不可思议\n的事情发生了！\p我今天早上醒来的时候，\n发现我的宝可梦有10个金子！\p当然是开玩笑了！\n哇哈哈！\p说正经的吧。\n我搞不清楚究竟\l让宝可梦携带什么道具。\p不如你替我决定一下\n我的{STR_VAR_1}应该携带什么？$"

gText_ApprenticeHoldNothing10::
    .string "什么意思？\n不用携带道具？$"

gText_ApprenticeThanksNoHeldItem10::
    .string "好吧，看来应该什么都不拿。\n那我马上去找个道具！\p开玩笑啦！\n我会听从你的教导的，师傅！\p谢谢你，师傅！\n希望你以后还能教导我！$"

gText_ApprenticeThanksHeldItem10::
    .string "哦，应该选{STR_VAR_1}！\n那我肯定不会用它的！\p开玩笑啦！\n我会听从你的教导的，师傅！\p谢谢你，师傅！\n希望你以后还能教导我！$"

gText_ApprenticeItemAlreadyRecommended10::
    .string "嗯，你之前已经告诉过我了，\n是不是？\p没有别的道具可以选吗？\p还是说，我的{STR_VAR_2}\n不需要道具？$"

gText_ApprenticeWhatHeldItem11::
    .string "啊-呵！\n我是说啊-呵！\p我是无敌的快嘴皮水手！\n我要问你一个\l十分有水平的问题！\p是关于道具的\n希望你能给点建议！\p我的{STR_VAR_1}需要携带一个道具，\n我应该选哪一个？$"

gText_ApprenticeHoldNothing11::
    .string "是吗？\n我的{STR_VAR_1}不需要\l携带任何道具？$"

gText_ApprenticeThanksNoHeldItem11::
    .string "好的，我明白了，肯定明白了！\n我的宝可梦什么都不用拿！\p说到建议，\n{PLAYER}，你的话总会令我满意！$"

gText_ApprenticeThanksHeldItem11::
    .string "好的，选{STR_VAR_1}，\n就这么定了。\l我果然找对了人！\p说到建议，\n{PLAYER}，你的话总会令我满意！$"

gText_ApprenticeItemAlreadyRecommended11::
    .string "哦，你让我选{STR_VAR_1}？\n你之前已经告诉过我了。\l我需要新的理念，新的思想。\p哦，等等，难道说？\n我的宝可梦不需要\l任何道具？$"

gText_ApprenticeWhatHeldItem12::
    .string "嘿，{PLAYER}！\n我今天又找到你了！\p我该怎么办？听一听你的建议？\n为什么不？我已经在和你说话了！\p{PLAYER}，你是不是烦我了？\n啊，不会的，不可能。\p你愿意听我说完吗？\n我想要点建议--\l没错，一点建议。\p是关于让我的{STR_VAR_1}\n携带何种道具的问题。\l我现在举棋不定，真郁闷。$"

gText_ApprenticeHoldNothing12::
    .string "我的{STR_VAR_1}什么都不需要？\n什么都不用拿？$"

gText_ApprenticeThanksNoHeldItem12::
    .string "如果什么都不拿真的是\n最佳选择，那我听你的！\p好了，{PLAYER}，我要自由驰骋，\n你可别忘了我这名学生。\p再见，我的好朋友！$"

gText_ApprenticeThanksHeldItem12::
    .string "如果携带{STR_VAR_1}是\n最佳选择，那我听你的！\p好了，{PLAYER}，我要自由驰骋，\n你可别忘了我这名学生。\p再见，我的好朋友！$"

gText_ApprenticeItemAlreadyRecommended12::
    .string "我之前是不是\n听说过{STR_VAR_1}？\l我肯定听过！\p我想来点新花样！\n难道说，我的{STR_VAR_2}不需要道具？\l什么都不用拿？$"

gText_ApprenticeWhatHeldItem13::
    .string "哇！哎哟！{PLAYER}{KUN}，\n我的膀子骨折了！请不要碰它！\p我肯定是在为我的宝可梦\n挑选合适的道具的时候\l把膀子弄骨折了。\p事到如今，\n我需要你替我决定。\p{PLAYER}{KUN}，你说我的{STR_VAR_1}\n适合携带什么道具？$"

gText_ApprenticeHoldNothing13::
    .string "哎哟…\p你建议我的{STR_VAR_1}\n什么都不拿？$"

gText_ApprenticeThanksNoHeldItem13::
    .string "嗯，好吧。事到如今\n也只能这样了。\p希望我以后还能这样\n向你咨询。$"

gText_ApprenticeThanksHeldItem13::
    .string "嗯，好吧。就选{STR_VAR_1}。\n反正我的宝可梦的膀子没事\l我马上让它拿那个道具。\p希望我以后还能这样\n向你咨询。$"

gText_ApprenticeItemAlreadyRecommended13::
    .string "不，不，你之前已经提到过\n{STR_VAR_1}了，你忘了？\p能不能告诉我一个\n更好的？\p哦，等一等。\n你是说我的{STR_VAR_2}\l什么都不需要拿？$"

gText_ApprenticeWhatHeldItem14::
    .string "啊…嗯…\n{PLAYER}{KUN}…\p请不要这样看着我。\n我的宝可梦什么都没有。\p我…我真丢人，\n我迫切需要你的建议。\p我不知道选什么道具\n能让我的{STR_VAR_1}变强。\p{PLAYER}{KUN}，你觉得什么\n道具比较好？$"

gText_ApprenticeHoldNothing14::
    .string "哦…你认为我的{STR_VAR_1}\n最好什么都不拿？$"

gText_ApprenticeThanksNoHeldItem14::
    .string "哦…好的！\n那我就不用道具了。\p不过还是有点紧张。\n这是不是太酷了？\p谢谢你，{PLAYER}{KUN}。\n如果我们还能见面的话\l请再给我些建议。$"

gText_ApprenticeThanksHeldItem14::
    .string "哦…好的！\n那我就用{STR_VAR_1}。\p不过还是有点紧张。\n这是不是太酷了？\p谢谢你，{PLAYER}{KUN}。\n如果我们还能见面的话\l请再给我些建议。$"

gText_ApprenticeItemAlreadyRecommended14::
    .string "可-可是我之前已经听说过了。\p请不要这样拒绝我！\n我无法忍受这种耻辱。\p哦…我是不是太性急了？\n你是不是认为\l我的{STR_VAR_2}不需要道具？$"

gText_ApprenticeWhatHeldItem15::
    .string "嗯？你好像是{PLAYER}{KUN}…\n你真的是？\l不会是双胞胎吧？\p哦，不，不，不，别担心！\n如果你真的是{PLAYER}，\l请原谅我的无礼。\p我现在又想听听\n你的建议。\p我现在养了只{STR_VAR_1}\n我想让它携带一个道具。\p哪一个值得一试？$"

gText_ApprenticeHoldNothing15::
    .string "最好不要道具？\n你确定吗？$"

gText_ApprenticeThanksNoHeldItem15::
    .string "我明白了。那就这么招吧。\n谢谢你抽空回答问题。\p再见！$"

gText_ApprenticeThanksHeldItem15::
    .string "一个{STR_VAR_1}？\n你确定吗？\p我明白了。那就这么招吧。\n谢谢你抽空回答问题。\p我真心希望我的宝可梦\n能把它用在刀刃上。\p再见！$"

gText_ApprenticeItemAlreadyRecommended15::
    .string "不，不，等一下。\n我记得你以前说过这个。\p我希望你这次能推荐\n别的什么东西\p或许你是指\n我的{STR_VAR_2}不需要道具？\l你确定吗？$"

gText_ApprenticeWhichMonFirst0::
    .string "哇，{PLAYER}！\n我现在进退两难，呜…\p我想和别人战斗，\n却不知道怎么办才好。\p我该怎样排列宝可梦\n的出场顺序以达到最佳效果？\p请告诉我，{PLAYER}。\n如果你是我，你会先派出这些\l宝可梦中的哪一个？$"

gText_ApprenticeMonFirstThanks0::
    .string "我的{STR_VAR_1}应该打头阵？\n哇啊啊！\p哦！对不起！\n你能替我决定出场顺序\l我高兴得都哭了…\p太感谢你了！$"

gText_ApprenticeWhichMonFirst1::
    .string "耶！是{PLAYER}！\n太好了！我正好想问你件事！\p嗯，我的这些宝可梦，哪一个\n应该先出场？$"

gText_ApprenticeMonFirstThanks1::
    .string "我的{STR_VAR_1}？没错。\n我会这么做的！\p谢谢你的教导！$"

gText_ApprenticeWhichMonFirst2::
    .string "{PLAYER}，你好！\p我认为对战中宝可梦\n的出场顺序至关重要。\p我的这些宝可梦，\n哪一个应该先出场？$"

gText_ApprenticeMonFirstThanks2::
    .string "我的{STR_VAR_1}打头阵？\n我明白了！\p再见！$"

gText_ApprenticeWhichMonFirst3::
    .string "你好，{PLAYER}…\n不好意思我又有\l问题来打搅你了。\p我现在没什么自信\n没有你，{PLAYER}，我都不知道该怎么办。\p现在花时间想这个\n可能是庸人自扰\l但我就是无法做出选择…\p我应该先让哪一个\n宝可梦出场呢？$"

gText_ApprenticeMonFirstThanks3::
    .string "我的{STR_VAR_1}？\n明白了！\p真不感相信你能\n耐着性子回答我的问题！\p光是和你说话我\n就无比感激了…谢谢你！$"

gText_ApprenticeWhichMonFirst4::
    .string "哦，{PLAYER}{KUN}！是我！\n真高兴能见到你\l我现在碰到了一点问题。\p我决定不了我的宝可梦的\n出场顺序。你能替我决定吗？\p哦，你目前不需要全部\n定下来。\p不如替我决定哪一个\n宝可梦先出场吧？$"

gText_ApprenticeMonFirstThanks4::
    .string "我的{STR_VAR_1}？太棒了！\p反正是你做的决定，\n{PLAYER}{KUN}，我即使输了\l也不丢人。\p就这样，我还会向你咨询的。\n再见！$"

gText_ApprenticeWhichMonFirst5::
    .string "嘿，{PLAYER}{KUN}老师！\n我今天又忙得不行！\p我得骑车，购物，\n还要哼哼小曲。\p我都没时间决定\n怎样排列我的宝可梦。\p你能不能看看我的宝可梦？\n哪一个应该先出场？$"

gText_ApprenticeMonFirstThanks5::
    .string "明白了。\n把我的{STR_VAR_1}放在队首\l这个时间我还是有的！\p哎呀，我的女朋友在等我呢！\n谢谢你！回见！$"

gText_ApprenticeWhichMonFirst6::
    .string "呀呵！嘿，{PLAYER}！\n你总是这样威风凛凛！\p听我说，我这次又要有求\n于你！还是那些事！\p来点鼓声！！\n我的问题是关于我的队伍的。\p我的宝可梦中哪一个\n应该打头阵？$"

gText_ApprenticeMonFirstThanks6::
    .string "嗯！\n你是说我的{STR_VAR_1}！\l真是精彩的回答，谢谢！\p我今天想问你的\n就这么多。\p以后再见吧？\n谢谢你！$"

gText_ApprenticeWhichMonFirst7::
    .string "谢谢你能抽空\n和我聊天，{PLAYER}。\p我知道我在利用你的善意\n不过你能不能给我点建议？\p我希望你能替我决定\n宝可梦的排序。\p能不能告诉我\n哪一个宝可梦应该先出场？$"

gText_ApprenticeMonFirstThanks7::
    .string "我的{STR_VAR_1}！\n我马上就去做！\p谢谢你，{PLAYER}。\n希望下次还能找你帮忙。\l请多保重！$"

gText_ApprenticeWhichMonFirst8::
    .string "哎呀！{PLAYER}！\n我…我真高兴能够再次见到你！\p我的宝可梦已经大有\n进步了！\p但我不能保持常胜。似乎\n第一个出场的宝可梦至关重要。\p{PLAYER}，我需要你的帮助！\p请替我决定哪一个宝可梦\n应该先出场！$"

gText_ApprenticeMonFirstThanks8::
    .string "唉…我真是高兴死了…\p能让你替我决定\n这简直就像是在做梦，{PLAYER}。\p我明白了！\n我会先派出{STR_VAR_1}的！\p希望你以后\n还能再教教我。$"

gText_ApprenticeWhichMonFirst9::
    .string "你好，你好！\n我的导师，{PLAYER}{KUN}！\l今天再给我一些建议吧！\p你瞧，我现在组建了一支\n3宝可梦战队。目前一切都很顺利。\p但是整个战队的顺序\n还没有定下来。\p这就是你要发挥的地方，{PLAYER}{KUN}！\n你来决定哪一个宝可梦打头阵吧！\p不要害羞，说出来吧！$"

gText_ApprenticeMonFirstThanks9::
    .string "啊-嗯，我的{STR_VAR_1}做领队！\n好的，好的！\l我会重新组队的！\p谢谢你再次帮忙！\n再见！$"

gText_ApprenticeWhichMonFirst10::
    .string "{PLAYER}{KUN}，听着！\n我遇到危机了！\p我的那三只宝可梦同时\n加入了战斗！\p这当然是不可能的！\n哇哈哈！\p说正事吧。\n我不擅长决定\l宝可梦的出场顺序。\p不如你替我决定\n哪一个宝可梦先出场吧，师傅？$"

gText_ApprenticeMonFirstThanks10::
    .string "哦，你选的是{STR_VAR_1}？\n那我绝不选它！\p开玩笑啦！\n我会听从你的教导的，师傅！\p谢谢你，师傅！\n希望你以后还能教导我！$"

gText_ApprenticeWhichMonFirst11::
    .string "啊-呵！\n我是说啊-呵！\p我是无敌的快嘴皮水手！\n我要问你一个\l十分有水平的问题！\p我在队伍的排列上遇到了麻烦\n希望你能给点建议！\p我的队伍中哪一个应该\n打头阵呢？$"

gText_ApprenticeMonFirstThanks11::
    .string "好的，我明白你的意思了！\n我肯定会调换顺序的！\p说到建议，\n{PLAYER}，你的话总会令我满意！$"

gText_ApprenticeWhichMonFirst12::
    .string "呀呵，{PLAYER}！\n你最近怎么样？\p我该怎么办？直接问你？\n嗯，我想问你件事！\l你接受我吗？\l你当然接受我！\p你得决定我的宝可梦中\n哪一个先出场！\l就这么多。$"

gText_ApprenticeMonFirstThanks12::
    .string "我的{STR_VAR_1}？好的！\n我会贯彻执行的！\p好了，{PLAYER}，我要自由驰骋，\n你可别忘了我这名学生。\p再见，我的好朋友！$"

gText_ApprenticeWhichMonFirst13::
    .string "…呜…哦…{PLAYER}{KUN}…\n我突然肚子疼…\p…现在好一些了…\p我肯定是太担忧了\n一直在想如何排列\l我的宝可梦。\p事到如今，\n我希望你替我决定。\p{PLAYER}{KUN}，我的宝可梦中\n哪一个先出场我才会赢？$"

gText_ApprenticeMonFirstThanks13::
    .string "嗯，好的。\n我的{STR_VAR_1}先出场。\p我吃过晚饭后\n就去修改顺序。\p希望我以后还能这样\n向你咨询。$"

gText_ApprenticeWhichMonFirst14::
    .string "呃…嗯…\n{PLAYER}{KUN}？\p请不要这样看着我。\n我都觉得脸红了。\p嗯…\n我迫切需要你的建议。\p真是有些难以启齿，\n我组建了一支3-宝可梦的队伍。\l可是却决定不了出场顺序。\p哪一个宝可梦先出场\n我才会有胜算？$"

gText_ApprenticeMonFirstThanks14::
    .string "哦…好的！\n我会让{STR_VAR_1}打头阵的。\p希望我能毫不气馁\n奋力拼搏…\p谢谢你，{PLAYER}{KUN}。\n如果我们还能见面的话\l请再给我些建议。$"

gText_ApprenticeWhichMonFirst15::
    .string "嗯？你好像是{PLAYER}{KUN}…\n真的是你吗？\l该不会是冒牌的吧？\p哦，不，不，不，别担心！\n如果你真的是{PLAYER}，\l请原谅我的无礼。\p我现在需要你的建议。\p我组建了一支宝可梦战队。\n希望你能告诉我应该由\l哪一个宝可梦打头阵。$"

gText_ApprenticeMonFirstThanks15::
    .string "我的{STR_VAR_1}…\n你不是开玩笑吧？\p我明白了。那就这么着吧。\n谢谢你抽空回答问题。\p我现在虽然还不强\n但我一定会努力的。\p回见！$"

gText_ApprenticeWhichMon0::
    .string "呜呜…\n啊，{PLAYER}！\p你来得正好！\n有些事我不知道该怎么办…\p我不知道我该选\n哪只宝可梦，\p不知道该\n选{STR_VAR_1}还是{STR_VAR_2}…\p{PLAYER}，你说我用哪只\n才会赢呢？$"

gText_ApprenticeMonThanks0::
    .string "呜呜…我…我明白了！\n啊，对不起！\l我高兴得都哭出来了…\p我一定要努力抓一只\n{STR_VAR_1}！\p非常感谢！$"

gText_ApprenticeWhichMon1::
    .string "耶！是{PLAYER}！\n呀，你来得正好！\l再给我点建议吧！\p呃，我已经搞不清楚了，我应该\n用我的{STR_VAR_1}还是{STR_VAR_2}…\p我该怎么办，\n{PLAYER}？$"

gText_ApprenticeMonThanks1::
    .string "啊，那么说{STR_VAR_1}更好一点！\n好，就这么决定了！\p谢谢你的帮忙！$"

gText_ApprenticeWhichMon2::
    .string "{PLAYER}，你好！\n我想问你个问题。\p我在犹豫该用\n{STR_VAR_1}还是{STR_VAR_2}，\p你说哪只宝可梦\n更强一点？$"

gText_ApprenticeMonThanks2::
    .string "你说是{STR_VAR_1}吗？\n嗯，我明白了！\p我这就去抓一只\n很强的{STR_VAR_1}来！\p回头见！$"

gText_ApprenticeWhichMon3::
    .string "你好，{PLAYER}…\p呃，你好像已经忘了\n我这个人了…\p…但没关系，我还是希望\n你能给我点建议…\p我不知道我该培养\n哪只宝可梦…\p我看中了两只宝可梦\n{STR_VAR_1}和{STR_VAR_2}，但\l下面我就不知道该怎么办了…\p{PLAYER}，很抱歉打扰你，\n但希望你能给我点建议。$"

gText_ApprenticeMonThanks3::
    .string "但野生{STR_VAR_1}会\n注意到我吗？\p我会努力的！\p但我能不能抓到…\n不对，我要尽全力做到！\p谢谢！$"

gText_ApprenticeWhichMon4::
    .string "噢，{PLAYER}{KUN}！很高兴见到你！\n我还打算去找你呢！\p你能帮我选一下我该\n用哪只宝可梦吗？\p比如…\n{STR_VAR_1}和\l{STR_VAR_2}怎么样？\p你说哪一个\n更好一点？$"

gText_ApprenticeMonThanks4::
    .string "{STR_VAR_1}？太好了！\p这是你替我做的决定，\n{PLAYER}{KUN}，\l即使我输了我也不会失望的。\p好吧，下次我还会找你请教的，\n再见！$"

gText_ApprenticeWhichMon5::
    .string "这不是{PLAYER}{KUN}嘛！一切还好吧？\n我还是像以前一样忙！\p我也想养宝可梦，\n但我还没决定\l要养哪只宝可梦。\p你觉得{STR_VAR_1}强吗？\n但也不能忽视{STR_VAR_2}啊。\p{PLAYER}{KUN}，给我点建议吧！\n哪个更适合我？$"

gText_ApprenticeMonThanks5::
    .string "知道了。\n我会努力去抓你说的\l那个{STR_VAR_1}的。\p真高兴能碰上你这样的好老师。\n谢谢啦，再见！$"

gText_ApprenticeWhichMon6::
    .string "噢！\n呀，是{PLAYER}！\p我才没有浪费时间去\n向朋友吹嘘碰上你的事！\p今天我还想麻烦你，\n对你来说很简单的！\p拜托了！\n我的问题是…\p如果我要在{STR_VAR_1}与\n{STR_VAR_2}两只宝可梦中选一只来养，\l我该选哪个？$"

gText_ApprenticeMonThanks6::
    .string "啊啊！\n你说是{STR_VAR_1}！\l真棒的答案！\p今天我想问你的\n就这些，\p下次再见吧。\n真的很感谢你！$"

gText_ApprenticeWhichMon7::
    .string "啊，是你，{PLAYER}？\n很高兴再见到你！\p我成了你的徒弟后，\n越来越有信心了。\p我想培养一只\n自己的宝可梦！\p{PLAYER}，能麻烦你帮我\n选一只宝可梦吗？\p我该培养{STR_VAR_1}\n还是{STR_VAR_2}？\l哪只宝可梦更适合我？$"

gText_ApprenticeMonThanks7::
    .string "{STR_VAR_1}吗？\n我马上就去抓一只！\p谢谢，{PLAYER}，\n希望下次还能请你帮忙。\l祝你一路顺风！$"

gText_ApprenticeWhichMon8::
    .string "哎！{PLAYER}！又见到你了！\n太…太棒了！\p啊，啊，啊，我知道\n我不能白白放掉这次机会！\p能请你帮个忙吗，{PLAYER}\n帮我选一只宝可梦吧！\p告诉我，{STR_VAR_1}和{STR_VAR_2}\n哪只更好一点！$"

gText_ApprenticeMonThanks8::
    .string "哇！你帮我选了一只！\n我要尽我的全力\l培养{STR_VAR_1}。\p希望以后你还能\n再教我。$"

gText_ApprenticeWhichMon9::
    .string "哎，喂！\n老师！{PLAYER}{KUN}！\p嗨，我一直在找你，\n希望你能再给我些建议！\p哪只宝可梦更适合我？\n{STR_VAR_1}还是{STR_VAR_2}？\p别顾忌什么，\n告诉我吧！$"

gText_ApprenticeMonThanks9::
    .string "啊哈，是{STR_VAR_1}\n好，太好了！\l我马上就去抓一只！\p还是多谢了！\n拜拜！$"

gText_ApprenticeWhichMon10::
    .string "{PLAYER}{KUN}，听好，有大消息了！\n我抓了一只稀有的宝可梦！\p当然，我在撒谎！\n啊哈哈哈！\p但我不太擅长\n抓宝可梦这一点\l可不是撒谎。\p帮我想想我该\n抓什么宝可梦好吗，\l老师？\p{STR_VAR_1}和{STR_VAR_2}\n哪只更好？$"

gText_ApprenticeMonThanks10::
    .string "你说要选{STR_VAR_1}吗？\n那么我就去抓另一种吧！\p哈哈，开玩笑的！\n我听你的，老师！\p谢谢你！\n希望你以后还能教我！$"

gText_ApprenticeWhichMon11::
    .string "W-E-I！\n拼出来就是喂！\p唱RAP的水手就是我！\n你还记得我是谁？\p今天有一个宝可梦的问题\n等你来回答！\p如果我要在\n{STR_VAR_1}和{STR_VAR_2}之中选一只，\l我应该要抓哪只？$"

gText_ApprenticeMonThanks11::
    .string "你说的{STR_VAR_1}，哈，哈！\n我马上就去抓来它！\p如果我想要什么建议，\n{PLAYER}，我总会听听你的话！$"

gText_ApprenticeWhichMon12::
    .string "哇，这不是{PLAYER}吗？\p我该怎么办？给我建议？\n当然！我已经在和你说话了。\p已经很久了，是该捅破窗户纸的\n时候了，我需要你的建议！\l你能告诉我吗？\l你当然会告诉我！\p我该用哪个宝可梦？\n{STR_VAR_1}和{STR_VAR_2}，\l我该选哪一个？$"

gText_ApprenticeMonThanks12::
    .string "如果说最好用{STR_VAR_1}，\n那我就听你的！\p哎，{PLAYER}，我要去自由地流浪，\n但你不要忘记我。\p下回再见，我的朋友！$"

gText_ApprenticeWhichMon13::
    .string "啊，你好，{PLAYER}{KUN}…\n我正在头疼一件事情…\p对于要培养哪只宝可梦\n我已经想得太多了。\p现在只能这样，\n你替我决定好吗？\p{PLAYER}{KUN}，如果要从\n{STR_VAR_1}和{STR_VAR_2}之中选一个，\l那么选择哪个好呢？$"

gText_ApprenticeMonThanks13::
    .string "晤，{STR_VAR_1}，好吧，\n我的头疼好一点之后就去抓一只来。\p希望以后还能麻烦你\n帮我决定这种事情。$"

gText_ApprenticeWhichMon14::
    .string "呃…嗯…\n{PLAYER}{KUN}…？\p拜托别那么看着我。\n我太紧张了…\l我…我希望你能给我点建议。\p真…真不好意思，\n能帮我决定一下我该用什么宝可梦吗？\p{STR_VAR_1}和{STR_VAR_2}之中\n我该选哪个？$"

gText_ApprenticeMonThanks14::
    .string "啊…好的！\n我会努力找到{STR_VAR_1}的。\p但愿我能做到最好，\n不要这么慌乱。\p谢谢你，{PLAYER}{KUN}，\n下次我们见面的时候\l希望你还能帮我的忙。$"

gText_ApprenticeWhichMon15::
    .string "嗯？你是{PLAYER}{KUN}吗…\n你真的是吗？\p哎，没什么，是本人的话就太好了。\n我想要你\l给我点建议，\p是关于我使用的宝可梦的。\p如果我要在{STR_VAR_1}和{STR_VAR_2}\n两只宝可梦中选一个，\l哪个会更适合我？$"

gText_ApprenticeMonThanks15::
    .string "{STR_VAR_1}？\n你确定吗？\p知道了，那样就太好了，\n谢谢你的帮忙。\p希望就算是我也能\n沉着地解决这件事。\p下次再见吧！$"

gText_ApprenticeWhichMove0::
    .string "哇！噢，{PLAYER}！\n流鼻涕…打嗝…\p我只有一个选择！\n我无法决定我的\l行动{STR_VAR_1}…\p请，请，{PLAYER}。\n你能为我做决定吗？\p因为我{STR_VAR_1}，哪个决定\n才是更好的选择：{STR_VAR_2}\l或者{STR_VAR_3}？$"

gText_ApprenticeMoveThanks0::
    .string "{STR_VAR_1}？\n哇！\p哦！对不起，{PLAYER}！\n你为我做的这个决定使我非常满意\l满意，我在哭…\p流鼻涕…\n非常感谢你！$"

gText_ApprenticeWhichMove1::
    .string "唉！嗨，{PLAYER}！\n我又需要你的建议！\p我想要教我很酷的{STR_VAR_1}\n行动。\p我喜欢决定中的任何一个\n{STR_VAR_2}或者{STR_VAR_3}。\l你的建议是什么？$"

gText_ApprenticeMoveThanks1::
    .string "{STR_VAR_1}更好吗？我想是的！\n好，我将和那一起去！\p老师，如果我们再次在这里见面，\n请教我其它东西！$"

gText_ApprenticeWhichMove2::
    .string "{PLAYER}，你好！\n对于我来说{STR_VAR_1}，有点\l担心你的决定。\p你看，这个决定{STR_VAR_2}\n和{STR_VAR_3}。\p对于我来说哪个更好更棒\n{STR_VAR_1}？$"

gText_ApprenticeMoveThanks2::
    .string "{STR_VAR_1}是你的选择吗？\n好，决定这样了！\p我将立刻{STR_VAR_1}去\n教我的宠物！\p再见！$"

gText_ApprenticeWhichMove3::
    .string "哦，{PLAYER}…\n不，真的，我没希望了！\p我决定饲养一个宠物，\n但是现在我甚至不能决定\l让它学习什么…\p我知道这并不意味着给你任何\n东西，{PLAYER}。\p但是却意味着给我很多…\p请，{PLAYER}，你你能帮\n我做一个决定吗{STR_VAR_1}？\p如果你在{STR_VAR_2}和{STR_VAR_3}\n之间选择的话…$"

gText_ApprenticeMoveThanks3::
    .string "我明白了！\p但对于我来说还要进行\n{STR_VAR_1}学习…\l不！我会做得更好！\p谢谢你！$"

gText_ApprenticeWhichMove4::
    .string "噢，{PLAYER}{KUN}！\n我也正希望遇见你！\p我正想知道什么活动\n适合我{STR_VAR_1}。\p我不能决定，你能代替我做\n决定吗？\p例如…怎样进行行动\n{STR_VAR_2} {STR_VAR_3}？\l哪一个更好？$"

gText_ApprenticeMoveThanks4::
    .string "{STR_VAR_1}？太谢谢你了！\p知道你做的决定，\n{PLAYER}{KUN}，如果我失败了我，会十\l分不安的。\p好，我将再次接受你的建议。\n再见！$"

gText_ApprenticeWhichMove5::
    .string "怎么会这么忙？\n嗨，如果不是这样{PLAYER}{KUN}！\l你将怎么做？\p从我早上一起来，我就做了\n慢跑，游泳，和吃饭！\p你不相信我会这么忙吗！\p我甚至不能决定我的\n{STR_VAR_1}学习！\p{STR_VAR_2}看起来不错，哼？\n但是{STR_VAR_3}也很适合。\p{PLAYER}{KUN}，给一些好的\n建议！怎样做将有益于我？$"

gText_ApprenticeMoveThanks5::
    .string "好，明白了。\n我将在我的安排中在家里\l学习这些。\p我高兴见到一位好顾问。\n谢谢！再见！$"

gText_ApprenticeWhichMove6::
    .string "噢！好幸运！\n我又遇见你了，{PLAYER}！\l我今天再次需要你的建议。\p请敲打！\n我的问题是…\p对于我来说{STR_VAR_1}，哪个行动\n最适合，{STR_VAR_2}或者\l{STR_VAR_3}？$"

gText_ApprenticeMoveThanks6::
    .string "啊！\n{STR_VAR_1}，你说的！\l感谢你精彩的回答！\p我猜这些就是我今天所有\n想问你的东西了。\p让我们再次在这里相见，好吗？\n谢谢！$"

gText_ApprenticeWhichMove7::
    .string "噢，你好，{PLAYER}。\n我十分信任你？\p我又来寻求你的建议了。\n这次是关于我的爱情{STR_VAR_1}。\p用什么方式能使我惹\n人爱{STR_VAR_1}？\l{STR_VAR_2}或者{STR_VAR_3}？$"

gText_ApprenticeMoveThanks7::
    .string "{STR_VAR_1} 这！\n我将教你正确的方法！\p谢谢，{PLAYER}。\n我希望能够再次得到你的指教。\l请小心！$"

gText_ApprenticeWhichMove8::
    .string "呀！{PLAYER}！有见到你了！\n我…我非常高兴！\p每当我需要帮助的时候，你总能\n出现，{PLAYER}！\p今天，我想要你为我推荐\n一个活动！\p请为我选择一个\n活动{STR_VAR_1}！\p哪个活动更好，\n{STR_VAR_2}或者{STR_VAR_3}？$"

gText_ApprenticeMoveThanks8::
    .string "哦-哦-哦！谢谢！\n{STR_VAR_1}这！\l完全了解了！\p我希望你下次教会我更多\n东西。$"

gText_ApprenticeWhichMove9::
    .string "你好，{PLAYER}{KUN}，很好！\n我今天需要你的\l更高明的建议！\p我的最好的行动将是\n什么{STR_VAR_1}？\p可以让我赢得那样的\n东西！\p会是什么{STR_VAR_2}？\n或者{STR_VAR_3}？$"

gText_ApprenticeMoveThanks9::
    .string "啊哈，{STR_VAR_1}这是！\n是，很好！\l我将教导它，就像，人参一样！\p很好，永远感谢你！\n再见！$"

gText_ApprenticeWhichMove10::
    .string "{PLAYER}{KUN}，好狂热啊！\p我的宠物！\n它学到了6个技术！\p当然我是开玩笑的！\n哇哈哈哈！\p虽然这不是谎言。\n我的宠物学到这些活动使我感觉\l不是很好。\p所以，到底我怎么选择哪个活动\n来学呢？\p{STR_VAR_2}或者{STR_VAR_3}--哪个\n我学最好{STR_VAR_1}呢？$"

gText_ApprenticeMoveThanks10::
    .string "好，所以这是{STR_VAR_1}你的选择？\n那么我将选择其他的行动！\p仅仅玩笑而已！\n主人我将服从你的教导！\p谢谢主人！\n我希望你继续教导我！$"

gText_ApprenticeWhichMove11::
    .string "A-H-O-Y！\n拼写是ahoy！\p我是一个唱Rap的海员！\n我总用它，不要问我为什么。\p今天，我有一个恳求你的建议\n的问题！\p{STR_VAR_2}并且{STR_VAR_3}是\n行动。什么对于我来说是\l能给{STR_VAR_1}带来最佳状态？$"

gText_ApprenticeMoveThanks11::
    .string "{STR_VAR_1}，你说，嗨，嗨！\n我将立刻去教！\p如果我需要建议，\n{PLAYER}，你的话就是最好的！$"

gText_ApprenticeWhichMove12::
    .string "哦，也，如果不是{PLAYER}！\p我将怎么做？得到你的建议？\n为什么不呢？我已经告诉你了！\p{PLAYER}，我是否给了你一个惊喜？\n我想要你的建议，可以吗？\p你能接受我吗？\n你将要接受我！\p我的{STR_VAR_1}--要使用什么？\n或者{STR_VAR_2}是{STR_VAR_3}，\l你选择的是什么？$"

gText_ApprenticeMoveThanks12::
    .string "如果{STR_VAR_1}这是最好的，\n我将依你的建议去做！\p那么，{PLAYER}，我就要走了，\n但是你不要忘记我。\p再见，我最好的朋友！$"

gText_ApprenticeWhichMove13::
    .string "呀！啊！哦，{PLAYER}{KUN}…\n我很冷，我做…\p我想要我的宠物进行，\n但是我不能让它达到这个地步…\p于是，事情就这样了，\n我需要你给我一个建议。\p{PLAYER}{KUN}，如果我在这之间有\n{STR_VAR_2}一个{STR_VAR_3}选择\l{STR_VAR_1}，会是哪个呢？$"

gText_ApprenticeMoveThanks13::
    .string "恩，{STR_VAR_1}，对了。咳咳！\n我好了后将教它。\p我希望我能一直像这样\n帮助你。$"

gText_ApprenticeWhichMove14::
    .string "嗯…呃…\n{PLAYER}{KUN}…？\p请不要那样看着我。\n我感到很混乱…\l我…我需要你的建议。\p我…我已经被囚禁了，但是我不能\n决定要教我的宠物什么\l活动。\p这是为了我{STR_VAR_1}。\n如果是这样选择{STR_VAR_2}\l{STR_VAR_3}，哪个会是更好的呢？$"

gText_ApprenticeMoveThanks14::
    .string "噢…好的！\n我试一下{STR_VAR_1}。\p我希望我能教那样的活动…\n这太伤脑筋了…\p谢谢，{PLAYER}{KUN}。\n如果我们再见面，我希望你能\l给我帮助。$"

gText_ApprenticeWhichMove15::
    .string "嗯？你出现了{PLAYER}{KUN}…\n但是你是真的吗？\p或许你是一个\n模仿者？\p不，不，如果你是真的，那就好了。\n不需要被覆盖，我保证！\p顺便说一下，我非常喜欢得到你\n的建议。\p我也是关于我的{STR_VAR_1}。\p什么活动会是更好的选择\n选择，{STR_VAR_2}或者{STR_VAR_3}？$"

gText_ApprenticeMoveThanks15::
    .string "{STR_VAR_1}？\n那儿没有问题了？\p我知道。如果很小心，一切都会很好。\n非常谢谢你。\p我希望我的宠物能学到一些\n东西。\p让我们再见面吧！$"

gText_ApprenticePickWinSpeech0::
    .string "哦…{PLAYER}？\n这是{PLAYER}！\l哦！吸…泣…听！\p我…当我战斗时，我感到很紧张，\n如果我赢了，我甚至不能说话…\p当我赢了我希望能很酷的说话\n说话…\p请，请，{PLAYER}！\n你能教我赢了后不酷并且很酷的\l说话吗？$"

gText_ApprenticeWinSpeechThanks0::
    .string "{STR_VAR_1}\p太棒了！厉害！哇啊啊啊！\n这已经很酷了！\p噢…对不起…\n我太高兴了，我要哭…\p流鼻涕…{PLAYER}！\n谢谢你的每件事！\p因为你我将要表演一场\n精彩的战斗，{PLAYER}！\p{PLAYER}…\n下次…我们将战斗！$"

gText_ApprenticePickWinSpeech1::
    .string "耶！这是{PLAYER}！你好！\n我想问你一些事情！\p我一旦赢了这个比赛那将事\n一件很酷的事。\p你能推荐一些很酷事情\n说吗？$"

gText_ApprenticeWinSpeechThanks1::
    .string "{STR_VAR_1}\p哦，哇啊！太酷了！\n好的，我将会这样说！\p谢谢你这段时间一直在教我！\n无论我今后走哪里我都\l会尽力的！\p当我们再见面，那将是一场\n战斗！$"

gText_ApprenticePickWinSpeech2::
    .string "你好啊，{PLAYER}！\p我和我的宝可梦一切都\n准备妥当，只剩下那么一件事。\p我想我获胜的时候找句话来欢呼\n应该是件不错的事情。\p你认为应该\n怎么欢呼呢？$"

gText_ApprenticeWinSpeechThanks2::
    .string "{STR_VAR_1}\p…太帅了！\n我决定就用这句了！\p我走到哪里就\n战斗到哪里。\p说不定有一天，我就能打败\n你了，{PLAYER}。\p下次见面时，就让我们痛快\n地打一场吧！$"

gText_ApprenticePickWinSpeech3::
    .string "你好，{PLAYER}…\n很抱歉打扰你，可是我真的绝望了…\p我好不容易…\n好不容易赢得了比赛，可我却\l不知道说些什么…\p{PLAYER}，我知道这对你来说\n根本算不了什么。\p但对我而言是件大事…\p拜托了，{PLAYER}，请告诉我胜利后\n要说的台词好吗？$"

gText_ApprenticeWinSpeechThanks3::
    .string "{STR_VAR_1}\p太棒了…\p啊…我刚才的表现是不是\n很棒呢？\p不！我必须全力以赴！\p{PLAYER}，非常感谢你能\n容忍我这么久…\p我保证从现在开始我会全力以赴的。\p我知道你很快就会忘掉\n我这种人的，但我们一定会\l再见面的！$"

gText_ApprenticePickWinSpeech4::
    .string "啊啦，{PLAYER}{KUN}。\n稍微听我说两句。\p我知道我给人的印象不是\n不好就是没礼貌…\p当我打赢时，\n我会自大起来。\p我不希望人们讨厌我，\n所以我想在胜利时\l说些什么以示友好。\p但我根本不知道该怎么办！\n你能给我出出主意吗？$"

gText_ApprenticeWinSpeechThanks4::
    .string "{STR_VAR_1}\p真不赖！\n没错，这就是我要的答案！\p我要踏平这里并且\n用你刚才教我的\l向对访问候。\p对不起，刚才我太\n狂妄了！\p下次见面时和我打一场怎么样？\n回见！$"

gText_ApprenticePickWinSpeech5::
    .string "啊，忙死了，忙死了！\n噢，嘿，我正找你呢，{PLAYER}{KUN}。\p身体还好吗？\n这儿对我来说还是和平常一样。\p每天都要跑步，战斗，\n还要画图。我咋这么忙呢？\p就算我再忙，也不能\n打赢之后\l抬腿就走吧。\p所以，在我离开时\n说些什么才能让我\l显得更酷呢？帮帮我吧，{PLAYER}{KUN}！$"

gText_ApprenticeWinSpeechThanks5::
    .string "{STR_VAR_1}\p太好了，就是它了。\n我会找机会这么说的！\p老实说，有你这么好的朋友\n真是我的福气啊。\p不知怎的，我一有时间\n就想和人对战。\p谢谢你，{PLAYER}{KUN}！\n总有一天，你和我，我们会打一场的！$"

gText_ApprenticePickWinSpeech6::
    .string "我真走运！\n{PLAYER}！很高兴见到你！\l和平常一样，我需要你的帮助！\p请听我说，是这样！\n我最后的问题就是…\p如果我想在胜利后\n显得又炫又酷，我应该\l说点儿什么呢？$"

gText_ApprenticeWinSpeechThanks6::
    .string "{STR_VAR_1}\p真…真是太棒了！\n真是又炫又酷！就是它了！\p…你听，我认为这样\n就很不错，是吧？\p啊，想到以后就要\n向其他训练师挑战。\p{PLAYER}，你真的帮了个大忙。\p说不定哪一天，就是我们\n对战的日子了！\p谢谢你的帮助！$"

gText_ApprenticePickWinSpeech7::
    .string "嗨，{PLAYER}。\n见到你非常高兴！\p我不再为我的宝可梦\n的事情操心了。\p我是担心我自己…\p你知道作为一名训练师在获胜\n之后以应该说点什么吗？\p当然，我希望\n我也能做到！\p那么，我获胜时\n应该说什么呢？$"

gText_ApprenticeWinSpeechThanks7::
    .string "{STR_VAR_1}\p啊！太棒了！这话让我清醒\n并且感到如获新生！\p我一定将它用好！\p现在，我必须提升实力，\n{PLAYER}…\p我要和其他人战斗，\n但决不会忘记你的教导。\p没准儿哪天…\n回见！$"

gText_ApprenticePickWinSpeech8::
    .string "呃！你是{PLAYER}吧！\n我… 能见到你真是太高兴了！\p噢-噢-噢！我有些事\n要向你请教一下！\p不久之前，我赢得了比赛。\n那真是令人眼花缭乱！\p但是我在万分高兴之余\n就说不出话来了！\p所以，{PLAYER}，我想请你现在\n为我指明一条出路！$"

gText_ApprenticeWinSpeechThanks8::
    .string "{STR_VAR_1}\p哇啊啊啊啊！\n我以后就要这么说了吗？！\l我…高兴得不知说什么好了！\p谢-谢-谢谢你了！\n我现在可以没有遗憾的离开了！\p我要游遍大江南北\n和各种人战斗。\p什么也不说了，{PLAYER}。\n真的，真的，太感谢你了！\p我现在就要走了，但是有一天\n我们会见面并且打一场的！$"

gText_ApprenticePickWinSpeech9::
    .string "喂，你好！\n{PLAYER}{KUN}！\p你知道，我渴望到处流浪并且\n到处战斗。\p但是在这之前，我想请你再次\n帮助我！\p如果我赢了，我应该如何\n向被我打败的训练师\l吹嘘自己的本领呢？$"

gText_ApprenticeWinSpeechThanks9::
    .string "{STR_VAR_1}\p嗯-啊，真有趣！\n嘶，不错！\l我会试着这么说的， 就像是，演员！\p现在，是该说再见的时候了！\n谢谢你的指导！\p那天和我打一场吧，怎么样？\n再见！$"

gText_ApprenticePickWinSpeech10::
    .string "{PLAYER}{KUN}，有大麻烦了！\p当我赢了的时候，我至少\n吹了一个小时的牛！\p当然，我是说着玩儿的！\n哇哈哈哈哈！\p尽管是这样，可是。\n我并不怎么擅长聊天。\p所以，你认为我获胜后\n应该怎么说呢，\l老师？$"

gText_ApprenticeWinSpeechThanks10::
    .string "{STR_VAR_1}\p我应该这么说，是吗？\n那时，我就离开了那里！\p还是小孩子的时候！\n我会谨遵教诲的，老师！\p谢谢你的教导，\n老师！\p我终于知道了如何成为\n一名训练师。\p我要外出并且打败\n更多的训练师。\p可能你后还会遇到你，老师！\p就这样！\n再见了，老师！$"

gText_ApprenticePickWinSpeech11::
    .string "NiHao！\n拼出来是你好！\p我就是唱Rap的水手！\n好了好了，\l这是我最后的问题了！\p我要向你讨教\n关于言词的问题！\p如果我赢了比赛，我该怎么说\n才能显得很酷呢？$"

gText_ApprenticeWinSpeechThanks11::
    .string "{STR_VAR_1}\p太完美了！以后就用这句了。\n我会把它用好的！\p现在，我想我会是，\n我们那最棒的！\p感谢你能教我。\n我要尽情享受战斗去了！\p一---路---平--安！\n一路平安，\l祝你一路平安！$"

gText_ApprenticePickWinSpeech12::
    .string "噢，耶，{PLAYER}！\n我今天又见到你了！\p我来干啥？再次向你请教？\n为啥不呢？我已经向你请教过了！\p不管怎样，{PLAYER}…\n你能接受我吗？\l你能！\l我需要得到更多的建议！\p是关于我要如何欢呼的。\n当战斗获胜时\l很帅地欢呼。\p来吧，我要听听你的意见！$"

gText_ApprenticeWinSpeechThanks12::
    .string "{STR_VAR_1}\p好，太好了！\n我要用它因为它很简练！\p我还有话要说。\n人们分开时都要挥手告别。\p不过也许有一天我们会再见面的，\n而且注定要战斗的。\p但是，现在确实是该告别的时候了。\p那么，{PLAYER}，我要到处流浪，\n但请不要忘记我！\p保重，{PLAYER}！\n宝贝儿！$"

gText_ApprenticePickWinSpeech13::
    .string "{PLAYER}{KUN}，我完了…\n我在不停地流鼻涕…\p我曾试着想过在我胜利时\n怎么说才能更酷。\p这让我倍受激励，我哭了起来，\n并且开始不停流鼻涕…\p所以，事情发展成这样，\n我需要你的帮助，{PLAYER}{KUN}。\p当我取得胜利时，\n我该说点什么呢？$"

gText_ApprenticeWinSpeechThanks13::
    .string "{STR_VAR_1}\p… … …太棒了。\n不，真是太感动了！\l我又开始流泪了！\p但是不用管我的眼泪\n和鼻子，我以后就这么说了！\p我还有事要和你说，\n{PLAYER}{KUN}。\p现在开始，我们就是对手了！\n谢谢你的帮助！$"

gText_ApprenticePickWinSpeech14::
    .string "呃… 唔…\n{PLAYER}{KUN}…\p请不要这样看着我。\n你弄得我很紧张。\p我…我还得向你请教。\n在比赛结束之后， 虽然…\p这真的让人难以启齿，\n但是如果我赢了比赛\l我该说些什么呢？$"

gText_ApprenticeWinSpeechThanks14::
    .string "{STR_VAR_1}\p哦… 好的！\n我会试着这么说的！\l我可能会不好意思说出来…\p谢谢你，{PLAYER}{KUN}。\n那么再见了。\p我会按你教的那样做的，\n{PLAYER}{KUN}，而且要做到最好。$"

gText_ApprenticePickWinSpeech15::
    .string "唔？你貌似是{PLAYER}{KUN}…\n是真的吗？\l难道你不是{PLAYER}的人偶？\p噢，不，不，不，别担心！\n如果你真的是本人，\l请原谅我的无礼。\p没必要这么生气吧。我还需要\n你好好指点我呢。\p是关于言词的。\p准确地说，就是在我打赢之后\n应该说些什么呢？$"

gText_ApprenticeWinSpeechThanks15::
    .string "{STR_VAR_1}\p… … … … … …\n当我赢得比赛时…\p{STR_VAR_1}\p…你会当真吗？\p我知道。如果你呢能当真，那就再好不过了。\n十分感谢你能帮我。\p我希望我能\n说好这句话。\p我似乎在寻求帮助时\n有点儿太正经了。\p我现在应该立即和你告别\n并且自己想办法了。\p谢谢你，我的朋友！\n我为刚才对你的怀疑表示道歉！$"
