BattleDome_Text_Potential1::
    .string "真不愧是冠军候选人中的No.1！$"

BattleDome_Text_Potential2::
    .string "必进决赛组。$"

BattleDome_Text_Potential3::
    .string "前三强热门。$"

BattleDome_Text_Potential4::
    .string "夺冠热门。$"

BattleDome_Text_Potential5::
    .string "潜力无限组。$"

BattleDome_Text_Potential6::
    .string "本次大赛黑马。$"

BattleDome_Text_Potential7::
    .string "中上等水平队伍。$"

BattleDome_Text_Potential8::
    .string "本次大赛中等水平队伍。$"

BattleDome_Text_Potential9::
    .string "潜力一般组。$"

BattleDome_Text_Potential10::
    .string "中下等水平队伍。$"

BattleDome_Text_Potential11::
    .string "求胜心切组。$"

BattleDome_Text_Potential12::
    .string "但求一胜组。$"

BattleDome_Text_Potential13::
    .string "弱队一支。$"

BattleDome_Text_Potential14::
    .string "潜力低下组。$"

BattleDome_Text_Potential15::
    .string "夺冠无望组。$"

BattleDome_Text_Potential16::
    .string "毫无胜算组。$"

BattleDome_Text_PotentialDomeAceTucker::
    .string "完美无敌的明星！$"

BattleDome_Text_StyleRiskDisaster::
    .string "时常孤注一掷。$"

BattleDome_Text_StyleEndureLongBattles::
    .string "对战耐力超强。$"

BattleDome_Text_StyleVariesTactics::
    .string "足智多谋。$"

BattleDome_Text_StyleToughWinningPattern::
    .string "老谋深算。$"

BattleDome_Text_StyleUsesVeryRareMove::
    .string "偶尔使用稀有技能。$"

BattleDome_Text_StyleUsesStartlingMoves::
    .string "使用技能制造混乱。$"

BattleDome_Text_StyleConstantlyWatchesHP::
    .string "对战中经常注意HP。$"

BattleDome_Text_StyleStoresAndLoosesPower::
    .string "擅长蓄力攻击。$"

BattleDome_Text_StyleEnfeeblesFoes::
    .string "擅长削弱对手。$"

BattleDome_Text_StylePrefersLuckTactics::
    .string "喜欢使用险招。$"

BattleDome_Text_StyleRegalAtmosphere::
    .string "出招华丽。$"

BattleDome_Text_StylePowerfulLowPPMoves::
    .string "使用强力而且PP值较低的技能。$"

BattleDome_Text_StyleEnfeebleThenAttack::
    .string "擅长削弱对手后再攻击。$"

BattleDome_Text_StyleBattlesWhileEnduring::
    .string "对战时奋不顾身。$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
    .string "擅长扰乱对手情绪。$"

BattleDome_Text_StyleStrongAndStraightforward::
    .string "使用简单而又强力的技能。$"

BattleDome_Text_StyleAggressivelyStrongMoves::
    .string "主动使用强力技能。$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
    .string "擅长躲避对方攻击。$"

BattleDome_Text_StyleUsesUpsettingMoves::
    .string "擅长扰乱对方。$"

BattleDome_Text_StyleUsesPopularMoves::
    .string "使用流行技能。$"

BattleDome_Text_StyleHasPowerfulComboMoves::
    .string "拥有强力连击技。$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
    .string "使用高精度技能。$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
    .string "主动使用华丽技能。$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
    .string "注重进攻。$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
    .string "注重防守。$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
    .string "使用高速强力技能。$"

BattleDome_Text_StyleUsesAddedEffectMoves::
    .string "经常使用带有附加效果的技能。$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
    .string "使用组合恰当的技能。$"

BattleDome_Text_StyleSampleMessage1::
    .string "这是测试信息1。$"

BattleDome_Text_StyleSampleMessage2::
    .string "这是测试信息2。$"

BattleDome_Text_StyleSampleMessage3::
    .string "这是测试信息3。$"

BattleDome_Text_StyleSampleMessage4::
    .string "这是测试信息4。$"

BattleDome_Text_EmphasizesHPAndAtk::
    .string "注重HP和攻击。$"

BattleDome_Text_EmphasizesHPAndDef::
    .string "注重HP和防御。$"

BattleDome_Text_EmphasizesHPAndSpeed::
    .string "注重HP和速度。$"

BattleDome_Text_EmphasizesHPAndSpAtk::
    .string "注重HP和特攻。$"

BattleDome_Text_EmphasizesHPAndSpDef::
    .string "注重HP和特防。$"

BattleDome_Text_EmphasizesAtkAndDef::
    .string "注重攻击和防御。$"

BattleDome_Text_EmphasizesAtkAndSpeed::
    .string "注重攻击和速度。$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
    .string "注重攻击和特攻。$"

BattleDome_Text_EmphasizesAtkAndSpDef::
    .string "注重攻击和特防。$"

BattleDome_Text_EmphasizesDefAndSpeed::
    .string "注重防御和速度。$"

BattleDome_Text_EmphasizesDefAndSpAtk::
    .string "注重防御和特攻。$"

BattleDome_Text_EmphasizesDefAndSpDef::
    .string "注重防御和特防。$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
    .string "注重速度和特攻。$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
    .string "注重速度和特防。$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
    .string "注重特攻和特防。$"

BattleDome_Text_EmphasizesHP::
    .string "注重HP。$"

BattleDome_Text_EmphasizesAtk::
    .string "注重攻击。$"

BattleDome_Text_EmphasizesDef::
    .string "注重防御。$"

BattleDome_Text_EmphasizesSpeed::
    .string "注重速度。$"

BattleDome_Text_EmphasizesSpAtk::
    .string "注重特攻。$"

BattleDome_Text_EmphasizesSpDef::
    .string "注重特防。$"

BattleDome_Text_NeglectsHPAndAtk::
    .string "无视HP和攻击。$"

BattleDome_Text_NeglectsHPAndDef::
    .string "无视HP和防御。$"

BattleDome_Text_NeglectsHPAndSpeed::
    .string "无视HP和速度。$"

BattleDome_Text_NeglectsHPAndSpAtk::
    .string "无视HP和特攻。$"

BattleDome_Text_NeglectsHPAndSpDef::
    .string "无视HP和特防。$"

BattleDome_Text_NeglectsAtkAndDef::
    .string "无视攻击和防御。$"

BattleDome_Text_NeglectsAtkAndSpeed::
    .string "无视攻击和速度。$"

BattleDome_Text_NeglectsAtkAndSpAtk::
    .string "无视攻击和特攻。$"

BattleDome_Text_NeglectsAtkAndSpDef::
    .string "无视攻击和特防。$"

BattleDome_Text_NeglectsDefAndSpeed::
    .string "无视防御和速度。$"

BattleDome_Text_NeglectsDefAndSpAtk::
    .string "无视防御和特攻。$"

BattleDome_Text_NeglectsDefAndSpDef::
    .string "无视防御和特防。$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
    .string "无视速度和特攻。$"

BattleDome_Text_NeglectsSpeedAndSpDef::
    .string "无视速度和特防。$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
    .string "无视特攻和特防。$"

BattleDome_Text_NeglectsHP::
    .string "无视HP。$"

BattleDome_Text_NeglectsAtk::
    .string "无视攻击。$"

BattleDome_Text_NeglectsDef::
    .string "无视防御。$"

BattleDome_Text_NeglectsSpeed::
    .string "无视速度。$"

BattleDome_Text_NeglectsSpAtk::
    .string "无视特攻。$"

BattleDome_Text_NeglectsSpDef::
    .string "无视特防。$"

BattleDome_Text_RaisesMonsWellBalanced::
    .string "使用恰当方法养育宝可梦。$"

BattleDome_Text_LetTheBattleBegin::
    .string "开战吧！$"

BattleDome_Text_TrainerWonUsingMove::
    .string "{STR_VAR_1}使用{STR_VAR_2}获胜！$"

BattleDome_Text_TrainerBecameChamp::
    .string "{STR_VAR_1}成为冠军！$"

BattleDome_Text_TrainerWonByDefault::
    .string "{STR_VAR_1}自动获胜！$"

BattleDome_Text_TrainerWonOutrightByDefault::
    .string "{STR_VAR_1}全部自动获胜！$"

BattleDome_Text_TrainerWonNoMoves::
    .string "{STR_VAR_1}未使用技能获胜！$"

BattleDome_Text_TrainerWonOutrightNoMoves::
    .string "{STR_VAR_1}全部未使用技能获胜！$"

BattleDome_Text_Round1Match1::
    .string "第1轮，第1局$"

BattleDome_Text_Round1Match2::
    .string "第2轮，第1局$"

BattleDome_Text_Round1Match3::
    .string "第3轮，第1局$"

BattleDome_Text_Round1Match4::
    .string "第4轮，第1局$"

BattleDome_Text_Round1Match5::
    .string "第5轮，第1局$"

BattleDome_Text_Round1Match6::
    .string "第6轮，第1局$"

BattleDome_Text_Round1Match7::
    .string "第7轮，第1局$"

BattleDome_Text_Round1Match8::
    .string "第8轮，第1局$"

BattleDome_Text_Round2Match1::
    .string "第1轮，第2局$"

BattleDome_Text_Round2Match2::
    .string "第2轮，第2局$"

BattleDome_Text_Round2Match3::
    .string "第3轮，第2局$"

BattleDome_Text_Round2Match4::
    .string "第4轮，第2局$"

BattleDome_Text_SemifinalMatch1::
    .string "第1场半决赛$"

BattleDome_Text_SemifinalMatch2::
    .string "第2场半决赛$"

BattleDome_Text_FinalMatch::
    .string "决赛$"
