FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent::
    .string "欢迎来到对战帐篷\n秋叶镇分址！\p由我向你说明三回合定胜负锦标赛的相关内容！$"

FallarborTown_BattleTentLobby_Text_TakeChallenge::
    .string "现在你有挑战三回合定胜负锦标赛\n的觉悟了吗？$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge::
    .string "我们期待你\n前来挑战！$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent::
    .string "在秋叶镇对战帐篷，\n采取三回合定胜负锦标赛。\p所有参赛队伍由\n3只宝可梦组成。\p这3只宝可梦出场时\n必须排成整齐的一队。\p战斗时，宝可梦以\n事先排好的顺序顺次出场。\p宝可梦出场后，必须\n一直战斗到比赛结束。\p如果一场比赛在3回合\n未分出胜负的活，就由裁判来判定。\p如果你想发起挑战，\n请先保存游戏进度。\p如果你不保存的话，就不能\n继续挑战了。\p如果你连续击败\n3名训练师的话，\l你将获得精美的礼物。$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge::
    .string "在挑战对战帐篷之前\n必须保存游戏进度，现在就记录吗？$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode::
    .string "我们提供两个级别的比赛，\n级别50和自由级\l您要参加哪个？$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons::
    .string "很好，请选择\n3只宝可梦。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50::
    .string "噢，天哪！\p你没有3只\n能参赛的宝可梦。\p他们不能\n携带相同的道具。\p蛋{STR_VAR_1}不能参加比赛。\p做好准备\n再来吧。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen::
    .string "噢，天哪！\p你没有3只\n能参赛的宝可梦。\p按照规则，你必须带来\n3只不同的宝可梦。\p他们不能\n携带相同的道具。\p蛋{STR_VAR_1}不能参加比赛。\p做好准备\n再来吧。$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent::
    .string "我现在带你\n进入对战帐篷。$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting::
    .string "噢，天哪！\p你到现在还没保存\n游戏进度，不是吗？\p很不幸，这样会使你\n失去挑战\l资格。\p你可能，不，一定是一个\n冒失的挑战者。$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers::
    .string "太棒了！你连续打败了\n3名训练师！$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame::
    .string "正在保存，请稍候。$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize::
    .string "祝贺你取得了3连胜，\n这是我们送你的奖品。$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize::
    .string "{PLAYER}得到了\n{STR_VAR_1}。$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize::
    .string "哎？\n你的背包已经满了。\p你还是把背包整理\n好后再来领奖吧。$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving::
    .string "非常感谢你的参与！\p正在保存，请稍候。$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2::
    .string "我们期待你的\n下次挑战！$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival::
    .string "我们一直期待\n你的到来。\p在带你进入对战帐篷之前，\n必须保存游戏进度。请稍候。$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent::
    .string "欢迎来到对战帐篷\n绿荫镇分址！\p在这里，将考验训练师\n与宝可梦之间的默契。$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge::
    .string "你要向绿荫镇\n对战帐篷挑战吗？$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent::
    .string "在绿荫镇对战帐篷里，\n有一条至关重要的规则\l是必须服从的。\p训练师只允许放出和收回\n他们的宝可梦。\p训练师不能对他们的宝可梦\n下任何指令。\p而宝可梦会根据自己的本性行动\n并且凭自己的力量战斗。\p你必须十分信任你的宝可梦\n并在一旁守护着它们。\p如果你能获得连续打败3位\n训练师的荣誉的话，\l我们会送给你礼物作为奖励。\p如果你想停止挑战，\n请保存游戏进度。\p如果你在保存之前中断的话，\n你将失去这场比赛的资格。$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified::
    .string "当你有勇气想让自己的\n宝可梦变强时再来吧。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode::
    .string "有两个级别，\n级别50和自由级。\l你要挑战哪个？$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50::
    .string "唉…\p你没有符合挑战要求\n的3只宝可梦。\p要想参加，你必须准备\n3只不同的宝可梦。\p而且它们不能携带\n同样的道具。\p蛋{STR_VAR_1}不能参加比赛。\p请你准备好了之后\n再来挑战。$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen::
    .string "唉…\p你没有符合挑战要求\n的3只宝可梦。\p要想参加，你必须准备\n3只不同的宝可梦。\p而且它们不能携带\n同样的道具。\p蛋{STR_VAR_1}不能参加比赛。\p请你准备好了之后\n再来挑战。$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons::
    .string "好。现在请你选择\n3只宝可梦。$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge::
    .string "在进入对战帐篷之前必须\n保存游戏进度。现在就保存吗？$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe::
    .string "很好。\n那么，请跟我来。$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded::
    .string "我十分欣赏\n你的宝可梦取得的成绩。\p比赛结果正在记录。\n请稍候。$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak::
    .string "能够达成3连胜就证明…\p你与你的宝可梦之间的羁绊\n是真诚的并且坚不可摧。$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded::
    .string "比赛结果正在记录。\n请稍候。$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize::
    .string "作为你取得3连胜的奖励，\n我们送你精美的礼品。$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent::
    .string "欢迎来到对战帐篷\n凯那市分址！\p由我把你带领到选择式对战\n锦标赛。$"

SlateportCity_BattleTentLobby_Text_TakeChallenge::
    .string "你要向交换式\n对战挑战吗？？$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent::
    .string "这里是凯那市对战帐篷，\n在这里我们要用租借的\l宝可梦进行选择式对战。\p首先，你要租用3只特定的\n宝可梦来参加比赛。\p你要带着那些租借的宝可梦，\n进行单人对战。\p如果你获胜了，你可以交换其中1只\n1只租借的宝可梦。\p重复循环战斗和交换--\n如果取得3连胜\l你将获得精美的奖品。\p如果你想停止挑战，\n请保存游戏进度。\p如果你在保存之前中断的话，\n你将失去这场比赛的资格。$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit::
    .string "我们期待你的再次来临。$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode::
    .string "你要挑战哪个等级？\n50级还是100级？$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge::
    .string "在你挑战之前，\n需要进行存档，要存档吗？$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping::
    .string "好的，我会替你保管\n宝可梦。$"

SlateportCity_BattleTentLobby_Text_StepThisWay::
    .string "请跟我来。$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults::
    .string "十分感谢你的配合！\p我要将你的宝可梦还给你\n并且收回我们借给你的宝可梦。\p正在保存你的战斗结果。\n请稍候。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals::
    .string "我要将你的宝可梦还给你\n并且收回我们借给你的宝可梦。$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons::
    .string "祝贺你！\n你获得了3连胜！\p我要将你的宝可梦还给你\n并且收回我们借给你的宝可梦。\p正在保存你的战斗结果。\n请稍候。$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize::
    .string "为了祝贺你取得了3连胜，\n我们送给你精美的礼品。$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom::
    .string "哎？\n你的背包没有空间放奖品。\p请整理好背包之后\n再来找我。$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou::
    .string "我们会等着你！\p在你继续战斗之前，\n你必须保存游戏进度。$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting::
    .string "非常抱歉，但是你上次退出游戏\n之前没有保存游戏进度。\p因此，你不能继续\n上次的进度进行比赛。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons::
    .string "我们将归还你的宝可梦。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize::
    .string "{PLAYER}得到奖品\n{STR_VAR_1}。$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed::
    .string "选择式对战规则已经列出。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading::
    .string "你要读哪条？$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules::
    .string "在选择式对战的比赛中，\n你只可以使用3只宝可梦。\p无论你是租借还是交换，\n你的队伍里不能有\l2只相同的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules::
    .string "你仅可以和刚刚被你\n打败的训练师交换宝可梦。\p你只能交换那些刚刚被你\n打败的训练师使用的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules::
    .string "你每次胜利后，你可以\n和对手的1只宝可梦\l进行交换。\p你不能与其他训练师\n进行宝可梦的交换。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes::
    .string "对于什么时候交换宝可梦\n有2个要点。\p首先，交换时，你不能检查\n你收到的宝可梦\l的状态。\p其次，你队伍中的宝可梦\n是如何排列的，取决于\l你租借时的顺序。\p这个顺序不会因为\n进行交换而改变。$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules::
    .string "在凯那市对战帐篷中\n使用的宝可梦都是租借的。\p所有租借的宝可梦\n等级都保持在30。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2::
    .string "绿荫镇对战帐篷的\n规则已经列出$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading::
    .string "你要读哪条？$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules::
    .string "在绿荫镇对战帐篷，\n宝可梦需要独立\l思考并战斗。\p不像在野外，宝可梦和人类一起生存\n由于自然环境不同\l行为也不同。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules::
    .string "由于它所处自然环境，宝可梦\n可能会不知原因的攻击。\p另外的宝可梦可能会\n保护自己免受伤害。\p有的还喜欢干扰\n和迷惑自己的敌人。\p由于它所处的自然环境，宝可梦\n可能有它所最喜欢的技能\l并且可以熟练使用。\p它也有可能存在不喜欢的技能\n于是不擅长使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules::
    .string "有攻击技能可以\n对敌人造成直接伤害。\p有防守技能\n用来防御敌人的攻击\l或用来恢复HP等等。\p也有一些有点怪异的技能\n可以使得敌人变得无力和带来\l其他问题，例如中毒和麻痹。\p宝可梦可能会考虑在\n这三种技能中选择使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules::
    .string "当没有听从训练师的命令时\n宝可梦可能不会有效的使用特定技能。\p宝可梦不擅长使用\n任何它不喜欢的技能。\p如果宝可梦仅仅知道些\n不符合其性格的技能，\l那么它就不会展示它的潜能。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules::
    .string "根据其性格，\n当陷入麻烦时，宝可梦可能会开始\l使用一些并不符合性格的技能。\p如果宝可梦开始变得行为怪异\n你就有必要仔细查查看了。$"

BattleTentLobby_Text_ExplainLevelRules::
    .string "在对战帐篷里，你对手的\n的等级会与你参赛的\l宝可梦的等级相适应。\p不管怎样，你不会碰到带着\n低于30级宝可梦的训练师。$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed::
    .string "绿荫镇对战帐篷\n的规则已列出。$"
