PetalburgCity_Gym_Text_GiveEnigmaBerry::
    .string "爸爸：嘿，{PLAYER}！\p我刚刚得到了一种稀有树果，\n给你拿着吧。$"

Route104_Text_PlantBerriesInSoilTakeThis::
    .string "你可以随意取走生长在\n松软的土壤里的树果，\p但记住离开之前一定要在同一个地方\n种下一枚树果，这是约定俗成的习惯。\p这个给你吧。$"

Route104_Text_TrainersOftenMakeMonHoldBerries::
    .string "看上去…你一定\n是训练师吧？\p训练师经常会给他们的宝可梦\n带上树果。\p当然，得到树果后是种植\n还是使用都取决于你自己。$"

Route111_Text_WateredPlantsEveryDayTakeBerry::
    .string "我每天都来给它们浇水，\n所以这里开了这么多的花，\l当然，我也收获了非常多的树果。\p给！这个送给你了！$"

Route111_Text_GoingToTryToMakeDifferentColorBerries::
    .string "我要努力种出\n不同颜色的树果。\p你也要努力啊！$"

Route111_Text_WhatColorBerriesToLookForToday::
    .string "今天去找什么颜色的树果呢？$"

Route114_Text_LoveUsingBerryCrushShareBerry::
    .string "我喜欢树果混合，\n所以我收集了各种各样的树果。\p这个给你怎么样？$"

Route114_Text_TryBerryCrushWithFriends::
    .string "我建议你和你的朋友\n一起玩树果混合。$"

Route114_Text_FunToThinkAboutBerries::
    .string "该种什么树果？得到的\n树果是使用呢还是收藏起来？\p考虑这些事情也是乐趣啊。$"

Route120_Text_BerriesExpressionOfLoveIsntIt::
    .string "树果吸收了阳光，渐渐成长，\p而我们要经常给它们浇水，\n帮助它们长大。\p这大概就是爱的表现吧？$"

Route120_Text_YesYouUnderstand::
    .string "啊，没错，没错，\n看来你明白我说的话了。\p这个给你吧。$"

Route120_Text_MakeYourOwnImpressions::
    .string "啊…也对，有自己的想法\n才是最重要的…\p这个给你吧。$"

Route120_Text_BerryIsRareRaiseItWithCare::
    .string "这可是个很少见的树果，\n希望你能用你的爱去照顾它成长。$"

Route120_Text_IllGetMoreBerriesFromBerryMaster::
    .string "我会从树果大师那儿\n得到更多树果。$"

LilycoveCity_Text_BerrySuitsYou::
    .string "要怎么说呢…\p就像我适合穿套装，\n海风适合在海边吹一样，\p你适合拥有树果…\p为什么呢？$"

LilycoveCity_Text_BecauseYoureTrainer::
    .string "要怎么说呢…\p就因为你是训练师！$"

LilycoveCity_Text_PokeblocksSuitPokemon::
    .string "要怎么说呢…\p就像简单对我的胃口一样，\n能量方块也要对宝可梦胃口。$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry::
    .string "你可以叫我树果大师，\p我始终梦想着让鲜花开满\n世界各地，所以我种植树果\l并把它们交托给遇见的每一个人。\p收下这个吧！$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother::
    .string "不用客气，\n这个也给你！$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop::
    .string "记得一定要去卡那兹市附近的花店\n漂亮花瓣看看。\p愿鲜花开满世界！$"

Route123_BerryMastersHouse_Text_DoneForToday::
    .string "今天就这些了，\n以后再来吧。\p愿鲜花开满世界！$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately::
    .string "我家老头子是世界上\n最擅长种树果的人，\p呵呵，这是我最自豪的事情。\p话说回来，孩子，你听说过\n最近一句流行的谚语吗？$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis::
    .string "啊！多棒的谚语！\n真令人感动！\p这个送给你吧。$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis::
    .string "啊！很好的谚语。\n你还不错，\p这个送给你吧。$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife::
    .string "我们的四个孙子\n肯定会比老头子干得更好的，\p我的生活里始终都充满了快乐！$"

Route123_BerryMastersHouse_Text_Ah::
    .string "啊…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop::
    .string "欢迎！\p这里是花店。\n我们的目标是让鲜花开满全世界！$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries::
    .string "{PLAYER}{KUN}，想知道\n关于树果的事情吗？$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries::
    .string "你的名字是？\p{PLAYER}{KUN}。\n好名字。\p{PLAYER}{KUN}，想知道\n关于树果的事情吗？$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation::
    .string "树果只有在松软的土壤中\n才能健康生长，\p如果你摘了树果，一定\n记得在土壤中再种下一颗。\p种下的树果很快会发芽，\n长出枝叶，开出美丽的花，\l最后又结出树果。\p真希望能看到整个世界\n都布满了美丽的花啊。\l这可一直是我的梦想。\p来帮我们吧，{PLAYER}{KUN}，\n种下这些树果，\l让世界上开出更多鲜花吧。$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness::
    .string "鲜花会使人们得到幸福。$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis::
    .string "欢迎！\p你越是细心地照顾花朵，\n花朵就会开放得越艳丽。\p看上去你很喜欢照顾花儿，\n这个送给你吧。$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation::
    .string "树果渐渐长大的时候，\n就用吼吼鲸喷壶给它们浇水吧。\p啊，对了，\p如果一段时间里你没摘下树果，\n它们会掉进土里，\l不过很快它们又会发芽的。\p挺不错的吧？\n就好像它们自己也盼望着成长一样。$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers::
    .string "我正在向姐姐们学习种花，\n总有一天，我也会像她们那样优秀！\p给！这个送你！$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries::
    .string "你可以把树果种到土里让它长大，\n也可以让宝可梦带上它，\p现在还有另一种选择，用一种\n特别的机器混合树果\l为宝可梦制作糖果。\p我也想要些糖果啊。$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese::
    .string "你叫什么名字啊？\p… … … … … … … … …\n嗯，真是个好名字\p我叫奇莉，\p爸爸妈妈希望我健康长大，而且热心助人，\n所以给我起了这个名字。\p这个给你一个吧。$"

SootopolisCity_Text_GiveYouThisBerryToo::
    .string "奇莉也会给你这种树果的！\n我真的很喜欢它！$"

SootopolisCity_Text_WhatKindOfWishInYourName::
    .string "你的名字里\n会包含了什么样的期望呢？$"

SootopolisCity_Text_LikeSeasonBornIn::
    .string "春，夏，秋，冬…\p春天出生的人喜欢春天\n冬天出生的人喜欢冬天吗？$"

SootopolisCity_Text_ThenILoveAutumn::
    .string "那么，奇莉是秋天出生的，\n所以一定喜欢秋天！\p你喜欢什么季节？$"

SootopolisCity_Text_OhDoesntMatter::
    .string "啊…没关系…\n我想知道的事情太多了…$"
