gText_Birch_Welcome::
    .string "你好！让你久等了！\p欢迎来到精灵宝可梦的世界！\p我是小田卷。\p人们都称我为\n宝可梦博士。\p$"

gText_Birch_Pokemon::
    .string "这就是叫做宝可梦的生物。$"

gText_Birch_MainSpeech::
    .string "这个世界广泛生存着精灵宝可梦，\n人们也管它们叫宝可梦。\p人们和宝可梦一起玩耍，\n互相帮助，\l并且成为了好伙伴。\p有时候，我们与它们\n宝可梦一起战斗。\p遗憾的是，我们对它们\n不是很了解。\p事实上，宝可梦身上\n还有很多很多秘密。\p为了揭开宝可梦的秘密，\n我倾注了毕生心血研究它们。\l来实现我一生中最大的愿望。\p$"

gText_Birch_AndYouAre::
    .string "那么请问？$"

gText_Birch_BoyOrGirl::
    .string "你是男孩？\n还是女孩？$"

gText_Birch_WhatsYourName::
    .string "那么。\n告诉我你的名字吧！$"

gText_Birch_SoItsPlayer::
    .string "是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
    .string "啊，没错！\p你就是刚搬到\n未白镇来的{PLAYER}{KUN}啊。\l我知道了！\p$"

gText_Birch_AreYouReady::
    .string "好的，准备好了吗？\p振奋人心的冒险\n即将展开。\p鼓起勇气，迈向宝可梦的世界吧！\n那里孕育着梦想，\l充满着刺激，还会遇到新的朋友！\p当然，我对你充满了期待。\n到我的宝可梦研究所来见我吧。\p$"
