gText_Birch_Welcome::
    .string "!\p$"

gText_Birch_Birthday::
    .string "今天是张帆的生日，\n也许就是你的生日\p先祝你15岁生日快乐！\n这是我为你特别准备的礼物，\p也许它很粗糙，\n甚至还有许多BUG。\l但是，我并没有多少新东西带给你，\p接下来就是宝可梦的正常流程了，\p祝你游戏愉快！\p$"

gText_Birch_Pokemon::
    .string "这。\p$"

gText_Birch_MainSpeech::
    .string "遗。\p$"

gText_Birch_AndYouAre::
    .string "问？\p$"

gText_Birch_BoyOrGirl::
    .string "男女？$"

gText_Birch_WhatsYourName::
    .string "吧！$"

gText_Birch_SoItsPlayer::
    .string "还是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
    .string "啊！\p{PLAYER}{KUN}啊。\l知！\p$"

gText_Birch_AreYouReady::
    .string "吗？\p吧！\n友！\p吧。\p$"
