gText_Birch_Welcome::
    .string "!\p$"

gText_Birch_Birthday::
    .string "今天是张帆的生日，\n也许就是你的生日\p先祝你15岁生日快乐！\n这是我为你特别准备的礼物，\p也许它很粗糙，\n甚至还有许多BUG。\l但是，我并没有多少新东西带给你，\p接下来就是宝可梦的正常流程了，\p祝你游戏愉快！\p$"

gText_Birch_Pokemon::
    .string "这。\p$"

gText_Birch_MainSpeech::
    .string "遗。\p$"

gText_Birch_AndYouAre::
    .string "问？\p$"

gText_Birch_BoyOrGirl::
    .string "男女？\p$"

gText_Birch_WhatsYourName::
    .string "吧！\p$"

gText_Birch_SoItsPlayer::
    .string "还是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
    .string "啊！\p{PLAYER}{KUN}啊。\l知！\p$"

gText_Birch_AreYouReady::
    .string "好的，准备好了吗？\p振奋人心的冒险\n即将展开。\p鼓起勇气，迈向宝可梦的世界吧！\n那里孕育着梦想，\l充满着刺激，还会遇到新的朋友！\p当然，我对你充满了期待。\n到我的宝可梦研究所来见我吧。\p$"
