BerryBlender_Text_BlendWithTheBlendMaster::
    .string "混合大师：确实是我！\n混合大师！\p和我一起混合，你就能看到我\n娴熟的混合技术！$"

BerryBlender_Text_SeeMyMasteryInAction::
    .string "混合大师：哦！这么说来，\n你是想看看我战斗的英姿吧？$"

BerryBlender_Text_TooBusyNowIsee::
    .string "啊！\p我看你好像挺忙的！\p别担心！\n我天天都在这儿！\l我看这样吧，等你旅行结束了再来找我吧！$"

BerryBlender_Text_BlendMasterNoBerries::
    .string "啊！\p你没带来不同寻常的树果！\p我每天都在这儿的！\n再拿一些珍稀的树果回来，赶快！$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks::
    .string "当然了！\n当然了！\p对了…\n你知道如何用树果\l做出能量方块吗？$"

BerryBlender_Text_BlendMasterExplainBerryBlending::
    .string "嗯！\p不知道没关系，其实非常简单！\p当混合机的指针正对着\n你的时候马上按A键。\p这事儿难不倒你吧。\p你看了我的示范之后，\n就会明白了。$"

BerryBlender_Text_BlendMasterLetsBerryBlender::
    .string "太好了！\p那就快开始吧！\p让我们与所有的混合大师一起，\n混合我们的树果吧！$"

BerryBlender_Text_BlendMasterNoPokeblockCase::
    .string "噢！\p貌似你没有得到\n能量方块盒啊！\p快去把能量方块盒带来！\n我在这儿等你！$"

BerryBlender_Text_BlendMasterPokeblockCaseFull::
    .string "啊！\p看来你的能量方块盒满了！\p我在这儿等着你！\n用掉一些能量块就马上回来！$"

BerryBlender_Text_WhoaAwesome::
    .string "唔啊！\n真可怕！$"

BerryBlender_Text_WickedlyFast::
    .string "坏透了！$"

BerryBlender_Text_WhatAnExpert::
    .string "多么老练啊！$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster::
    .string "能和大师一起混合的话，\n我们就能做出极品的能量方块了！$"

BerryBlender_Text_QualitiesOfBlendMaster::
    .string "看到轨道上的指针像\n机器般强烈震动时…\p就以固定的频率\n一下一下连点A键…\p掌握这种能力\n正是混合大师的终极要义。$"

BerryBlender_Text_MasterWorksOnSkillsInMountains::
    .string "可以想象混合大师在深山中\n进行严格修行。\p有时他一整天\n都在水静市混合树果。$"
