CableClub_Text_WelcomeWhichCableClubService::
    .string "欢迎来到宝可梦有线\n俱乐部，\p需要为您提供\n什么服务吗？$"

CableClub_Text_WhichService::
    .string "需要为您提供\n什么服务吗？$"

CableClub_Text_TradeUsingLinkCable::
    .string "通过GBA通信线\n与其他玩家交换宝可梦。$"

CableClub_Text_BattleUsingLinkCable::
    .string "通过GBA通信线\n与其他训练师战斗。$"

CableClub_Text_RecordCornerUsingLinkCable::
    .string "通过GBA通信线\n与其他人一起使用联机中心。$"

@ Unused
CableClub_Text_CloseThisMenu::
    .string "关闭菜单。$"

CableClub_Text_NeedTwoMonsForDoubleBattle::
    .string "要进行双打对战\n至少要带两只宝可梦。$"

CableClub_Text_NeedTwoMonsToTrade::
    .string "要进行交换\n至少要带有两只宝可梦。$"

CableClub_Text_CantTradeEnigmaBerry::
    .string "带有{STR_VAR_1}树果的\n宝可梦无法进行交换。$"

gText_PleaseWaitForLink::
    .string "请稍候\n… … B键：取消$"

gText_ConfirmLinkWhenPlayersReady::
    .string "等待玩家准备…\nA键：确认\lB键：取消$"

gText_ConfirmStartLinkWithXPlayers::
    .string "与玩家{STR_VAR_1}开始连接。\nA键：确认\lB键：取消$"

gText_AwaitingLinkup::
    .string "等待连接…\n… … B键：取消$"

@ Unused
CableClub_Text_OkayToSaveProgress::
    .string "你的进度必须在\n连接前进行保存。可以吗？$"

CableClub_Text_PleaseEnter::
    .string "请进。$"

CableClub_Text_DirectYouToYourRoom::
    .string "请让我带您去您的房间。$"

Text_SomeoneIsNotReadyToLink::
    .string "对方未准备好连接。\p请待所有人准备好之后\n再回来。$"

Text_LinkErrorPleaseReset::
    .string "对不起，连接发生了错误…\n请重启之后再试。$"

Text_PlayersMadeDifferentSelections::
    .string "连接的伙伴似乎\n做出了别的选择。$"

CableClub_Text_PleaseVisitAgain::
    .string "欢迎再次光临。$"

CableClub_Text_IncorrectNumberOfParticipants::
    .string "参与者数量\n发生错误。$"

CableClub_Text_CantSingleBattleWithXPlayers::
    .string "玩家{STR_VAR_1}无法进行\n单人对战模式。$"

CableClub_Text_CantDoubleBattleWithXPlayers::
    .string "玩家{STR_VAR_1}无法进行\n双打对战模式。$"

CableClub_Text_NeedFourPlayers::
    .string "进行此种对战模式\n需要4位玩家。$"

CableClub_Text_PleaseConfirmNumberAndRestart::
    .string "请确认玩家数量，\n重新开始。$"

Text_TerminateLinkConfirmation::
    .string "如果您离开房间，连接\n将会终止。可以吗？$"

Text_TerminateLinkPleaseWait::
    .string "终止连接…\n您会由服务员带出\l房间，请稍候。$"

CableClub_Text_TooBusyToNotice::
    .string "这个训练师太忙，\n没空注意…$"

CableClub_Text_GotToLookAtTrainerCard::
    .string "成功！看一下{STR_VAR_1}的\n训练师卡片！$"

CableClub_Text_GotToLookAtColoredTrainerCard::
    .string "成功！看一下{STR_VAR_1}的\n训练师卡片！\p是一张{STR_VAR_2}卡！$"

BattleColosseum_2P_Text_TakePlaceStartBattle::
    .string "请就位，\n准备开始战斗。$"

TradeCenter_Text_TakeSeatStartTrade::
    .string "请就位，\n准备开始交换。$"

RecordCorner_Text_ThanksForComing::
    .string "谢谢惠顾。$"

CableClub_Text_TrainerCardDataOverwritten::
    .string "训练师卡片数据\n将被覆盖。$"

CableClub_Text_HopeToSeeYouAgain::
    .string "下回再见！$"

CableClub_Text_NotSetUpForFarAwayRegion::
    .string "非常抱歉，\p我们现在无法与\n远在其它地区的训练师\l进行连接…$"

CableClub_Text_OtherTrainerNotReady::
    .string "其他训练师还未准备好。$"

CableClub_Text_YouHaveAMonThatCantBeTaken::
    .string "你带有不能携带的\n宝可梦。$"

RecordCorner_Text_TakeSeatAndWait::
    .string "请坐在您的位置上等候。$"

RecordCorner_Text_PlayerSentOverOneX::
    .string "{STR_VAR_1}送出一个\n{STR_VAR_2}。$"

CableClub_Text_CantMixWithJapaneseGame::
    .string "对不起，连接错误。\p不能与日版红蓝宝石\n进行混合存档。\p同样，你也不能同时与\n日版绿宝石和海外版\l红蓝宝石混合存档。$"

CableClub_Text_AdapterNotConnected::
    .string "无线接收器没有\n正确连接。$"

CableClub_Text_ParticipantsStepUpToCounter::
    .string "参加者请到\n接待处。$"

@ Unused
CableClub_Text_Hello::
    .string "你好！$"

@ Unused
CableClub_Text_PleaseWait::
    .string "请稍候。$"

CableClub_Text_YouMayTradeHere::
    .string "在这里你可以与其他\n训练师交换宝可梦。$"

CableClub_Text_YouMayBattleHere::
    .string "在这里你可以\n与朋友对战。$"

CableClub_Text_CanMakeBerryPowder::
    .string "可以与2到5个训练师\n一起制作树果粉末。$"

CableClub_Text_CanMixRecords::
    .string "这里可以将2到4个\n玩家的存档混合在一起。$"

@ Unused
CableClub_Text_GuideToVariousServices::
    .string "无线俱乐部的导游\n提供各种服务。$"

CableClub_Text_CancelSelectedItem::
    .string "取消选定的菜单项目。$"

@ Unused
CableClub_Text_WhichBattleMode::
    .string "你喜欢哪种对战模式？$"

@ Unused
CableClub_Text_ReturnsToPreviousStep::
    .string "回到上一步。$"

CableClub_Text_NeedBerryForBerryCrush::
    .string "要使用树果混合机，\n你至少要有1个树果。$"

CableClub_Text_NeedTwoMonsForUnionRoom::
    .string "要进入联合房间，\n你至少要带有2只宝可梦。$"

CableClub_Text_NoEnigmaBerryInUnionRoom::
    .string "带有{STR_VAR_1}树果的宝可梦\n不能进入联合房间。$"

CableClub_Text_UnionRoomAdapterNotConnected::
    .string "这里是宝可梦无线俱乐部\n联合房间，\p很抱歉，您的无线接收器没有正确连接，\p请下次再来。$"

@ Unused
CableClub_Text_OhExcuseMe::
    .string "哦…\n打扰了！$"

CableClub_Text_PlayerIsWaiting::
    .string "看来{STR_VAR_1}已经\n准备好了。\l加油！$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame::
    .string "需要的话，我可以\n向您解说对战规则。\p需要解说哪一项？$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo::
    .string "“宝可梦跳绳”\p用A键让你的宝可梦\n跳过藤鞭。\p只有60厘米以下的小型\n宝可梦可以参加，\p而且，只会游泳、挖掘、飞行的\n宝可梦并不擅长跳跃，\p因此，这些宝可梦\n也不能参加。\p如果大家都及时跳起，\n会有好事情发生。$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo::
    .string "“嘟嘟利摘树果”\p指挥嘟嘟利的3个头\n接住落下的树果。\p按+方向键的\n左、右、上键移动这些头。\p要玩此游戏，你必须\n拥有嘟嘟利。$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay::
    .string "如果你想玩游戏，\n就告诉我后面的老人。$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait::
    .string "嗨，欢迎！\n你是想用无线\l交流玩游戏吗？\p请稍等一下好吗？$"

MossdeepCity_GameCorner_1F_Text_ComeAgain::
    .string "好，再来啊！$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected::
    .string "无线接收器没有连接。\n连接上之后再回来吧！$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame::
    .string "好，你想玩\n哪个游戏？$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon::
    .string "要让哪只宝可梦\n参加？$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo::
    .string "好的，一切就绪，\n一定要赢！$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain::
    .string "现在离开吗？\n要再来哟！$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon::
    .string "看来你并没有可以\n参加的宝可梦…\p需要我为你解释一下\n什么样的宝可梦可以参加吗？$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed::
    .string "参加“宝可梦跳绳”的宝可梦\n必须在60厘米以下，\p并且，不会跳跃的\n宝可梦也不能参加，\p比如说，只会游泳、挖掘、\n飞行的宝可梦。\p知道这些就够了。$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed::
    .string "只有嘟嘟利可以参加\n嘟嘟利摘树果。$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease::
    .string "要再次从头\n挑战吗？$"

CableClub_Text_WelcomeWhichDirectCornerRoom::
    .string "欢迎来到宝可梦无线\n俱乐部交流中心，\p在这里你可以与\n你的朋友直接进行交流。\p你要进入\n哪个房间？$"

CableClub_Text_TradePokemon::
    .string "你想要交换宝可梦吗？$"

CableClub_Text_PlayWhichBattleMode::
    .string "你想参加哪个比赛\n项目？$"

CableClub_Text_AccessRecordCorner::
    .string "你想参加联机中心？$"

CableClub_Text_UseBerryCrush::
    .string "你想使用\n树果研磨系统吗？$"

CableClub_Text_ExplainBattleModes::
    .string "一共有3种不同的对战模式。\p单打模式中每位选手\n至少带上一只宝可梦。\p战斗开始时每位选手同时放出\n一只宝可梦。\p双打模式中每位选手\n至少带上一只宝可梦。\p战斗开始时每位选手同时放出\n一只宝可梦。\p混战模式中每位选手\n至少带上一只宝可梦。\p战斗开始时每位选手\n同时放出一只宝可梦。$"

CableClub_Text_ChooseGroupLeaderOfTwo::
    .string "请决定你们中的谁会成为\n队长。\p其他的人就得选择\n“加入小组。”$"

CableClub_Text_ChooseGroupLeaderOfFour::
    .string "请决定你们中的谁会成为\n队长。\p其他的人就得选择\n“加入小组。”$"

CableClub_Text_ChooseGroupLeader::
    .string "请决定你们中的谁会成为\n队长。\p其他的人就得选择\n“加入小组。”$"

CableClub_Text_WelcomeUnionRoomEnter::
    .string "欢迎来到宝可梦无线通信\n俱乐部联合房间。\p在这里你可以和一些\n甚至你不认识的人\l进行交流。\p你想进来吗？$"

CableClub_Text_UnionRoomInfo::
    .string "在这里的人都是在你的周围\n而且都进入了联合房间的\l选手。\p在这里你可以和他做一些\n交换或聊天之类的事。\p你可以拿出2只30级的\n宝可梦进行一对一的战斗。\p你也可以和2到5个人\n在这里进行聊天。\p或者你可以进行宝可梦\n之前的交换。\p你想进来吗？$"

CableClub_Text_EnjoyUnionRoom::
    .string "希望你能在联合房间过的愉快。$"

CableClub_Text_FirstTimeRightThisWay::
    .string "你好！\n我是奥纳。\p你应该是第一次到\n这里来吧。\p由我来向你介绍写无线通信\n系统吧。\p首先需要向你介绍下\n这一层的宝可梦服务台。\p请走这边。$"

CableClub_Text_ExplainWirelessClubFirstTime::
    .string "在这里有\n两个房间。\p首先介绍下左边的\n那是联合房间。\p你能够和那些在你周围的\n并且也进入这个房间的\l人进行联机。\p你可以和他们进行\n聊天，战斗或交换。\p接着右边的就是直接通信\n房间了。\p你可以和他们进行交换或\n战斗。\p如果无线通信器不起作用\n的话，你就得使用\lGBA通信线了。\p那样的话，你必须得去\n直接通信室。\p希望你能满意我\n的服务。$"

CableClub_Text_AskAboutLinking::
    .string "你好，{PLAYER}！\p我是奥纳，\n宝可梦中心2楼的服务员。\p你想了解些关于\n通信的事情吗？$"

CableClub_Text_ExplainWirelessClub::
    .string "让我给你介绍下\n无线通信俱乐部吧。\p这一层有两个房间\p首先介绍下左边的\n那是联合房间。\p你能够和那些在你周围的\n并且也进入这个房间的\l人进行联机。\p你可以和他们进行\n聊天，战斗或交换。\p接着右边的就是直接通信\n房间了。\p你可以和他们进行交换或\n战斗。\p如果无线通信器不起作用\n的话，你就得使用\lGBA通信线了。\p那样的话，你必须得去\n直接通信室。\p希望你能满意\n我的服务。$"

CableClub_Text_HopeYouEnjoyWirelessSystem::
    .string "希望你能满意\n我的服务。$"
