@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
    .string "失误回合$"

gText_LinkStandby4::
    .string "准备连接！$"

gText_WinnerIsPlayersMonCongrats::
    .string "胜者是{STR_VAR_1}的{STR_VAR_2}！\n恭喜！$"

gText_WinnerIsPlayersMon::
    .string "胜者是{STR_VAR_1}的{STR_VAR_2}！{0xFC 9}$"

gText_PrimaryJudgingNumX::
    .string "初评：No.{STR_VAR_1}{0xFC 9}$"

gText_SecondaryJudgingNumX::
    .string "次评：No.{STR_VAR_1}{0xFC 9}$"

gText_SetEventNumX::
    .string "自定赛：No.{STR_VAR_1}{0xFC 9}$"

gText_MoveUsedMostOften::
    .string "经常使用的技能：\n{STR_VAR_1}{0xFC 9}$"

gText_MostImpressiveMon::
    .string "给人印象最深的宝可梦：\n{STR_VAR_1}的{STR_VAR_2}{0xFC 9}$"

gText_SetEventNumX2::
    .string "自定赛：No.{STR_VAR_1}{0xFC 9}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
    .string "不会制作联线电视节目了\n因为训练师走了。{0xFC 9}$"
