@ Contest move effect descriptions

gText_HighlyAppealingMove::
    .string "质量好高的一个动作。$"

gText_UserMoreEasilyStartled::
    .string "这个动作之后宝可梦\n更容易受到别人的惊吓。$"

gText_GreatAppealButNoMoreToEnd::
    .string "能得到一个好成绩，但是\n只能使用一次。$"

gText_UsedRepeatedlyWithoutBoringJudge::
    .string "能够重复使用\n但是却不会让裁判厌烦。$"

gText_AvoidStartledByOthersOnce::
    .string "能避免受到别人的\n的一次惊吓。$"

gText_AvoidStartledByOthers::
    .string "能避免受到别人的\n的惊吓。$"

gText_AvoidStartledByOthersLittle::
    .string "能避免受到别人的\n的惊吓。$"

gText_UserLessLikelyStartled::
    .string "这个动作之后宝可梦\n不容易被别的吓到。$"

gText_SlightlyStartleFrontMon::
    .string "让前面的宝可梦\n轻微的惊讶了下。$"

gText_SlightlyStartleAppealed::
    .string "让那些做了动作的\n宝可梦受到了惊吓。$"

gText_StartleAppealedBeforeUser::
    .string "让那些在选手前面的\n宝可梦受到了惊吓。$"

gText_StartleAllAppealed::
    .string "让那些做了动作的\n宝可梦受到了惊吓。$"

gText_BadlyStartleFrontMon::
    .string "把前面的宝可梦\n吓坏了。$"

gText_BadlyStartleAppealed::
    .string "把做了动作的宝可梦\n吓坏了。$"

gText_StartleAppealedBeforeUser2::
    .string "把在自己前面的宝可梦\n吓坏了。$"

gText_StartleAllAppealed2::
    .string "把所以做了动作的宝可梦\n吓坏了。$"

gText_ShiftJudgesAttentionFromOthers::
    .string "将裁判的注意\n转移到了别人身上。$"

gText_StartleMonHasJudgesAttention::
    .string "把那些获得裁判注意的\n宝可梦吓到了。$"

gText_JamOthersMissesTurn::
    .string "让其他的宝可梦惊愕了\n但却失去了一次表演的机会。$"

gText_StartleMonsMadeSameTypeAppeal::
    .string "让那些做了同样动作的\n宝可梦惊愕了。$"

gText_BadlyStartleCoolAppeals::
    .string "让那些做了帅气动作的\n宝可梦惊愕了。$"

gText_BadlyStartleBeautyAppeals::
    .string "让那些做了美丽动作的\n宝可梦惊愕了。$"

gText_BadlyStartleCuteAppeals::
    .string "让那些做了可爱动作的\n宝可梦惊愕了。$"

gText_BadlyStartleSmartAppeals::
    .string "让那些做了聪明动作的\n宝可梦惊愕了。$"

gText_BadlyStartleToughAppeals::
    .string "让那些做了强壮动作的\n宝可梦惊愕了。$"

gText_MakeMonAfterUserNervous::
    .string "让在选手后面一位的宝可梦\n紧张了。$"

gText_MakeAllMonsAfterUserNervous::
    .string "让在选手后面所有的宝可梦\n紧张了。$"

gText_WorsenConditionOfThoseMadeAppeals::
    .string "以后做动作时动作的\n质量会更低。$"

gText_BadlyStartleMonsGoodCondition::
    .string "让状态好的\n宝可梦惊愕了。$"

gText_AppealGreatIfPerformedFirst::
    .string "如果动作先表演的话\n将会发挥得更好。$"

gText_AppealGreatIfPerformedLast::
    .string "如果动作最后表演的话\n将会发挥得更好。$"

gText_AppealAsGoodAsThoseBeforeIt::
    .string "让动作做得和之前的\n一样好吧。$"

gText_AppealAsGoodAsOneBeforeIt::
    .string "让动作做得和上位选手的\n一样好吧。$"

gText_AppealBetterLaterItsPerformed::
    .string "再做一次的时候动作的\n质量会更高。$"

gText_AppealVariesDependingOnTiming::
    .string "动作质量的变化\n完全取决于他的表演时间。$"

gText_WorksWellIfSameTypeAsBefore::
    .string "如果和前面选手做得一样的\n话会很好。$"

gText_WorksWellIfDifferentTypeAsBefore::
    .string "如果和前面选手做不同的\n话会很好。$"

gText_AffectedByAppealInFront::
    .string "被之前动作的质量\n所影响。$"

gText_UpsConditionHelpsPreventNervousness::
    .string "提高训练师的水平。\n能够防止紧张。$"

gText_AppealWorksWellIfConditionGood::
    .string "训练师的状态越好，\n动作的质量也就会越高。$"

gText_NextAppealMadeEarlier::
    .string "下一次的动作\n会先做。$"

gText_NextAppealMadeLater::
    .string "下一次的动作\n做的会更晚一些。$"

gText_TurnOrderMoreEasilyScrambled::
    .string "让下回合的次序\n跟容易混乱。$"

gText_ScrambleOrderOfNextAppeals::
    .string "使下一回合的次序\n混乱。$"

gText_AppealExcitesAudienceInAnyContest::
    .string "一个可以在任何比赛中\n都能获得观众肯定的动作。$"

gText_BadlyStartlesMonsGoodAppeals::
    .string "让那些做得好的\n严重的惊愕了。$"

gText_AppealBestMoreCrowdExcited::
    .string "观众越兴奋动作的\n质量就会越高。$"

gText_TemporarilyStopCrowdExcited::
    .string "暂时让观众停止\n兴奋。$"

@ Unused move names

gText_RainDance::
    .string "乞雨$"

gText_Rage::
    .string "愤怒$"

gText_FocusEnergy::
    .string "集气$"

gText_Hypnosis::
    .string "催眠术$"

gText_Softboiled::
    .string "生蛋$"

gText_HornAttack::
    .string "角撞$"

gText_SwordsDance::
    .string "剑舞$"

gText_Conversion::
    .string "变性$"

gText_SunnyDay::
    .string "大晴天$"

gText_Rest2::
    .string "睡觉$"

gText_Vicegrip::
    .string "剪断$"

gText_DefenseCurl::
    .string "防卫卷$"

gText_LockOn::
    .string "锁定$"

@ Contest type names

gContestMoveTypeCoolText::
    .string "帅气$"

gContestMoveTypeBeautyText::
    .string "美丽$"

gContestMoveTypeCuteText::
    .string "可爱$"

gContestMoveTypeSmartText::
    .string "聪明$"

gContestMoveTypeToughText::
    .string "强壮$"

gText_AppealNumWhichMoveWillBePlayed::
    .string "{STR_VAR_1}号表演！\n你会选择什么动作？$"

gText_AppealNumButItCantParticipate::
    .string "{STR_VAR_1}号表演！\n但是他无法参与！$"

gText_MonAppealedWithMove::
    .string "{STR_VAR_1}使用\n{STR_VAR_2}表演！$"

gText_MonWasWatchingOthers::
    .string "{STR_VAR_1}正在看\n着别人。{0xFC 8}盔{0xFC 8}盔$"

gText_AllOutOfAppealTime::
    .string "表演时间\n已经结束了！{0xFC 8}盔{0xFC 8}盔$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
    .string "但是动作还是\n很混乱啊。$"

gText_FollowedAnotherMonsLead::
    .string "它听着其它宝可梦\n的指挥。$"

gText_ButItMessedUp::
    .string "但是它陷入困境了。$"

gText_WentBetterThanUsual::
    .string "它做得比平常\n还要好$"

gText_JudgeLookedAwayForSomeReason::
    .string "裁判因为什么原因\n往四周看了。$"

gText_WorkedHardToBuildOnPastMistakes::
    .string "它努力纠正\n之前犯的错误。$"

gText_CantMakeAnyMoreMoves::
    .string "它不能再做任何\n动作了。$"

gText_WorkedFrighteninglyWell::
    .string "它做的非常好，\n让人吃惊。$"

gText_WorkedHardAsStandoutMon::
    .string "它做的和那些出色的\n宝可梦一样的努力。$"

gText_JudgedLookedOnExpectantly::
    .string "裁判看起来\n非常期待啊。$"

gText_WorkedRatherWell::
    .string "它做得相当的好 $"

gText_WorkedLittleBetterThanUsual::
    .string "发挥的比平常要好。$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
    .string "{STR_VAR_1}似乎\n表现的不突出{0xFC 9}$"

gText_MonDidntStandOutVeryMuch::
    .string "{STR_VAR_1}表现的\n不是太好…{0xFC 9}$"

gText_MonCaughtALittleAttention::
    .string "{STR_VAR_1}得到了\n一点注意。{0xFC 9}$"

gText_MonAttractedALotOfAttention::
    .string "{STR_VAR_1}吸引了\n很多眼球。{0xFC 9}$"

gText_MonCommandedTotalAttention::
    .string "{STR_VAR_1}引起了\n所有人的注意。{0xFC 9}$"

gText_MonHasntMadeItsAppeal::
    .string "{STR_VAR_1}还没有\n做动作。{0xFC 9}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
    .string "期望下次{STR_VAR_1}\n的吸引力会有提高。$"

gText_EmptyContestString::
    .string "$"

gText_JudgesViewsOnMonHeldFirm::
    .string "裁判很欣赏\n{STR_VAR_1}。$"

gText_MonsXChangedPerceptions::
    .string "{STR_VAR_1}的{STR_VAR_3}\n改变了结果。$"

gText_MonsAppealEffectWoreOff::
    .string "{STR_VAR_1}的\n动作失效了。$"

gText_SpecialAppealsEffectWoreOff::
    .string "动作特殊效果\n逐渐消失了。$"

gText_EveryonesAppealsMadeToLookSame::
    .string "每个宝可梦的动作看起来\n都是一样的。$"

gText_CheapenedMonsAppeal::
    .string "使得{STR_VAR_2}\n的动作质量下降了。$"

gText_CheapenedAppealOfThoseAhead::
    .string "所有在前面做动作的 \n效果都下降了。$"

gText_StoleAttentionAwayFromMon::
    .string "它吸引了\n{STR_VAR_2}的注意力。$"

gText_CheapenedMonsAppeal2::
    .string "使得{STR_VAR_2}\n的动作质量下降了。$"

gText_SeverelyCheapenedOtherAppeals::
    .string "它大大降低了\n其他选手的吸引力。$"

gText_AnticipationSwelledForMonsAppealNext::
    .string "{STR_VAR_1}下回合的\n吸引力会飞涨。$"

gText_CheapenedAppealOfThoseAhead2::
    .string "所有在前面做动作的\n质量都下降。$"

gText_CheapenedJudgesFavoriteAppeal::
    .string "所有裁判最喜欢的\n动作质量都下降了。$"

gText_AppealsOfOthersCheapenedByHalf::
    .string "其它宝可梦的吸引力\n下降了一半。$"

gText_StoodOutToMakeUpForBeingJammed::
    .string "它出色的表演\n防止了被干扰。$"

gText_CantParticipateInAppealsAnyMore::
    .string "它不能再使用\n这个动作了。$"

gText_TouchedJudgeForFantasticAppeal::
    .string "这就是裁判\n最喜欢的动作。$"

gText_AnticipationRoseForUpcomingAppeals::
    .string "期待接下来\n将出现的动作。$"

gText_StoodOutAsMuchAsSpecialAppeals::
    .string "做的和特殊动作\n一样的优秀。$"

gText_StoodOutAsMuchAsMon::
    .string "它和{STR_VAR_1}一样\n的表现出色。$"

gText_JammedAppealsMadeEvenLessNoticeable::
    .string "被干扰动作后\n关注度下降了。$"

gText_EveryonesAppealsMadeSame::
    .string "所有选手的吸引力\n完全相同。$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
    .string "其它宝可梦变得\n更警惕了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonCantMakeAnAppealAfterThis::
    .string "{STR_VAR_1}在这之后\n不能再做动作了。{0xFC 8}盔{0xFC 8}盔$"

gText_SettledDownJustLittleBit::
    .string "它只镇静了\n一小会儿。{0xFC 8}盔{0xFC 8}盔$"

gText_BecameObliviousToOtherMons::
    .string "它开始忽视\n其它宝可梦了。{0xFC 8}盔{0xFC 8}盔$"

gText_BecameLessAwareOfOtherMons::
    .string "其它宝可梦的\n关注度降低了。{0xFC 8}盔{0xFC 8}盔$"

gText_StoppedCaringAboutOtherMons::
    .string "它不再关注\n其他的宝可梦了。{0xFC 8}盔{0xFC 8}盔$"

gText_TriedToStartleOtherMons::
    .string "它试着去惊吓\n其它宝可梦。{0xFC 8}盔{0xFC 8}盔$"

gText_TriedToDazzleOthers::
    .string "它尝试让其它\n宝可梦眼花。{0xFC 8}盔{0xFC 8}盔$"

gText_JudgeLookedAwayFromMon::
    .string "裁判不再看\n {STR_VAR_1}了。{0xFC 8}盔{0xFC 8}盔$"

gText_TriedToUnnerveNextMon::
    .string "它想让下一位\n宝可梦泄气。{0xFC 8}盔{0xFC 8}盔$"

gText_MonBecameNervous::
    .string "{STR_VAR_1}变得\n紧张了。{0xFC 8}盔{0xFC 8}盔$"

gText_AppealTriedToUnnerveWaitingMons::
    .string "它让在等待的\n宝可梦胆怯了。{0xFC 8}盔{0xFC 8}盔$"

gText_TauntedMonsDoingWell::
    .string "它让其它宝可梦\n受到了惊吓。{0xFC 8}盔{0xFC 8}盔$"

gText_MonRegainedItsForm::
    .string "{STR_VAR_1}恢复了。\n{0xFC 8}盔{0xFC 8}盔$"

gText_TriedToJamMonDoingWell::
    .string "它试图干扰宝可梦\n把动作做好。{0xFC 8}盔{0xFC 8}盔$"

gText_StandoutMonHustledEvenMore::
    .string "表现出色的{STR_VAR_1}\n加快步伐甩开对手。{0xFC 8}盔{0xFC 8}盔$"

gText_LargelyUnnoticedMonWorkedHard::
    .string "不太受人注意的\n{STR_VAR_1}做得更加的努力。{0xFC 8}盔{0xFC 8}盔$"

gText_WorkedAsMuchAsMonBefore::
    .string "它和之前的那些宝可梦\n一样的的努力。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealDidNotGoWell::
    .string "{STR_VAR_1}的动作完成\n的不是很理想。{0xFC 8}盔{0xFC 8}盔$"

gText_WorkedAsMuchAsPrecedingMon::
    .string "和前面宝可梦的动作\n重复了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealDidNotGoWell2::
    .string "{STR_VAR_1}的动作完成\n的不是很理想。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealDidNotGoWell3::
    .string "{STR_VAR_1}的动作完展\n的不是很理想。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentSlightlyWell::
    .string "{STR_VAR_1}的动作\n完成的还可以。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentPrettyWell::
    .string "{STR_VAR_1}的动作\n完成的非常好。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentExcellently::
    .string "{STR_VAR_1}的动作\n完成的太棒了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWasDud::
    .string "{STR_VAR_1}的动作\n没有作用。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealDidNotWorkVeryWell::
    .string "{STR_VAR_1}的动作\n不是很有用。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentSlightlyWell2::
    .string "{STR_VAR_1}的动作\n完成的还可以。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentPrettyWell2::
    .string "{STR_VAR_1}的动作\n完成的非常好。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentVeryWell::
    .string "{STR_VAR_1}的动作\n完成的非常棒。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsAppealWentExcellently2::
    .string "{STR_VAR_1}的动作\n完成的太出色了。{0xFC 8}盔{0xFC 8}盔$"

gText_SameTypeAsOneBeforeGood::
    .string "和前面宝可梦的动作\n完成的一样出色！{0xFC 8}盔{0xFC 8}盔$"

gText_NotSameTypeAsOneBeforeGood::
    .string "它和之前做相同\n动作的一样棒！{0xFC 8}盔{0xFC 8}盔$"

gText_StoodOutMuchMoreThanMonBefore::
    .string "它比前面的宝可梦\n要出色多了。{0xFC 8}盔{0xFC 8}盔$"

gText_DidntDoAsWellAsMonBefore::
    .string "它还没有之前的\n宝可梦表演的精彩。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsConditionRoseAboveUsual::
    .string "{STR_VAR_1}的状态\n渐入佳境。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsHotStatusMadeGreatAppeal::
    .string "{STR_VAR_1}的火热状态\n使得表演更加出色！{0xFC 8}盔{0xFC 8}盔$"

gText_MovedUpInLineForNextAppeal::
    .string "为了接下来的表演，\n它走到了前方。{0xFC 8}盔{0xFC 8}盔$"

gText_MovedBackInLineForNextAppeal::
    .string "它向后退了步\n等待下一轮表演。{0xFC 8}盔{0xFC 8}盔$"

gText_ScrambledUpOrderForNextTurn::
    .string "下一轮的\n次序被打乱了。{0xFC 8}盔{0xFC 8}盔$"

gText_JudgeLookedAtMonExpectantly::
    .string "裁判非常专注地\n看着{STR_VAR_1}的表演。{0xFC 8}盔{0xFC 8}盔$"

gText_AppealComboWentOverWell::
    .string "这一套动作\n受到欢迎了。{0xFC 8}盔{0xFC 8}盔$"

gText_AppealComboWentOverVeryWell::
    .string "这一套动作\n很受欢迎。{0xFC 8}盔{0xFC 8}盔$"

gText_AppealComboWentOverExcellently::
    .string "这一套动作\n非常受欢迎了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonManagedToAvertGaze::
    .string "{STR_VAR_1}设法\n躲开了它的注视。{0xFC 8}盔{0xFC 8}盔$"

gText_MonManagedToAvoidSeeingIt::
    .string "{STR_VAR_1}设法\n避免看到它。{0xFC 8}盔{0xFC 8}盔$"

gText_MonIsntFazedByThatSortOfThing::
    .string "{STR_VAR_1}并没有因为\n那些小插曲受影响。{0xFC 8}盔{0xFC 8}盔$"

gText_MonBecameALittleDistracted::
    .string "{STR_VAR_1}变得有些\n分心了。{0xFC 8}盔{0xFC 8}盔$"

gText_TriedToStartleOtherPokemon::
    .string "它尝试惊吓\n其它宝可梦。{0xFC 8}盔{0xFC 8}盔$"

gText_MonLookedDownOutOfDistraction::
    .string "{STR_VAR_1}低着头\n不知道在想什么。{0xFC 8}盔{0xFC 8}盔$"

gText_MonTurnedBackOutOfDistraction::
    .string "{STR_VAR_1}转过身子\n不知道在想什么。{0xFC 8}盔{0xFC 8}盔$"

gText_MonCouldntHelpUtteringCry::
    .string "{STR_VAR_1}忍不住\n哭了出来。{0xFC 8}盔{0xFC 8}盔$"

gText_MonCouldntHelpLeapingUp::
    .string "{STR_VAR_1}不禁地\n跳了起来。{0xFC 8}盔{0xFC 8}盔$"

gText_MonTrippedOutOfDistraction::
    .string "{STR_VAR_1}因为漫不经心\n而被绊倒了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonWasTooNervousToMove::
    .string "{STR_VAR_1}紧张得\n不得动弹了。{0xFC 8}盔{0xFC 8}盔$"

gText_ButItMessedUp2::
    .string "但是它陷入了困境。{0xFC 8}盔{0xFC 8}盔$"

gText_ButItFailedToMakeTargetNervous::
    .string "它想让对手紧张\n但失败了。{0xFC 8}盔{0xFC 8}盔$"

gText_ButItFailedToMakeAnyoneNervous::
    .string "没有让任何\n一个宝可梦紧张。{0xFC 8}盔{0xFC 8}盔$"

gText_ButItWasIgnored::
    .string "它被无视了…{0xFC 8}盔{0xFC 8}盔$"

gText_CouldntImproveItsCondition::
    .string "它还不能改善\n自己的状态…{0xFC 8}盔{0xFC 8}盔$"

gText_BadConditionResultedInWeakAppeal::
    .string "它糟糕的状态\n使得动作都是有气无力的了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonWasUnaffected::
    .string "{STR_VAR_1}没有\n受到影响。{0xFC 8}盔{0xFC 8}盔$"

gText_RepeatedAppeal::
    .string "{STR_VAR_1}做了重复的动作，\n真让人失望。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsXWentOverGreat::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n做得相当出色。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsXDidntGoOverWell::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n没有受到青睐…{0xFC 8}盔{0xFC 8}盔$"

gText_MonsXGotTheCrowdGoing::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n让围观人群散去了。{0xFC 8}盔{0xFC 8}盔$"

gText_MonCantAppealNextTurn::
    .string "{STR_VAR_1}下一轮\n不能行动了…{0xFC 8}盔{0xFC 8}盔$"

gText_AttractedCrowdsAttention::
    .string "它吸引了\n观众的注意。{0xFC 8}盔{0xFC 8}盔$"

gText_CrowdContinuesToWatchMon::
    .string "人们还在关注\n着{STR_VAR_3}。{0xFC 8}盔{0xFC 8}盔$"

gText_MonsMoveIsIgnored::
    .string "{STR_VAR_1}的\n{STR_VAR_2}被忽视了。{0xFC 8}盔{0xFC 8}盔$"

gText_Contest_Shyness::
    .string "害羞$"

gText_Contest_Anxiety::
    .string "焦虑$"

gText_Contest_Laziness::
    .string "懒惰$"

gText_Contest_Hesitancy::
    .string "踌躇$"

gText_Contest_Fear::
    .string "恐惧$"

gText_Contest_Coolness::
    .string "帅气$"

gText_Contest_Beauty::
    .string "美丽$"

gText_Contest_Cuteness::
    .string "可爱$"

gText_Contest_Smartness::
    .string "聪明$"

gText_Contest_Toughness::
    .string "强壮$"

@ Unused
gText_Tension::
    .string "帅气的动美丽的动作可爱的动作$"

gText_CoolMove::
    .string "美丽的动作可爱的动作$"

gText_BeautyMove::
    .string "可爱的动作$"

gText_CuteMove::
    .string "聪明的动作强壮的动作$"

gText_SmartMove::
    .string "强壮的动作$"

gText_ToughMove::
    .string "联线待机！$"

gText_3QuestionMarks::
    .string "？？？$"
