gContestHallPaintingCaption::
    .string "{STR_VAR_1}\n{STR_VAR_2}的{STR_VAR_3}$"

@ Unused
gContestPaintingContest::
    .string "比赛$"

gContestRankNormal::
    .string "普通组$"

gContestRankSuper::
    .string "超级组$"

gContestRankHyper::
    .string "专家组$"

gContestRankMaster::
    .string "大师组$"

gContestLink::
    .string "联机$"

gContestCoolness::
    .string "帅气$"

gContestBeauty::
    .string "美丽$"

gContestCuteness::
    .string "可爱$"

gContestSmartness::
    .string "聪明$"

gContestToughness::
    .string "强壮$"

gContestPaintingCool1::
    .string "挡不住的帅气--\n无可估量的{STR_VAR_1}$"

gContestPaintingCool2::
    .string "嗨那边的！\n好漂亮的宝可梦啊{STR_VAR_1}$"

gContestPaintingCool3::
    .string "这真是让人惊奇的\n{STR_VAR_1}居然那么神奇$"

gContestPaintingBeauty1::
    .string "{STR_VAR_1}是本世纪\n最后的维纳斯。$"

gContestPaintingBeauty2::
    .string "{STR_VAR_1}耀眼\n而闪亮的微笑$"

gContestPaintingBeauty3::
    .string "宝可梦中心的超级偶像--\n无与伦比的{STR_VAR_1}$"

gContestPaintingCute1::
    .string "可爱的{STR_VAR_1}$"

gContestPaintingCute2::
    .string "美丽的{STR_VAR_1}的\n胜利肖像$"

gContestPaintingCute3::
    .string "让我们看看\n那个漂亮的宝可梦{STR_VAR_1}！$"

gContestPaintingSmart1::
    .string "智慧的艺术大师--\n聪明的宝可梦{STR_VAR_1}$"

gContestPaintingSmart2::
    .string "{STR_VAR_1}--被选中的宝可梦\n宝可梦中的宝可梦$"

gContestPaintingSmart3::
    .string "优秀的{STR_VAR_1}的\n高贵瞬间$"

gContestPaintingTough1::
    .string "肌肉发达的\n{STR_VAR_1}$"

gContestPaintingTough2::
    .string "强壮，无比强壮\n的{STR_VAR_1}$"

gContestPaintingTough3::
    .string "极为强悍的\n易激动的宝可梦{STR_VAR_1}$"
