EventTicket_Text_ShowOldSeaMap::
    .string "去凯那的游船…\p嗯？什么？\n要去地图上的这个地方吗？\p我认得一个人，也许能\n帮上你。请稍等。$"

EventTicket_Text_ThatPass::
    .string "去凯那的游船…\p哦？\n那张船票…$"

EventTicket_Text_ShowEonTicket::
    .string "嘿，伙计，拿着那张\n奇怪的船票的人就是你吗？\p我说，那可是南方\n非常远的一个小岛，\p而且谁也不知道到那儿之后\n会碰上什么东西，\l想想就激动啊！\p上船了！$"

EventTicket_Text_SouthernIslandSailBack::
    .string "嘿，伙计，看来这根本是个\n没什么探索价值的荒凉的岛，\p回水静市去怎么样？$"

EventTicket_Text_SailHome::
    .string "好的！出海，回家去了！$"

EventTicket_Text_AsYouLike::
    .string "好的，你随意吧。$"

SouthernIsland_Interior_Text_Sign::
    .string "“所有的梦境都只是另一个现实。\n永远不要忘记…”$"

SouthernIsland_Exterior_Text_Sign::
    .string "“那些似已逝去的记忆，\n人们会将其镌刻在心的最深处…”$"
