@ Battle Tower
gText_AnabelWonSilver::
    .string "这令人非常失望…$"

gText_AnabelDefeatSilver::
    .string "好，我知道…$"

gText_AnabelWonGold::
    .string "十分抱歉…$"

gText_AnabelDefeatGold::
    .string "谢谢…$"

@ Battle Dome
gText_TuckerWonSilver::
    .string "啊哈哈哈！你不感到麻烦吗？\n人们都看着呢！$"

gText_TuckerDefeatSilver::
    .string "呃…\n你这么就…$"

gText_TuckerWonGold::
    .string "我巨蛋天王的头衔并不是浪得虚名的！$"

gText_TuckerDefeatGold::
    .string "啊哈哈哈！\n真兴奋！$"

@ Battle Factory
gText_NolandWonSilver::
    .string "好好干！\n这是很好的一课，不是吗？$"

gText_NolandDefeatSilver::
    .string "祝你好运！\n你应该明白你要做什么！$"

gText_NolandWonGold::
    .string "喂，喂，喂！\n已经结束了吗？$"

gText_NolandDefeatGold::
    .string "出什么事了？$"

@ Battle Pike
gText_LucyWonSilver::
    .string "哼哼…$"

gText_LucyDefeatSilver::
    .string "可恶$"

gText_LucyWonGold::
    .string "哈！$"

gText_LucyDefeatGold::
    .string "该死！$"

@ Battle Arena
gText_GretaWonSilver::
    .string "喂，快点！\n你要试着更努力才行！$"

gText_GretaDefeatSilver::
    .string "没办法！\n祝你好运！$"

gText_GretaWonGold::
    .string "呵呵！\n你怎么认为？$"

gText_GretaDefeatGold::
    .string "咦？\n你是认真的？！$"

@ Battle Palace
gText_SpenserWonSilver::
    .string "你的宝可梦之所以这么软弱\n是因为有你这个软弱的训练师！$"

gText_SpenserDefeatSilver::
    .string "啊…\n这是别的什么…$"

gText_SpenserWonGold::
    .string "唔啊啊啊啊！\n弟兄们，没有什么能吓到我们！$"

gText_SpenserDefeatGold::
    .string "咕哇！\n唔啊啊啊！$"

@ Battle Pyramid
gText_BrandonWonSilver::
    .string "喂！你是怎么了！\n让我们看看你的努力成果！起来！$"

gText_BrandonDefeatSilver::
    .string "就是这样！太棒了！\n你为此辛苦地努力着！$"

gText_BrandonWonGold::
    .string "嘿！现在放弃还太早了吧！\n起来！要对自己有信心！$"

gText_BrandonDefeatGold::
    .string "就是这样！你做到了！\n你一直为此努力着！$"
