LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket::
    .string "这里是宝可梦彩票中心。\p来我们商业大厦的所有顾客\n都可以抽一张宝可梦彩票，\p如果彩票的号码\n与你任何一只宝可梦的ID相同，\l我们将会赠送一样精美礼品。\l你想抽宝可梦彩票吗？$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow::
    .string "请明天再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain::
    .string "欢迎下次再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket::
    .string "请在此抽一张彩票。\n…{0xFC 8}盔{0xFC 8}盔…{0xFC 8}盔{0xFC 8}盔…{0xFC 8}盔{0xFC 8}盔$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait::
    .string "彩票的号码是{STR_VAR_1}，\p我需要对照一下你的\n宝可梦的ID，请稍候。$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon::
    .string "恭喜！\p你携带的{STR_VAR_1}的ID与\n彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon::
    .string "恭喜\p你盒子里的{STR_VAR_1}的ID与\n彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched::
    .string "很遗憾，\n没有找到相符的号码。$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched::
    .string "有两个数字相同，\n恭喜你获得三等奖！\l奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched::
    .string "有三个数字相同，\n恭喜你获得二等奖！\l奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched::
    .string "有四个数字相同，\n恭喜你获得一等奖！\l奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched::
    .string "啊，天哪，五个数字\n完全相同！\p恭喜你获得特等奖！\n奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis::
    .string "哎？\n好像你没有放奖品的地方了，\p等你的背包里腾出空间之后，\n请再来找我。$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding::
    .string "{PLAYER}？\n啊，我一直在等你，\l这就是替你保管的奖品。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2::
    .string "欢迎下次再来。$"
