MatchCall_WildBattleText1::
    .string "嗨！{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}。\p我见过这个{STR_VAR_2}就在刚才！\n但是我没办法抓到它。\p就只差一点点呀！\n好，待会见！$"

MatchCall_WildBattleText2::
    .string "你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我差点就抓住一只很棒的{STR_VAR_2}\n就在刚才。\p但是，它还是跑掉了。\n我真的很丧气啊！\p好了，再见！$"

MatchCall_WildBattleText3::
    .string "你好阿，{PLAYER}！\n是我呀，{STR_VAR_1}。\p我刚才差点抓住\n这个{STR_VAR_2}，但是给它逃掉了。\p差一点就成功了！\p今天算是毁了…\n好了，待会见！$"

MatchCall_WildBattleText4::
    .string "嗨，{PLAYER}{KUN}。\n{STR_VAR_1}就是我。\p你知道那种宝可梦{STR_VAR_2}么？\n我差点就抓到一只。\p就在刚才。\n我以为我已经抓到了，但是它挣脱了。\p如果再让我看见它\n他肯定跑不了！\p好，待会再和你联系。$"

MatchCall_WildBattleText5::
    .string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\l最近抓到什么宝可梦了么？\p刚才我几乎就\n抓住一只，但是它逃掉了。\p好，多保重！$"

MatchCall_WildBattleText6::
    .string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l最近抓到什么宝可梦了么？\p那天我差点抓住一只。\n但是给它闪开了。\p多保重。$"

MatchCall_WildBattleText7::
    .string "…嗯，{PLAYER}{KUN}？\n是我，{STR_VAR_1}。\p哦，等等！等等！\n我能抓住这只{STR_VAR_2}…\p啊啊！给他逃了！\n只差一点点啊！$"

MatchCall_WildBattleText8::
    .string "哦，{PLAYER}{KUN}，最近如何？\n我是{STR_VAR_1}。\p你最近有抓到过什么\n宝可梦么？\p我刚刚悄悄的靠近了一只\n但是，我的猎物还是逃掉了。\p我还未够本呀！\n一会见！$"

MatchCall_WildBattleText9::
    .string "哦，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p哦？你正在收集宝可梦\n是么？\p我最近过得糟透了，因为它们！\n它们都逃跑了！\p再见！$"

MatchCall_WildBattleText10::
    .string "哦，{PLAYER}{KUN}，你好…\n我是{STR_VAR_1}。\p听着，我几乎已经\n够着这只{STR_VAR_2}了…\p但是，它脚底抹油了…\p我还未够本呀。\n待会见。$"

MatchCall_WildBattleText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l最近怎么样？\p我想抓只野生的{STR_VAR_2}\n就在刚才，但是它成功挣脱了。\p我败了…$"

MatchCall_WildBattleText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还在抓那些宝可梦吗？\p我也试着自己去抓他们\n但是，这没有那么容易呀。\p宝可梦之道是博大的！$"

MatchCall_WildBattleText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l你抓到宝可梦了吗？\p我自己也尝试着去抓几只，\n但是很少有成功的。\p宝可梦之道是精深的！$"

MatchCall_WildBattleText14::
    .string "哦，嗨，{PLAYER}{KUN}，你好么？\n我是{STR_VAR_1}。\p刚才，我差点抓到一只可爱的\n{STR_VAR_2}。\p可恨给它跑了！\n哦，我真的很难过啊！\p再见！$"

MatchCall_WildBattleText15::
    .string "嘿，{PLAYER}！\n我是{STR_VAR_1}！\p我正在思考，怎样才能\n抓一两只宝可梦。\p但是还是没想出好办法。\n这真是个难题啊！\p真的把我难住了！\n以后再见！$"

MatchCall_NegativeBattleText1::
    .string "嗨！{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}。\p我试着挑战了另一个训练师，\n但是我输了。\p真丧气。\n好了，以后再聊！$"

MatchCall_NegativeBattleText2::
    .string "你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我挑战另一个家伙\n我们大战了一场。\p我差点就赢了，但是最后\n我输了。哎，没事没事！$"

MatchCall_NegativeBattleText3::
    .string "嘿你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我在刚刚的战斗里面一败涂地。\p我想我需要更进一步\n锻炼我的队伍！$"

MatchCall_NegativeBattleText4::
    .string "嘿，{PLAYER}。\n{STR_VAR_1}是我。\p我昨天又打了一场，\n可还是没办法赢。\p我的小队需要再练练。\nOk，以后再聊。$"

MatchCall_NegativeBattleText5::
    .string "嘿嘿，{PLAYER}！\n我是{STR_VAR_1}。\p最近怎么样？\p我在不停的战斗，\n但不是经常能赢。\p我还是不能找到窍门。\n好了，保重！$"

MatchCall_NegativeBattleText6::
    .string "嘿，{PLAYER}。\n我是{STR_VAR_1}呢。\p最近还好吗？\p我最近战的昏天黑地，\n但是几乎全输了。\p我还是没能参透诀窍。\n你自己保重。$"

MatchCall_NegativeBattleText7::
    .string "{STR_VAR_1}。\n最近还顺利么？\p我昨天又输了，\n现在我满脑子都是这事。\p我必须好好计划一下…\n再见。$"

MatchCall_NegativeBattleText8::
    .string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}呀。\p你的那些宝可梦还好吗？\n前天我又输了一场比赛。\p我要更努力些！\n再见！$"

MatchCall_NegativeBattleText9::
    .string "喂，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p听好，听好，你一定要\n听听这个！\p我刚才来了场宝可梦大战，\n我在最后几秒的时候被打败了。\p哦哦，气死我了！$"

MatchCall_NegativeBattleText10::
    .string "喂，{PLAYER}{KUN}，你好…\n我是{STR_VAR_1}。\p不久前，我在战斗。\n最后，我输了。\p我要进一步提升我的宝可梦。\n再见。$"

MatchCall_NegativeBattleText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l你的宝可梦咋样了？\p我又输掉了一场。\p哦，再见！$"

MatchCall_NegativeBattleText12::
    .string "喂你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还在拼命战斗么？\p我？我最近老是输，所以\n我在训练我的队伍。\p以后见。$"

MatchCall_NegativeBattleText13::
    .string "喂，你好啊，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我希望你一切顺利。\p我刚刚大战一场\n就在不久前。\p{PLAYER}{KUN}，要像我一养努力啊。\n再见！$"

MatchCall_NegativeBattleText14::
    .string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p最近如何？\p你要经常回家看看啊，\n咳咳。\p再见！$"

MatchCall_PositiveBattleText1::
    .string "嗨！{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我和另外的一个训练师打了一场。\n我赢了！赢了！\p我的{STR_VAR_2}真的干得很漂亮！\n太棒了！$"

MatchCall_PositiveBattleText2::
    .string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我昨天战了一场\n而且我赢了！太美妙了！$"

MatchCall_PositiveBattleText3::
    .string "喂你好，{PLAYER}！\n我是，{STR_VAR_1}！\l你的战斗如何？\p我，前些天战了一场，\n我的{STR_VAR_2}变得很巨大！\p下次再遇到你，\n{PLAYER}，输的就不是我了！$"

MatchCall_PositiveBattleText4::
    .string "嘿，{PLAYER}。\n{STR_VAR_1}在此。\p早些时间我有一场比赛。\n我努力去赢的，但还是差一点。\p我的{STR_VAR_2}上演了\n一出好戏。$"

MatchCall_PositiveBattleText5::
    .string "嘿呀，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p最近怎么样？\n战绩如何？\p我刚刚赢了一场！\n我的{STR_VAR_2}是天才！\p你等着。我一定会打败你的\n一定！好了，你要小心！$"

MatchCall_PositiveBattleText6::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\p一切顺利吗？\p我正站在领奖台上。\n为什么？我刚刚赢了一场战斗。\p当我们下次交手的时候，\n我肯定不会输了！$"

MatchCall_PositiveBattleText7::
    .string "{PLAYER}{KUN}？\n{STR_VAR_1}在此。\p我的{STR_VAR_2}是个好战力！\n我刚刚又赢了一场！\p我真想现在就和你\n赛一场。$"

MatchCall_PositiveBattleText8::
    .string "哦，{PLAYER}{KUN}，你好么？\n我是{STR_VAR_1}呀。\p我希望你一切都好。\n我想告诉你我刚刚赢了。\p我的{STR_VAR_2}非常努力\n所以我们才能赢得比赛。\p一会见！$"

MatchCall_PositiveBattleText9::
    .string "哦，{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}！\p你现在得宝可梦怎么样了？\n我的那只刚刚赢了一场！\p我的{STR_VAR_2}真是太弓虽了，\n我只能这么说！\p我希望能你能看看！\n以后见！$"

MatchCall_PositiveBattleText10::
    .string "哦，{PLAYER}{KUN}，好啊…\n我是{STR_VAR_1}。\p最近过得好吗？\p我的宝可梦现在\n充满了能量。\p我刚刚靠他们获得了胜利。\n以后见。$"

MatchCall_PositiveBattleText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p最近有战过么？\n我今天又打败了一个！\p太美了！哈哈哈哈！\n好了，回见！$"

MatchCall_PositiveBattleText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\p我相信你过的不错？\n我仍然充满了活力！\p因为我刚刚又赢了一场。\n我不会输给你们这些\l小屁孩的！$"

MatchCall_PositiveBattleText13::
    .string "啊，好啊，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我希望你一切都好。\n我现在进入了反弹期！\p我刚才又赢了一场。\n哦，我现在不会输给你们这些\l小屁孩的！\p再见！$"

MatchCall_PositiveBattleText14::
    .string "哦，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我刚刚经历了一场恶战，我的\n{STR_VAR_2}是独一无二的！\p我希望你能见识一下，\n{PLAYER}{KUN}。再见！$"

MatchCall_SameRouteBattleRequestText1::
    .string "嗨！{PLAYER}，你好！\n这里是{STR_VAR_1}。\p嗯？等一下，你在\n{STR_VAR_2}附近？\p哦，哇噢，让我们来战吧！\n我等着你！回见！$"

MatchCall_SameRouteBattleRequestText2::
    .string "你好，{PLAYER}！\n我是{STR_VAR_1}。\p啊？你说正在\n{STR_VAR_2}这里？\p我们来战一场可以么？\n我等你啊！回见！$"

MatchCall_SameRouteBattleRequestText3::
    .string "嗨你好，{PLAYER}！\n是我，{STR_VAR_1}。\p哦，嘿，你就在\n{STR_VAR_2}这里？\p我们来战一场怎么样？\n就现在。\p我不会再输了！\n我等着你啊！快来吧！$"

MatchCall_SameRouteBattleRequestText4::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\p你在哪里？\n啥？{STR_VAR_2}？\p来战么？\n我会等你的。回见！$"

MatchCall_SameRouteBattleRequestText5::
    .string "好哇，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\l最近如何？\p你在哪里？\n{STR_VAR_2}？\p好罢，你说我们之间\n再赛一场如何？\p我盼你来啊。\n再见！$"

MatchCall_SameRouteBattleRequestText6::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\l你的宝可梦还好吗？\p哈，真的？你就在\n{STR_VAR_2}这里？\p这样，那么，我们再来\n比试一场。\p我等这你。\n再见！$"

MatchCall_SameRouteBattleRequestText7::
    .string "…呃，{PLAYER}{KUN}？\n{STR_VAR_1}这里…\p哦，你碰巧在附近\n{STR_VAR_2}？\p那么，来战吧。\n马上，我是说。\p我想给你看看我的宝可梦。\n我等着你。$"

MatchCall_SameRouteBattleRequestText8::
    .string "哦，{PLAYER}{KUN}，你还好么？\n我是{STR_VAR_1}呀。\p希望你一切都好。\n哦，你就在{STR_VAR_2}这里啊。\p你想来跟我\n战一场么，嗯？\p我等着你。\n一会见！$"

MatchCall_SameRouteBattleRequestText9::
    .string "嗯，{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}！\p一切都好么？\n哦，你就在{STR_VAR_2}附近？\p哦，好吧，你不想和我\n战一场么？\p别让我等太久！$"

MatchCall_SameRouteBattleRequestText10::
    .string "哦，{PLAYER}{KUN}，好…\n这里是{STR_VAR_1}。\p过得顺利么？\n哦，你在{STR_VAR_2}这里。\p那么你应该来战一场，嗯。\p我准备好了等你。\n快点！$"

MatchCall_SameRouteBattleRequestText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p啊，你现在正在\n{STR_VAR_2}？\p那么，我们之间一定要\n来战一场的，不是么？\p我在这里等你！\n回见！$"

MatchCall_SameRouteBattleRequestText12::
    .string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你现在在哪儿呢？\p{STR_VAR_2}？\n很近的么！\p你说我们来战一场\n怎么样？\p我能等的。\n再见！$"

MatchCall_SameRouteBattleRequestText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我希望你一切顺利。\n哦，你在{STR_VAR_2}附近？\p不是很远么，\n来和我战一场吧。\p我等你。\n再见。$"

MatchCall_SameRouteBattleRequestText14::
    .string "哦，好，{PLAYER}{KUN}。\n我数{STR_VAR_1}。\p你在哪儿？…{STR_VAR_2}？\n很近。\p你不认为我们应该\n战一场么？\p我会等你的！\n拜拜！$"

MatchCall_DifferentRouteBattleRequestText1::
    .string "嗨！{PLAYER}，你好！\n我是{STR_VAR_1}。\p想和我战一场么？\p我就在\n{STR_VAR_2}等你！$"

MatchCall_DifferentRouteBattleRequestText2::
    .string "你好啊，{PLAYER}！\n我是{STR_VAR_1}。\p你想要\n再和我比试么？\p你能在\n{STR_VAR_2}找到我。我等着呢！$"

MatchCall_DifferentRouteBattleRequestText3::
    .string "你好啊，{PLAYER}！\n是我，{STR_VAR_1}。\p我的宝可梦在上一次之后\n又成长了许多。\p我想看看他们和你的宝可梦比起来\n到底变强了多少，{PLAYER}。\p那么，让我们来战吧！\p我等着你，就在\n{STR_VAR_2}。$"

MatchCall_DifferentRouteBattleRequestText4::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\l你还好么？\p我的宝可梦已经\n成长了不少。\p嘿，你想来和我\n再战一场么？\p让我们在\n{STR_VAR_2}见面，好么？$"

MatchCall_DifferentRouteBattleRequestText5::
    .string "嘿，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我的宝可梦在最近几天\n成长了不少。\p我真的非常想和你\n再战一场。\p我会一直等着你的，就在\n{STR_VAR_2}这里。回头见！$"

MatchCall_DifferentRouteBattleRequestText6::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\l我希望你一切顺利。\p我想什么时候能和你再战一场。\n你说什么？\p如果你想来战，\n到{STR_VAR_2}这里来。\p再见！$"

MatchCall_DifferentRouteBattleRequestText7::
    .string "…呃，{PLAYER}{KUN}？\n{STR_VAR_1}在此…\l哈？你的宝可梦成长了么？\p我的也是。\n我希望能给你看一下。\p我会去{STR_VAR_2}那里。\n来和我再战一场吧。\p以后见。$"

MatchCall_DifferentRouteBattleRequestText8::
    .string "哦，{PLAYER}{KUN}，你好么？\n我是{STR_VAR_1}。\p我希望你一切都好。\n我的宝可梦非常的活跃。\p如果你和我在一个地方，\n和我再战一场吧。\p我就在{STR_VAR_2}。\n不见不散，再见！$"

MatchCall_DifferentRouteBattleRequestText9::
    .string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\l你的宝可梦还好吗？\p我的宝可梦越来越强了。\n我想给你见识一下，{PLAYER}{KUN}。\p我现在就在{STR_VAR_2}这里，\n如果你在附近的话，那么就让我们战一场吧。\p希望能早点见到你！$"

MatchCall_DifferentRouteBattleRequestText10::
    .string "哦，{PLAYER}{KUN}，你好…\n我是{STR_VAR_1}。\l啊，最近还好吗？\p我的宝可梦可是比以前\n要强多了。\p我很想和你再战一次，\n{PLAYER}{KUN}。\p现在我在{STR_VAR_2}。\n如果方便的话就来吧。$"

MatchCall_DifferentRouteBattleRequestText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l现在的你会在哪里？\p我的宝可梦现在充满了活力。\n它们说很想再会会\l你的那些宝可梦，{PLAYER}{KUN}。\p我现在就在{STR_VAR_2}这里。\n希望你能找到我们。$"

MatchCall_DifferentRouteBattleRequestText12::
    .string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\p我想要告诉你，我的宝可梦已经\n成长了非常之多。\p我希望再和你战的时候\n能看到，{PLAYER}{KUN}。\p我们就在{STR_VAR_2}。\n随时欢迎！$"

MatchCall_DifferentRouteBattleRequestText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l你的宝可梦都好吗？\p我的宝可梦非常得健壮，\n他们不像是会输给你的样子！\p我很想再和你战一场，\n非常想。\p如果你在{STR_VAR_2}附近，\n来找我吧。$"

MatchCall_DifferentRouteBattleRequestText14::
    .string "哦，好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l一切都好吧。\p哦，对了！我的宝可梦已经\n比以前强大了不少。\p你不觉得我们应该\n再战一场么，{PLAYER}{KUN}？\p我会在\n{STR_VAR_2}等着你的。\p你随时都能来，行吗？$"

MatchCall_PersonalizedText1::
    .string "是我啊，热爱大山的\n{STR_VAR_1}！\p那个，上次见过以后，你是不是\n也开始喜欢群山了呢？\p我很少在山里看见你呀…\p下一次，让我们在\n{STR_VAR_2}碰头吧。$"

MatchCall_PersonalizedText2::
    .string "我是{STR_VAR_1}。\n你好。\p我刚刚告诉了一个新人训练师\n有关你的事。\p我告诉她有一个强大的训练师\n用爱心培养他的宝可梦。\p我希望你能成为一个\n人人称赞的训练师。\p希望能再见到你！$"

MatchCall_PersonalizedText3::
    .string "你好！我是{STR_VAR_1}。\p我爱上我在的这个地方了。\n多么怡人的芳香！\p我想有人种下了些树果，\n它们正在开花。\p再见！$"

MatchCall_PersonalizedText4::
    .string "你好！具有30年经验的探险家，\n{STR_VAR_1}为你服务！\p看上去你正在充满干劲的\n走东闯西呢。\p你发现了什么新的遗迹吗？\n如果有的话要告诉我！\p那么，如果没有的话，\n我自己有遗迹要去探索。$"

MatchCall_PersonalizedText5::
    .string "我是{STR_VAR_1}！\p知道我正在做什么吗？\n我正在海边看海浪！\p啊…浪花多么美丽啊。\n这里真是看海的好地方啊。\l我有点饿了，再见了！$"

MatchCall_PersonalizedText6::
    .string "嗯嗯…\n哦，嗨，我是{STR_VAR_1}。\l我喜欢在海滩上吃东西。\p我的宝可梦和我都很愉快。\n我们充满活力！\l我要去游个泳。再见！$"

MatchCall_PersonalizedText7::
    .string "你好，我是{STR_VAR_1}…\p我对这个酷训练师\n已经有些厌倦了…\p每个人都认为我是完美的\n训练师，这迫使我\l按照别人期望而活着。\p但是我想要作个出色的\n酷训练师。\p我必须认真干…\n微笑着承受这一切。\p这些话\n我只对你一个人说。\p当我下一次见到你的时候，\n放心，我不会抱怨的！$"

MatchCall_PersonalizedText8::
    .string "哟荷，我是{STR_VAR_1}！\n你好吗？\p我现在正在训练我的宝可梦，\n你是我的目标哦。\p下次遇见你的时候\n我不会再输了。\p你说有一个训练师朋友\n不是很棒么？再见吧！$"

MatchCall_PersonalizedText9::
    .string "我是{STR_VAR_1}…\n现在，在你的后面…\l你不觉得那里有东西么…？\p那是沉睡在送神火山的\n宝可梦之大能…\p他告诉了我你的存在…\p赶快离开这里，而且\n不要回头…\p口桀口桀…\n再见…$"

MatchCall_PersonalizedText10::
    .string "我是{STR_VAR_1}。\n最近好么？\p能够远距离通话\n真是方便那？\p之前，如果我想和谁聊聊的话\n我只有叫我老爸\l开车载我去…\p我要走了。\n和你聊天很愉快。$"

MatchCall_PersonalizedText11::
    .string "我是{STR_VAR_1}！\n你听着呢吗？\p我很喜欢野生原野区，\n但是不管我怎么走，我都迷路了！\p到处是高高的杂草！\n而且他们实在太多了！\p几乎都戳到\n我的胸口了！\p我要再次向野生原野区出发了！\n回见！$"

MatchCall_PersonalizedText12::
    .string "你好，{STR_VAR_1}在此。\n嗯，没错，我有钱了，嗯。\p我要告诉你，我的财富\n在上次见面后又增加了不少。\p而且，我的宝可梦也变得\n更强了。\p我不得不开始怀疑\n地球是围着我转的！\p哦，无需多言！\n事实就在眼前！\p哦，我必须说声抱歉，我还有一个\n重要的晚宴要参加。$"

MatchCall_PersonalizedText13::
    .string "呼呼呼…\n是我，{STR_VAR_1}…\p你能猜到我看见了什么吗？\n一对{STR_VAR_2}正在打架。\p也许我应把胜利者抓住…\n呼呼呼…\p我要去忙了。\n我走了。$"

MatchCall_PersonalizedText14::
    .string "哦，我是{STR_VAR_1}！\p我已经开始觉得\n呆在被遗弃的海船里有些无聊了。\p但既然我来了，\n而且我想打败你一次，\l那么我得多呆一会。\p如果你愿意的话，为什么\n不来看看我？\p我想今天\n我终于可以和\l我的老邻居来场比赛了。\p再见！$"

MatchCall_PersonalizedText15::
    .string "我是{STR_VAR_1}！\n海之男！\p你知道我在想啥么？\p从大海里来的训练师\n才是强者中的强者呀！\p你一定要跟我学点东西\n还要在大海里修炼…\p哦哦哦，洪波涌起！\p这是多么好的修炼机会啊！\n抱歉，我先闪了！$"

MatchCall_PersonalizedText16::
    .string "在下是{STR_VAR_1}！听着，我一直在\n传授空手道给我的宝可梦。\p它们现在已经比我强了！\n我还来不及反应就败给他们了！\p但即便是我输给了\n宝可梦，我也不可能输给\l训练师的，没门！\p我们要再战一场！\n呜哇！$"

MatchCall_PersonalizedText17::
    .string "是我，{STR_VAR_1}。\n你的旅行顺利吗？\p…哇，真的真的？\n听起来真是刺激啊！\p我想我应该写一首\n有关你的歌。\p…哦，嘿，我正在找灵感呢。\n我的脑海里已经有旋律了。\p我得把曲子记下来\n嗯，我必须走了！一会见！$"

MatchCall_PersonalizedText18::
    .string "我是{STR_VAR_1}…\n听听我的新歌吧。\p啦啦啦，{STR_VAR_2}，{STR_VAR_2}！\n为什么你是{STR_VAR_2}？\l为什么我不能成为你，{STR_VAR_2}？\l啦啦，{STR_VAR_2}和{STR_VAR_1}，\l{STR_VAR_1}和{STR_VAR_2}…\p反复，淡出…$"

MatchCall_PersonalizedText19::
    .string "我是{STR_VAR_1}，你知道的，\n野营专家！\p当我们战的时候，\n我情不自禁的输给了你。\p之后，我学习了野营的知识。\p无论结果如何，\n我都想在野营的时候去战斗。\p再和我们战一场吧，怎么样？\n哦，再让我们去野营吧！$"

MatchCall_PersonalizedText20::
    .string "是我呀，我，{STR_VAR_1}！\p凭良心讲，我想\n去爬一座比这更高的山。\p但是我不能确定别的山的美女\n能像火山口的一样多。\p如果你知道哪座山\n隐藏着美女的，让我知道！\p哦活活，再见啦！$"

MatchCall_PersonalizedText21::
    .string "… … … … … …\n… … … … … …\l我是{STR_VAR_1}…\p… … … … … …\n… … … … … …\l今天就到这里…$"

MatchCall_PersonalizedText22::
    .string "我是{STR_VAR_1}。今天，我想\n和你聊聊。\p我击败你的欲望\n与日俱增。\p你想要个好对手，是吧？\n我希望我就是…\p很高兴你能听我。\n再见！$"

MatchCall_PersonalizedText23::
    .string "我是{STR_VAR_1}。\p每当一个强大的训练师\n在附近，我都能感觉到\l奇怪吧。\p你就在我附近么，{PLAYER}{KUN}？\n我希望那是你。\p我等着你。\n再见！$"

MatchCall_PersonalizedText24::
    .string "你好，我是{STR_VAR_1}。\n听起来你还不错，{PLAYER}{KUN}。\p我周游了世界，\n但是我承认\l我被这个国度迷住了。\p我计划多呆一会。\n也许我们应该再见一次？\p我忘不了你炫目的\n技术。\p我真的想再战一场。$"

MatchCall_PersonalizedText25::
    .string "吸鼻涕…我是…{STR_VAR_1}…\n…吸…\p杜娟在班里训了我，\n就在今天。\p但是我并不嫉恨她或者别的什么人。\p杜娟详细的告诉了我\n哪里做错了，这样我能吃一堑长一智。\p我明天就要去\n训练师学校报道了w！\p以后再见！$"

MatchCall_PersonalizedText26::
    .string "我是{STR_VAR_1}！\p昨天，杜娟让我和她\n交了手。\p结果么…\n很糟，和你想的一样。\p但是我很欣赏杜娟\n居然允许我挑战她！\p你不知道我有多么\n崇拜她！\p我必须努力学习！\n我要走了！$"

MatchCall_PersonalizedText27::
    .string "嗨，我是美穗！我仍和我的\n伙伴利可在一起。\p我非常喜欢照料那些利可\n和宝可梦。它们真是可爱啊！\p我希望我能好好的照顾它们\n就像对自己的亲人一样！\p哦，嘿，利可！\n我要你去买的小面包呢？\p什么？不，不，我没有把你\n当作自己的奴隶啊！\p你输掉了比赛，所以你必须\n去帮我买面包，这是惩罚！\p我不会把你当作我的奴仆的，\n利可！你对我真是太重要了！\p我得走了。\n现在是甜点时间了！$"

MatchCall_PersonalizedText28::
    .string "我喜欢宝可梦！\n我是从宝可梦同好会来的{STR_VAR_1}！\p你一定要听听这个！\n我可爱的宝可梦…\p呼呼！哈哈哈哈！\n我已经不能再说！这是个秘密！\l你的可爱已经没法用语言形容了！\p哦，我可爱的{STR_VAR_2}\n正渴求着能量方块！\p真是卡哇伊的照片啊！\p抱歉，我不能再说了！\n你下次也一定要听我说啊！$"

MatchCall_PersonalizedText29::
    .string "活活！\p我是{STR_VAR_1}！我一定要\n跟你说说我心爱的宝可梦！\p求你了，一定要听我说。\n这是我的甜心{STR_VAR_2}。\p不管谁拾起它，\n它都会直接逃回我的怀里！\p哦…哦…还有比这\n更幸福的感觉么？\p哦，我好像在天堂！\p你和我分享这份快乐\n我非常高兴。\p好，我要走了。\n再见！$"

MatchCall_PersonalizedText30::
    .string "我是…{STR_VAR_1}。\n人们都叫我专家。\p但是我知道一件事。\n在驾驭我自己的能力方面，\l我不能算是专家。\p只有在宝可梦的帮助下，\n一个训练师才能成为一个专家。\p哼哼！我想我说的是不是\n太深奥了！\p我应该给你留份好心情的！$"

MatchCall_PersonalizedText31::
    .string "我是{STR_VAR_1}。\n很高兴和你谈话！\p能泡个热水澡\n感觉真是好啊。\p自从上次交手以后\n我又和年轻训练师在战，但是你还是\l他们当中最出色的。\p可以想象你会在成年以后\n成为一个专家的！呵呵呵…$"

MatchCall_PersonalizedText32::
    .string "耶！我是{STR_VAR_1}！\n出了什么事？\p我可以想象，但是\n当我赢得比赛得时候，我的缺点看起来\l可能，也许，好像，貌似……总的来说。\p我再说些什么……？\n我很难表达，但是…\l我改怎么说哪…\l我的缺点看上去那么微小！\p但是我和你战的时候，{PLAYER}{KUN}，\n我的缺点却是那么明显而又让人讨厌。\p… … … … … …\n你不会当真吧？\l呵呵，就到这里吧！再见！$"

MatchCall_PersonalizedText33::
    .string "咳咳！\n{STR_VAR_1}在此！\p和以前一样，我在\n狂野的捕鱼！\p除了大海和大河\n我还有其他地方能捕鱼吗？\p有一种强烈的欲望驱使着我\n去四处钓鱼！\p哦，该死，见鬼！\n我的线断了！\p我走了！\n帮我找些新的钓鱼场吧！$"

MatchCall_PersonalizedText34::
    .string "嘿，你好！我是{STR_VAR_1}。\n你最近过得很轻松吧？\p从我还是个孩子开始，要知道，\n我都生活得都很平静，是吧？\p我那时从来没有\n遇到过巨大的压力和刺激的事情。\p但是你不知道吧，\n我现在是个三项全能运动员了。\p你无法预见命运会把你带到哪里，\n如果你像我一样漂泊的话。\p你目前是个训练师，但是\n谁知道未来会怎样呢，是吧？\p想想看自己将成为一个导师，\n或是一个艺术家。酷，是吧？\p但是，嘿，冷静点。放轻松。\n再见了。$"

MatchCall_PersonalizedText35::
    .string "我是{STR_VAR_1}！\n我在骑自行车呢。\p我喜欢游泳和跑步，\n但是自行车是我的最爱！\p我感到我的整个身体\n好像和风化作一体了。\p好像随风飞行一样，\n感觉太棒了！\p好了！今天，我要创造一个\n自行车公路赛的新纪录！\p你也可以来挑战一下！\n再见！$"

MatchCall_PersonalizedText36::
    .string "哟，我是{STR_VAR_1}！我正在\n参加铁人三项赛！\p不过，嘿，我总是有时间\n来聊天的！\p和宝可梦一起共事真是\n太棒了！\p不用语言上的交流，我们默契的\n就好像是一个人似的。\p多美妙啊！\p呃…边跑聊天…\n上气不接下气了…\l呼…我…必须…挂了…$"

MatchCall_PersonalizedText37::
    .string "嗨，我是{STR_VAR_1}。\n如果你想增强耐力，\l那么就来参加高原训练！\p来山顶上跑步吧。\n你会跟本喘不上气！\p我也感到呼吸困难了！\n再见！$"

MatchCall_PersonalizedText38::
    .string "哦，我是{STR_VAR_1}，你好。\p我已经游了很长很长时间了\n但是看上去我还是到达不了彩幽市。\p难道我正在兜圈子。\p不，不，那绝对不可能。\n哇哈哈哈。\l保重！$"

MatchCall_PersonalizedText39::
    .string "嘿，我是{STR_VAR_1}…\n哇！\p扑通！\p啪-啪-啪-啪…\p哗啦！\p呼-呼！呼-呼！\p嘿！不好意思啊！\n我在抹防晒油哪。\p所以我的手滑了一下，\n口袋领航员就一下子掉到水里了！\p不过，得文的\n口袋领航员是非常结实的。\p泡到水里都没事！\p总之，我要晒日光浴了，\n改日再聊吧。$"

MatchCall_PersonalizedText40::
    .string "你好，我是{STR_VAR_1}。\p铁人三项赛里面，\n我最喜欢游泳了。\p但是如果我在海水里呆的时间太长，\n我岂不是会被泡的像一棵海参了？\p哦，铁人三项赛真是对\n人类耐力的严酷考验啊！再见！$"

MatchCall_PersonalizedText41::
    .string "你好，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\p你的宝可梦还好吗？\p我的龙宝可梦已经进化到\n终极形态了。再见。$"

MatchCall_PersonalizedText42::
    .string "{STR_VAR_1}在此。\p我的{STR_VAR_2}可是要比上一次的时候\n强多了。\p我不会在输给你了。\n你就等着吧！\p再见了！$"

MatchCall_PersonalizedText43::
    .string "我是{STR_VAR_1}。\p我正在进阶研究\n躲猫猫的艺术。\p但是我实在是太成功了。\n现在没人能找到我了。\l我的成功让我很孤独…\p我就像一阵烟尘，消失了！\n别了！$"

MatchCall_PersonalizedText44::
    .string "我是{STR_VAR_1}。\n再上次见面以后我一直在修炼。\p我的{STR_VAR_2}已经比以前\n强多了。\p在沙滩上修炼是很有成效的，\n和预料中的一样。再见！$"

MatchCall_PersonalizedText45::
    .string "你好吗？\n我是{STR_VAR_1}。\p我在想这些该死的火山灰\n要下到什么时候？\p如果再这样下去，我小花伞\n上的图画都要被盖住了…\p说好了一定要再见啊！$"

MatchCall_PersonalizedText46::
    .string "嗨，{STR_VAR_1}在此。\p你知道吗？浮在海水里\n比浮在池子里简单很多呢。\p只要躺着别动，你的身体\n会自己飘起来。\p但是如果你漂浮的时间太长，\n当心别被海流\l带出很远啊。\p…我在哪里？别管了…\n我得挂了！$"

MatchCall_PersonalizedText47::
    .string "喂，{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}。\l我正在山里呢。\p但是这地面真是不平。\n我不能在这里搭帐篷…\p哦，我有个天才的想法！\p也许我能用宝可梦来\n平整土地！\p这就去试试看！\n再见！$"

MatchCall_PersonalizedText48::
    .string "喂，嗨，嗨，我是{STR_VAR_1}！\p我正在用留美培养我的宝可梦！\n我们正在努力尝试中！\p如果我们再努力些，我们会成为\n第一吗？再见！$"

MatchCall_PersonalizedText49::
    .string "我是{STR_VAR_1}！\p我是个水手，但是现在我并不在\n船上。\p我很好奇如何来称呼\n一个在陆地上的水手呢？\p这就是我经常在远航时\n所想的问题。\p好了，下次见！$"

MatchCall_PersonalizedText50::
    .string "我是{STR_VAR_1}。\n啥？获得更多的宝可梦了吗？\p如果你抓到了新的宝可梦，\n你一定要来给我看看。\p我不会嫉妒的，相信我。\n我等着你。会见。$"

MatchCall_PersonalizedText51::
    .string "这里是{STR_VAR_1}。\p你正在用正确的方法\n来培养你的宝可梦吗？\p我这里的空气很清洁呀。\n对于培养宝可梦来说\l这是最好的环境。\p如果你还在致力于培养\n宝可梦，你应来\l{STR_VAR_2}。来看看吧$"

MatchCall_PersonalizedText52::
    .string "嗨，我是{STR_VAR_1}。\p我给了我的{STR_VAR_2}一个能量方块。\n它看上去非常喜欢。\p看上去宝可梦的喜怒哀乐\n都是和能量方块相关的。\p这真是不可思议啊。\n多保重。$"

MatchCall_PersonalizedText53::
    .string "我是{STR_VAR_1}。\p如果你和宝可梦一起合作，\n那么在野外是很适合的。\p每个人都应该知道这一点\n并且和宝可梦更多的合作。\p那样就好了。\n我是这么认为的。\p我希望你走在正道上！\n稍后联系！$"

MatchCall_PersonalizedText54::
    .string "嗨，我是{STR_VAR_1}。你要知道，\n训练师是时刻准备着的！\p{PLAYER}{KUN}，你有足够的物品吗？\n你的宝可梦适合行动吗？\p让你身边的一切事情\n都保持在最佳状态，o\l是继续冒险的秘密。\p我去检查我自己的装备去了\n时刻准备着！$"

MatchCall_PersonalizedText55::
    .string "我是{STR_VAR_1}！\n我是{STR_VAR_1}！\p{STR_VAR_2}是一条非常繁忙的\n街道，所以\l我每天都能挑战各种训练师。\p今天，我赢了5次\n只败了3场！\p你的战绩呢？\n下次告诉我吧，好吗？$"

MatchCall_PersonalizedText56::
    .string "是我，{STR_VAR_1}。\p我人气旺盛！因为我有\n很多虫宝可梦，对吧？\p对了，今天我带了一些\n最喜欢的虫子去学校了。\p我喜欢的女孩子被吓哭了！\n你想笑就笑吧。\p我必须让她知道\n那些虫宝可梦是多么的有吸引力。\p吸鼻涕…\n再见！$"

MatchCall_PersonalizedText57::
    .string "呼！呼！呼！呼！\p嗨！我是{STR_VAR_1}！呼！呼！\p尝试着…\n登山的时候聊天…\l是多么困难的训练啊…呼！呼！\p哇！呜…\n山峰真陡峭…\l我们要改日…再谈了…\l呼！呼！哇！$"

MatchCall_PersonalizedText58::
    .string "哦，嗨！\p我依然和奇拉一起\n寻找财宝！\p也许这里什么财宝\n都没有…\p但是和奇拉一起搜索\n对我来说很重要。\p哦，嘿，奇拉！\n为…为什么那么生气？\p我没有忽略你，宝贝！\n你就是我的唯一！\p…{PLAYER}，我要挂了，再见！$"

MatchCall_PersonalizedText59::
    .string "我是{STR_VAR_1}！\p我又去了武斗镇的道馆\n去锻炼。\p藤树，道馆馆主，看上去\n更壮了。\p看上去\n巨浪的确能锻炼人…\p但他还是和原来一样酷。\nMM都围着他！\l实话说，我有点嫉妒。\p我很好奇…他的朋友志霸\n是个和藤树差不多的人么？\p你知道，那些优缺点，\n还有总喜欢把叫别人\l“大波”什么的。\p但是，嘿，我嫉妒的\n不是很明显吧？\p你就当我什么都没跟你说吧，\n怎么样？再见！$"

MatchCall_PersonalizedText60::
    .string "我非常高兴\n能和你这样的年轻训练师交流。\p我可以想象你不管在任何时间\n都会喜欢宝可梦的。\p为什么你不像我们一样\n来合作呢？\p当然，{PLAYER}{KUN}，你已经\n在享受和宝可梦之间的\l信任和合作关系了。\p你已经建立了\n长久而牢固的关系了！\p哈哈！\n永远不能气馁！$"

MatchCall_PersonalizedText61::
    .string "嗨，我是{STR_VAR_1}！\n我们刚刚赢了一场战斗！\p我们不是每次都能赢，但是它真的是个\n很酷的游泳者。\p我的妹妹又在发牢骚了！\p她想装傻\n傻到对胜利没一点印象！\p不管我是赢是输\n她总是要说我一顿！\p{PLAYER}{KUN}，你能在下次\n跟她好好谈谈吗？\p好，再见！$"

MatchCall_PersonalizedText62::
    .string "我是{STR_VAR_1}，对。\n昨天我出海去了。\p我希望能发现一个\n新的遗迹。\p但是，海流好像把我\n又带回我出发的地方了。\p我还是不擅长战斗…\n想笑就笑吧…\l但是我不会放弃。\p等我发现了新的遗迹\n我就时来运转了！\p就说这么多了！\n再见咯！$"

MatchCall_PersonalizedText63::
    .string "喂，那个啥！\n是我，{STR_VAR_1}！\l我现在正在108号航道！上\l一句话，我还是在老地方！\p今天，一位美丽的\n比基尼大姐在我身旁游过！\p我朝她大叫了一声！\p然后她朝我狠狠瞪了一眼！\p就发生108号航道！\n以上是{STR_VAR_1}带给你的消息！$"

MatchCall_PersonalizedText64::
    .string "我是{STR_VAR_1}！\p我有点忙，但是我想\n我应该让你知道\l我今天又打败了五个训练师。\p如果保持这种势头，\n我下次就能击败你了。\p我想我们会成为好对手的，\n你和我。再见了！$"

MatchCall_BattleFrontierStreakText1::
    .string "嗨！我是{STR_VAR_1}。\n告诉你一个好消息！\p他们说你在{STR_VAR_2}\n做得很出色。\p真可怕，一下子就连赢了{STR_VAR_3}场？\n再见！$"

MatchCall_BattleFrontierStreakText2::
    .string "你好，我是{STR_VAR_1}！\n我听说过你！\p他们说你在{STR_VAR_2}\n一下子就打赢了{STR_VAR_3}局。\p太厉害了！我也要努力！\n再见！$"

MatchCall_BattleFrontierStreakText3::
    .string "喂你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n春风得意！\p一个漂亮的{STR_VAR_3}连胜…\n这是个新纪录，对吧？\p我也要努力了！\n以后联系！$"

MatchCall_BattleFrontierStreakText4::
    .string "喂，{PLAYER}{KUN}。\n{STR_VAR_1}在此。我有什么事？\p有传言说\n你在{STR_VAR_2}取得了\l{STR_VAR_3}连胜。\p我也要加油啊。\n再见！$"

MatchCall_BattleFrontierStreakText5::
    .string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n一口气赢了{STR_VAR_3}场？\l真厉害啊！\p我也要继续和宝可梦努力了。\n回见！$"

MatchCall_BattleFrontierStreakText6::
    .string "喂，{PLAYER}{KUN}。\n{STR_VAR_1}在此。你好吗？\p顺便说下，我听说你\n在{STR_VAR_2}一下子赢了{STR_VAR_3}场\l比赛。\p这让我更加专注与\n训练我的队伍了。$"

MatchCall_BattleFrontierStreakText7::
    .string "…呃，{PLAYER}{KUN}？\n{STR_VAR_1}在此…\p哦，对，你现在正在\n{STR_VAR_2}，对吧？\p并且你一下子赢了{STR_VAR_3}场战斗。\p哦，这里有一只稀有的宝可梦！\n我要走了！$"

MatchCall_BattleFrontierStreakText8::
    .string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l我希望你一切都好。\p嗯，那个，那个啥。我听说\n你一下子赢了{STR_VAR_3}场比赛，\l就在{STR_VAR_2}。\p真是让人震惊！\n我希望你能保持下去。$"

MatchCall_BattleFrontierStreakText9::
    .string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}取得了\n{STR_VAR_3}连胜！\p太酷了！\n我也要加油！$"

MatchCall_BattleFrontierStreakText10::
    .string "喂，{PLAYER}{KUN}，你好…\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n一下子赢了{STR_VAR_3}场？\p这真是不容易啊。\n我要努力了。$"

MatchCall_BattleFrontierStreakText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p你已经成为了{STR_VAR_2}的\n恐怖传说？\p你赢了，多少，{STR_VAR_3}场\n还是一口气的？\p你很棒，你。\n我想知道我能赢几场？$"

MatchCall_BattleFrontierStreakText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p有些人在谈论你。\n你真的在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p真的是个传奇啊。\n回见！$"

MatchCall_BattleFrontierStreakText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l我希望你一切都好。\p他们说你在{STR_VAR_2}\n连赢了{STR_VAR_3}场。\p我赞赏你的能力！\n再见了。$"

MatchCall_BattleFrontierStreakText14::
    .string "喂，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你了！\n你真的在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p你真厉害！\n再见！$"

MatchCall_BattleFrontierRecordStreakText1::
    .string "嗨！我是{STR_VAR_1}。\n我听说了！\p我听说你在{STR_VAR_2}\n做得非常出色。\p真是恐怖啊--{STR_VAR_3}连胜？\n再见！$"

MatchCall_BattleFrontierRecordStreakText2::
    .string "你好，我是{STR_VAR_1}！\n我听说你了！\n你真的在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p真的不容易啊！我也要\n努力了！再见$"

MatchCall_BattleFrontierRecordStreakText3::
    .string "喂你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n做得非常出色。\p{STR_VAR_3}连胜…\n是个新纪录吧？\p我也要加油了！\n再见！$"

MatchCall_BattleFrontierRecordStreakText4::
    .string "喂，{PLAYER}{KUN}。\n{STR_VAR_1}在此。什么？\p有传言说\n你在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p我也要加油了！\n再见！$"

MatchCall_BattleFrontierRecordStreakText5::
    .string "嘿，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p你在一个叫{STR_VAR_2}的地方\n连胜了{STR_VAR_3}场？\l真厉害啊！\p我不能落后啊。\n再见！$"

MatchCall_BattleFrontierRecordStreakText6::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。你好吗？\p顺便说下，我听说\n你在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p我不能落后啊。\n再见！$"

MatchCall_BattleFrontierRecordStreakText7::
    .string "…呃，{PLAYER}{KUN}？\n{STR_VAR_1}在此…\p哦，对，你现在正在\n{STR_VAR_2}，对吧？\p并且你一下子赢了{STR_VAR_3}场战斗。\p哦，这里有一只稀有的宝可梦！\n我要走了！$"

MatchCall_BattleFrontierRecordStreakText8::
    .string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切都好。\p嗯，那个，我听说你在\n一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p太震撼了！\n我也要去和我的宝可梦好好锻炼了！$"

MatchCall_BattleFrontierRecordStreakText9::
    .string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}取得了\n{STR_VAR_3}连胜！\p太酷了！\n我也要加油！$"

MatchCall_BattleFrontierRecordStreakText10::
    .string "哦，{PLAYER}{KUN}，你好…\n我是{STR_VAR_1}。\p我听说了！你在{STR_VAR_2}取得了\n{STR_VAR_3}连胜？\p真是不简单啊。\n我也要加油。$"

MatchCall_BattleFrontierRecordStreakText11::
    .string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p你已经成为了{STR_VAR_2}的\n恐怖传说？\p你赢了，多少，{STR_VAR_3}场\n还是一口气赢的？\p你很棒，你。\n我想知道我能赢几场？$"

MatchCall_BattleFrontierRecordStreakText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p有些人在谈论你。\n你真的在一个叫{STR_VAR_2}的地方\l连胜了{STR_VAR_3}场？\p真的是个传奇啊。\n回见！$"

MatchCall_BattleFrontierRecordStreakText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l我希望你一切都好。\p他们说你在{STR_VAR_2}\n连赢了{STR_VAR_3}场。\p我赞赏你的能力！\n再见了。$"

MatchCall_BattleFrontierRecordStreakText14::
    .string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l我听说过你了！\p是不是你在{STR_VAR_2}\n连胜了{STR_VAR_3}场？\p真厉害呀！\n再见！$"

MatchCall_BattleDomeText1::
    .string "嗨！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说过你了！\p你在\n{STR_VAR_2}连续获得了{STR_VAR_3}次冠军？\p真厉害！我也要加油！\n会见！$"

MatchCall_BattleDomeText2::
    .string "你好，我是{STR_VAR_1}！\n我听说过你的！\p他很说你在{STR_VAR_2}\n连赢了{STR_VAR_3}场。\p真厉害！我也能\n成为冠军吗？$"

MatchCall_BattleDomeText3::
    .string "嘿你好，{PLAYER}！\n是我啊，{STR_VAR_1}。\l最近好吗？\p我听说你在{STR_VAR_2}\n连赢了{STR_VAR_2}场！\p再接再厉！\n会见！$"

MatchCall_BattleDomeText4::
    .string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在\n{STR_VAR_2}连续获得了{STR_VAR_3}次冠军？\p看上去你很努力呀。\n再接再厉！$"

MatchCall_BattleDomeText5::
    .string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连赢了{STR_VAR_2}场！\p我也要加油！\n会见！$"

MatchCall_BattleDomeText6::
    .string "嘿，{PLAYER}{KUN}？\n我是{STR_VAR_1}。你还好吗？\p顺便问下\n据说你在{STR_VAR_2}\l赢了{STR_VAR_2}场。\p我也必须训练我的宝可梦，\n在你把我甩开太远之前。$"

MatchCall_BattleDomeText7::
    .string "{PLAYER}{KUN}？\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n连续获得了{STR_VAR_3}次冠军？\p真不得了啊。另外，\n你抓到什么稀有的宝可梦没有？\p哦，这样阿。\n好，再见。$"

MatchCall_BattleDomeText8::
    .string "哦，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l我希望你一切都好。\l哦，那个，那个什么。\p我听说你在{STR_VAR_2}\n连续赢了{STR_VAR_3}场。\p我也要像你一样训练宝可梦。\n再见。$"

MatchCall_BattleDomeText9::
    .string "喂，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在\n{STR_VAR_2}连续赢得了{STR_VAR_3}场比赛！\p真酷啊！\n我也要努力了！$"

MatchCall_BattleDomeText10::
    .string "哦，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}连续赢得了\n{STR_VAR_3}场？\p真是了不起啊。\n我也要努力了。$"

MatchCall_BattleDomeText11::
    .string "哦，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n名声大振？\p你现在已经连续赢了{STR_VAR_3}场\n比赛了？\p我在想我会不会\n成为冠军？\p…不太可能吗？\n好，再见！$"

MatchCall_BattleDomeText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l最近还好吗？\p你在一个叫{STR_VAR_2}的地方\n连续赢了{STR_VAR_3}场？\p真是传奇啊。\n再见！$"

MatchCall_BattleDomeText13::
    .string "喂，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l我希望你一切都好。\p据说你在一个叫{STR_VAR_2}的地方\n连续赢了{STR_VAR_3}场？\p真厉害啊！\n再见。$"

MatchCall_BattleDomeText14::
    .string "喂，你还，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l我听说你了！\p你不是在{STR_VAR_2}\n连赢了{STR_VAR_3}场么？\p真了不起啊！\n再见！$"

MatchCall_BattlePikeText1::
    .string "嗨！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说了！\p你是不是在{STR_VAR_2}\n连赢了{STR_VAR_3}场？\p太惊人了！\n再见！$"

MatchCall_BattlePikeText2::
    .string "你好，我是{STR_VAR_1}！\n我听说你了！\p他们听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间！\p我也要加油阿！\n再见！$"

MatchCall_BattlePikeText3::
    .string "嘿你好，{PLAYER}！\n是我，{STR_VAR_1}。\l一切还好吗？\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间！\p下次要更努力啊！\n以后再见！$"

MatchCall_BattlePikeText4::
    .string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间。\p我也要多多训练我的宝可梦\n不能落后！$"

MatchCall_BattlePikeText5::
    .string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间。\p我也要多多努力！\n回见！$"

MatchCall_BattlePikeText6::
    .string "喂，{PLAYER}{KUN}？\n我是{STR_VAR_1}。你好吗？\p顺便说下，我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间。\p我要多多训练我的宝可梦\n别把我甩的太远。$"

MatchCall_BattlePikeText7::
    .string "{PLAYER}{KUN}？\n{STR_VAR_1}在此。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间？\p真不可思议。\p哦，我看见一只稀有的宝可梦！\n好，再见。$"

MatchCall_BattlePikeText8::
    .string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l我希望你一切都好。\l哦，那个，你都很好啊。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间。\p真是让人震惊！\n我也要像你一样训练宝可梦了。\l再见。$"

MatchCall_BattlePikeText9::
    .string "喂，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间。\p太酷了！\n我也要努力！$"

MatchCall_BattlePikeText10::
    .string "喂，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间？\p真是了不起啊。\n我也要加油了。$"

MatchCall_BattlePikeText11::
    .string "喂，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n名声显赫？\p你通过了，啥，{STR_VAR_3}间房间？\n真是不得了啊。\p我想知道\n我也能成为冠军吗？\p…不可能吗？\n好了，再见！$"

MatchCall_BattlePikeText12::
    .string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间？\p真是不得了啊。\n再见！$"

MatchCall_BattlePikeText13::
    .string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p他们说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间？\p你可真厉害！\n再见。$"

MatchCall_BattlePikeText14::
    .string "喂，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l我听说了！\p不就是你在{STR_VAR_2}\n连续通过了{STR_VAR_3}间房间？\p真是了不起！\n再见！$"

MatchCall_BattlePyramidText1::
    .string "喂！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说了！\p你在{STR_VAR_2}里\n登上了{STR_VAR_3}层？\p真是厉害啊！\n我也该试着挑战一下。$"

MatchCall_BattlePyramidText2::
    .string "你好，我是{STR_VAR_1}！\n我听说你了！\p他们说你在{STR_VAR_2}里\n一共登上了{STR_VAR_3}层？\p真不可思议！\n我也要去训练我的宝可梦了！$"

MatchCall_BattlePyramidText3::
    .string "为你好，{PLAYER}！\n是我，{STR_VAR_1}。\l还好吗？\p我听说你在{STR_VAR_2}里\n登上了{STR_VAR_3}层？\p下次更要努力啊！\n再见！$"

MatchCall_BattlePyramidText4::
    .string "嘿，{PLAYER}{KUN}。\n{STR_VAR_1}在此。\p说你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p我也要努力\n赶上你啊！$"

MatchCall_BattlePyramidText5::
    .string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}里\n登上了第{STR_VAR_3}层？\p我也要努力了！\n再见！$"

MatchCall_BattlePyramidText6::
    .string "喂，{PLAYER}{KUN}？\n{STR_VAR_1}在此。你好吗？\p顺便说下，听说你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层。\p我也要去训练宝可梦，\n否则要被你甩开了。$"

MatchCall_BattlePyramidText7::
    .string "{PLAYER}{KUN}？\n{STR_VAR_1}在此。\p你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p厉害。那里有稀有的\n宝可梦么？\p哦，没有么？\n好的，再见。$"

MatchCall_BattlePyramidText8::
    .string "哦，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l我希望你一切都好。\l嗯，那个，那个啥。\p你在{STR_VAR_2}里\n通过了第{STR_VAR_3}层？\p真是不得了啊！\n我也要像你一样培养我的宝可梦。\l再见。$"

MatchCall_BattlePyramidText9::
    .string "哦，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层！\p太酷了！\n我也要努力！$"

MatchCall_BattlePyramidText10::
    .string "哦，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p真是了不起。\n我也要加油了。$"

MatchCall_BattlePyramidText11::
    .string "喂，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n名震一方？\p你登上了，多少来着，第{STR_VAR_3}层？\n那真是很有点了不起呀。\p我在想我能成为\n冠军吗？\p…基本不可能？\n好，再见！$"

MatchCall_BattlePyramidText12::
    .string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p真是难以置信。\n再见！$"

MatchCall_BattlePyramidText13::
    .string "喂，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l我希望你一切都好。\p你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p你真是活力充沛啊！\n再见了。$"

MatchCall_BattlePyramidText14::
    .string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l我听说你了！\p你在{STR_VAR_2}里\n到达了第{STR_VAR_3}层？\p你真是我的偶像！\n再见了！$"

MatchCall_Text_Mom1::
    .string "妈妈：你们父子两个…\n统统都被宝可梦迷住了。\p宝可梦到底有啥能耐？\p我？\n我喜欢那些宝可梦\l它们每天都帮我干杂活。$"

MatchCall_Text_Mom2::
    .string "妈妈：嗨，{PLAYER}！\n你老爸把自己\l关在橙华市道馆里。\p他偶尔也会回家。\n但是每次从道馆回来\l他都会拼命的吃东西。\p我想，败给你\n对他的自尊心是一个很大的打击！$"

MatchCall_Text_Mom3::
    .string "妈妈：{PLAYER}…\n别为我和房子担心。\p穿上这些风速鞋\n直到它们被穿烂为止！$"

MatchCall_Text_Roxanne1::
    .string "杜娟：哦，你好，{PLAYER}！\p在上次见面以后\n我一直在努力修炼。\p我还需要一点点时间\n来重新开启道馆。\p当我准备好了之后，请来我的道馆\n再战一场吧！$"

MatchCall_Text_Roxanne2::
    .string "杜娟：你是{PLAYER}？\n恭喜你啊！\l我听说你的事了！\p我么，我还再需要一点时间\n开重新开放道馆。\p一切就绪以后，请来我的道馆\n让我们重赛一场吧！$"

MatchCall_Text_Roxanne3::
    .string "杜娟：{PLAYER}！\n我的道馆已经准备好了！\p请在有空的时候到卡那兹市\n来吧！$"

MatchCall_Text_Roxanne4::
    .string "杜娟：在卡那兹市道馆，\n{PLAYER}，\l我们是为了荣誉而战。$"

MatchCall_Text_Brawly1::
    .string "藤树：嘿，在此，{PLAYER}{KUN}！\p我在和你战斗以后\n又学到了不少东西。\p我打算结束我的训练，\n然后重新开放道馆。\p在我重新开启道馆之前\n我还需要点时间做准备。\p如果我能重新开启道馆，\n我希望你能和我们比试比试。$"

MatchCall_Text_Brawly2::
    .string "藤树：嘿，{PLAYER}{KUN}！\n祝贺你！\p关于你英雄事迹的传闻\n已经满天飞了！\p看上去\n我需要更努力的修炼呀。\p我想我还需要一些时间准备\n之后才能重开道馆。\p如果我重开了道馆，\n我希望能挑战你。$"

MatchCall_Text_Brawly3::
    .string "藤树：喂，{PLAYER}{KUN}！\n我的道馆已经准备就绪！\p回武斗镇来吧\n我时刻期待能再挑战你！$"

MatchCall_Text_Brawly4::
    .string "藤树：{PLAYER}{KUN}，我一直都觉得\n和你的战斗真是充满了乐趣！$"

MatchCall_Text_Wattson1::
    .string "铁旋：哦，是你啊！\p你走了之后，我已经\n从新开始了修炼。\p我还需要那么一丁点时间\n来重新开启道馆。\p你洗干净脖子等着吧！\n挖哈哈哈哈！$"

MatchCall_Text_Wattson2::
    .string "铁旋：挖哈哈哈哈！\p你终于做到了，是吧？\n我听说过你的事了！\p看上去我还要再多\n修炼一下。\p我承认我还需要一点点\n时间来重新开启道馆。\p你就等着吧！\n挖哈哈哈！$"

MatchCall_Text_Wattson3::
    .string "铁旋：哦，是你啊！\n我的道馆已经好了！\p来紫堇市吧，随时欢迎！\n挖哈哈哈哈！$"

MatchCall_Text_Wattson4::
    .string "铁旋：哦活活活活！\p和你的战斗总是能让人\n兴奋得发抖！$"

MatchCall_Text_Flannery1::
    .string "亚莎：{PLAYER}…\p当我们战斗的时候，我才\n意识到我多么的不成熟。\p但是事情还没完呢！\p我正在重新进行训练\n这样才能重新开启道馆。\p到时候，{PLAYER}，\n请再来挑战我吧。$"

MatchCall_Text_Flannery2::
    .string "亚莎：你好，{PLAYER}？\n祝贺你！\p有关你成功的消息\n就像火山喷发一样止不住！\p我们的修炼\n十分顺利。\p当我们的道馆就绪之后，\n看看你的对战寻呼，\l我的名字旁边会有标记。$"

MatchCall_Text_Flannery3::
    .string "亚莎：哦，{PLAYER}？\n我们的道馆已经准备好了！\p请来釜炎镇，你可以\n泡泡温泉，顺便还可以决斗！$"

MatchCall_Text_Flannery4::
    .string "亚莎：{PLAYER}…\n当我看见你的训练成果\l越来越好，我很高兴。$"

MatchCall_Text_Winona1::
    .string "娜琪：你好，{PLAYER}！\p多亏了我们的那场战斗，我知道了\n我的弱点在哪里！\p当我重新开启道馆之后，\n我不会再输了！$"

MatchCall_Text_Winona2::
    .string "娜琪：你成功了，{PLAYER}！\p关于你成为冠军的消息\n已经传到了茵郁市！\p不过…下一次你我再战，\n结果应该有所不同了。$"

MatchCall_Text_Winona3::
    .string "娜琪：你是{PLAYER}？\n我们的道馆从新开始运作了！\p我们在茵郁市等你！$"

MatchCall_Text_Winona4::
    .string "娜琪：{PLAYER}…\n虽然我输了，但是我的信心\l绝对不会丧失。\p对，就像你\n从未失去你的梦想一样。$"

MatchCall_Text_TateLiza1::
    .string "枫：哦！你是…\n南：{PLAYER}！\p枫：我们在重新训练…\n南：然后就能重开道馆！\p枫：当我们的道馆就绪之后…\n南：当我们的道馆就绪之后…\p枫：我们的名字旁边会有一个标志…\n南：就在对战寻呼里。$"

MatchCall_Text_TateLiza2::
    .string "枫：{PLAYER}，祝贺你！\n南：{PLAYER}，祝贺你！\p枫：我们两个…\n南：仍在训练！\p枫：不过，再给我们一点时间…\n南：当我们的道馆就绪之后…\p枫：看你的对战寻呼…\n南：我们名字旁会有一个标记。$"

MatchCall_Text_TateLiza3::
    .string "枫：{PLAYER}！\n南：{PLAYER}！\p枫：我们的道馆已经好了！\n南：我们的道馆已经好了！\p枫：请来…\n南：绿岭市看看！$"

MatchCall_Text_TateLiza4::
    .string "枫：{PLAYER}，我们之间的战斗…\n南：真是宝贵的经历。\p枫：真期待能和你…\n南：再战一场！$"

MatchCall_Text_Juan1::
    .string "亚当：嗯…\n{PLAYER}{KUN}…是你吗？\p我们的战斗-\n这让我想起了第一次\l遇到米可利的时候。\p也许你真是个天才\n甚至超越了米可利！$"

MatchCall_Text_Juan2::
    .string "亚当：呼呼…{PLAYER}{KUN}…\n你终于达成了你的目标。\p我当初真的没有\n看错人…\p我希望能再见你一次，\n告诉我你是如何\l取得这样的成功的。$"

MatchCall_Text_Juan3::
    .string "亚当：活活…{PLAYER}{KUN}…\p我们的琉璃市道馆终于\n重开了。\p如果你相见我们，\n我们随时欢迎。$"

MatchCall_Text_Juan4::
    .string "亚当：{PLAYER}{KUN}…\p像最动听的音乐，\n我们的战斗\l撩动了我的心弦…\p每当我闭上双眼，都能看到\n你乘着歌声的翅膀飞翔…$"

MatchCall_Text_Sidney::
    .string "花月：哟，{PLAYER}！\p如果你想跟我再战一场，\n你可以在任何时候\l来宝可梦联盟找我。\p我会等着你的！\n一直！！$"

MatchCall_Text_Phoebe::
    .string "芙蓉：嗨，{PLAYER}！\p什么时候你能\n回来看看呢？\p我想看看\n你和你的宝可梦\l又成长了多少。$"

MatchCall_Text_Glacia::
    .string "波妮：你好，{PLAYER}。\p我想，你还没有因为\n你的力量而自大吧？\p如果你想让你发热的头脑\n稍微冷静一下，就来\l宝可梦联盟吧…$"

MatchCall_Text_Drake::
    .string "源治：这个声音…{PLAYER}，是你吗？？\n听上去很健康啊…\p我知道，\n有一个设施叫做\l对战开拓区，是用来测试\l训练师的能力的。\p不过，如果你想进行\n真正的战斗，那么没有地方比\l宝可梦联盟更合适了！\p你觉得呢，{PLAYER}？$"

MatchCall_Text_Wallace::
    .string "米可利：你好，{PLAYER}{KUN}。\n你见过大吾么？\p他…\n真是神乎奇技阿。\p不过，他的脾气很怪，\n很少战斗。\p他情愿\n寻找珍稀的石头。\p我打保票，他肯定正在\n某个峭壁附近打洞呢。\p不过什么石头才算是珍稀的？\n我能想到的只有陨石了…$"

MatchCall_Text_MayRayquazaCall::
    .string "… … … … … …\n… … … … … 嘟嘟！\p小遥：嗨，{PLAYER}{KUN}！\p我刚才在暮水镇\n附近呢。\p我看见一个巨型绿色宝可梦\n在高空飞翔。\p我…\n我从来没见过这玩意。\p我想知道这是啥啊。\n这是个大发现吧？\p… … … … … …\n… … … … … 咔嚓！$"

MatchCall_Text_BrendanRayquazaCall::
    .string "… … … … … …\n… … … … … 嘟嘟！\p佑树：嗨，{PLAYER}！\n我刚才在暮水镇附近。\p我看见一个巨型绿色宝可梦\n在高空飞翔。\p我从来没见过类似\n东西。\p要是你也看看就好了，\n{PLAYER}。\p… … … … … …\n… … … … … 咔嚓！$"

MatchCall_Text_May1::
    .string "小遥：嗨，{PLAYER}{KUN}！\p哈奇从水手的岗位上退休了，\n但是我常常见到他和宠物\l小皮一起去看海。\p他一定还爱着大海。$"

MatchCall_Text_May2::
    .string "小遥：嗨，{PLAYER}{KUN}！\p你知道有些小镇，比如\n橙华市和武斗镇拥有道馆？\p由于某些原因，凯那\n这样的大港口没有道馆。\p当我们在那里建好道馆之后，\n我会申请做馆主。$"

MatchCall_Text_May3::
    .string "小遥：嗨，{PLAYER}{KUN}！\p你知道一个叫做\n一字斩手的人吗？在卡那兹市？\l他在这里有一幢房子，记得吗？\p很好，我们发现他的\n弟弟住在紫堇市。\p猜猜他是谁？\p… … … … … …\n… … … … … …\p就是那个岩石粉碎者！$"

MatchCall_Text_May4::
    .string "小遥：{PLAYER}{KUN}？\p卡绿隧道…\n之所以这样得名，是因为\l隧道连接了卡那兹市和绿荫镇。$"

MatchCall_Text_May5::
    .string "小遥：{PLAYER}{KUN}，还好吗？\p我正在111号公路呢。\p我准备在一个老太太的房子里\n休息一下。\p她就住在\n沙漠的北边。$"

MatchCall_Text_May6::
    .string "小遥：嗨，{PLAYER}{KUN}！\p你知道沙漠中央的\n幻影之塔吗？\p据说，像幻影一样，\n出现和消失都无法琢磨。\p我希望你能看看。$"

MatchCall_Text_May7::
    .string "小遥：{PLAYER}{KUN}，呀呼！\n我正在119号公路上呢。\p这里有条大河，而且\n经常下雨。\p我湿透了！$"

MatchCall_Text_May8::
    .string "小遥：{PLAYER}{KUN}，嗨。\p送神火山码头是被当作\n纪念死去的宝可梦而存在的。\p结果时，里面有\n很多幽灵系宝可梦！$"

MatchCall_Text_May9::
    .string "小遥：嗨，{PLAYER}{KUN}！\p我想去釜炎镇\n泡温泉。\p但是，在崎岖山路上，\n我撞上了一群丑八怪。\l真扫兴！$"

MatchCall_Text_May10::
    .string "小遥：嗨，{PLAYER}{KUN}！\n看到新闻了吗？\p他们说库斯诺吉馆长在\n潜水远征中\l发现了海底洞窟。$"

MatchCall_Text_May11::
    .string "小遥：嗨，{PLAYER}{KUN}！\n你不觉得这很棒吗？\p即使没有船，\n你也能利用宝可梦的技能\l来越过大海。\p你知道这还不是全部吧？\p有种宝可梦技能能够\n让你潜入深海。$"

MatchCall_Text_May12::
    .string "小遥：嗨，{PLAYER}{KUN}！\n希望一切都好！\p你出海之后\n又没有发现通向彼岸的航路\l被封住了？\p试试看潜下深水\n沿着壕沟前进。\p当你到了对岸之后，\n再浮上水面。容易吧！$"

MatchCall_Text_May13::
    .string "小遥：嗨，{PLAYER}{KUN}！\p怎么样了？\n你正在补完你的宝可梦图鉴？\p我听说有\n上古宝可梦的存在。\l一共有3只！\p我哪怕见到一只才好…$"

MatchCall_Text_May14::
    .string "小遥：{PLAYER}{KUN}！\n我听说了！\p你击败了琉璃市道馆\n馆主？\p这就是说，你的目标\n已经近在咫尺了？$"

MatchCall_Text_May15::
    .string "小遥：离开丰缘的训练师当中，\n没有一个不知道你的，\l{PLAYER}{KUN}！\p我告诉他们，你是我的朋友，\n{PLAYER}{KUN}，\l他们都吓了一跳！$"

MatchCall_Text_Brendan1::
    .string "佑树：嘿，{PLAYER}！\p哈奇从水手的岗位上退休了，\n但是我常常见到他和宠物\l小皮一起去看海。\p我猜想\n他一定爱着大海。$"

MatchCall_Text_Brendan2::
    .string "佑树：嘿，{PLAYER}！\p我弄不懂，为什么橙华市和\n武斗镇这样的小镇都有道馆。\p而像凯那这样的\n大港口却没有道馆。\p当他们在这里建好道馆之后，\n我会申请做馆主。$"

MatchCall_Text_Brendan3::
    .string "佑树：哟，{PLAYER}！\p你知道哪个住在卡那兹市\n叫一字斩手的家伙么？\l他在这里有幢房子，对吧？\p听好，他的弟弟\n就住在紫堇市。\p知道他是谁么？\p… … … … … …\n… … … … … …\p就是那个岩石粉碎者！$"

MatchCall_Text_Brendan4::
    .string "佑树：这声音…{PLAYER}？\p卡绿隧道名称的由来\n是因为它连接了卡那兹市和\l绿荫镇。\p知道了吧？$"

MatchCall_Text_Brendan5::
    .string "佑树：{PLAYER}，咋了？\p嘿我正在111号公路呢。\p我打算在一个老婆婆的家里\n稍作休息，就在沙漠的北边。\p如果你也在，你应该来\n看看她。$"

MatchCall_Text_Brendan6::
    .string "佑树：嘿，{PLAYER}！\p你知道沙漠中的\n幻影之塔么？\p据说，像幻影，塔\n只在某些时候出现。\p想见阿！$"

MatchCall_Text_Brendan7::
    .string "佑树：谁啊？哦，{PLAYER}？\n怎么？我正在119号公路呢。\p这里有条大河，而且\n老是下雨。\p我湿透了！$"

MatchCall_Text_Brendan8::
    .string "佑树：{PLAYER}！\p送神火山码头是作为死去的宝可梦\n的纪念场而存在的。\p说不定\n你面有很多幽灵系宝可梦！$"

MatchCall_Text_Brendan9::
    .string "佑树：你好，{PLAYER}。\p我本来想去釜炎镇\n泡温泉的。\p但是在崎岖山路，我撞上了\n一帮丑陋的家伙。\p真可怕…\n我想他们是火岩队。$"

MatchCall_Text_Brendan10::
    .string "佑树：嗨，{PLAYER}！\n听到新闻了？\p库斯诺吉馆长在\n潜水探险中发现了\l海底洞窟。$"

MatchCall_Text_Brendan11::
    .string "佑树：你好，{PLAYER}！\n你不觉得这很棒吗？\p即使没有船，\n你也能利用宝可梦技能\l来越过大海。\p你知道这还不是全部吧？\n有种宝可梦技能能够让你潜入深海呢。\p宝可梦无所不能啊！$"

MatchCall_Text_Brendan12::
    .string "佑树：嗨，{PLAYER}！\n希望一切都好！\p你出海之后\n有没有发现通向彼岸的航路被封住了？？\p试试看潜下深水\n沿着壕沟前进。\p当你到了对岸之后，\n再浮上水面。容易吧！$"

MatchCall_Text_Brendan13::
    .string "佑树：你好啊，{PLAYER}！\p怎么样了？还在在补完你的？\n宝可梦图鉴？\p我听说某些地方有\n上古宝可梦的存在。。\l一共三只哦！\p我哪怕抓到一只才好…$"

MatchCall_Text_Brendan14::
    .string "佑树：{PLAYER}！\n我听说了！\p你打倒了琉璃市道馆的\n馆主？真厉害！\p你已经很接近那个了！$"

MatchCall_Text_Brendan15::
    .string "佑树：在离开丰缘的\n当中，没有一个不知道\l你的，{PLAYER}！\p我告诉他们你是我的朋友\n哈哈，{PLAYER}，他们都\l羡慕死了！$"

MatchCall_Text_Wally1::
    .string "小光：哦，{PLAYER}！\p我已经变得更健康\n更结实。\p我希望能变成你这样的\n训练师，{PLAYER}！$"

MatchCall_Text_Wally2::
    .string "小光：{PLAYER}，你好！\p当卡绿隧道打通\n之后，小亮非常高兴！$"

MatchCall_Text_Wally3::
    .string "小光：哦，{PLAYER}！\p我离开了我叔叔家，\n离开了绿荫镇，没有告诉别人。\p他会不会为我担心呢…\p{PLAYER}，你知道我的感受，\n对不对？$"

MatchCall_Text_Wally4::
    .string "小光：{PLAYER}？\n是我呀，小光！\p训练师的世界多么美妙！\p当我带着我的宝可梦，\n所有人都向我问好！\p好像他们都是\n被宝可梦联结起来了一样！$"

MatchCall_Text_Wally5::
    .string "小光：{PLAYER}？太不可思议了！\n还记得我们抓的拉鲁拉丝吗？\l他进化了，{PLAYER}！\p我大概是个天才…\p哦，我觉得我的头还\n不够大！\p不过，值得表扬的应该是宝可梦\n才对！$"

MatchCall_Text_Wally6::
    .string "… … … … … …\n… … … … … …\p小光好像\n不在口袋领航员的服务区…$"

MatchCall_Text_Wally7::
    .string "小光：哦，{PLAYER}！\p见到你之前，我很少\n离开家…\p但现在，我正在和属于我的\n宝可梦一起冒险呢…\p{PLAYER}…\n谢谢你…$"

MatchCall_Text_Scott1::
    .string "亚希达：嗨，{PLAYER}{KUN}！\p你知道宝可梦能在\n任何地方被找到吗？\p在山里，海里，\n在草丛里？\p像宝可梦一样，\n训练师也是满地都是。\p我也只好到处飘泊了。\n忙，真忙！$"

MatchCall_Text_Scott2::
    .string "亚希达：我正在119号公路上呢。\n这里到处都是训练师！\p简直和这里的\n杂草数量有的一拼。\p一句话，\n在这里行动真是麻烦！$"

MatchCall_Text_Scott3::
    .string "亚希达：嗨，嗨，{PLAYER}{KUN}！\p你有没有登上过\n送神火山码头？\p那个地方是作为死去宝可梦\n的纪念场而存在的。\p每一个训练师\n一生至少应该登顶一次。$"

MatchCall_Text_Scott4::
    .string "亚希达：嗨，{PLAYER}{KUN}！\p我听说那些奇怪\n的帮会在为非作歹。\p火岩队和水舰队，\n不出我的所料。\p我就猜到他们当中\n会有一些老练的训练师。\p…但是他们竟然如此狂暴…$"

MatchCall_Text_Scott5::
    .string "亚希达：哦，嗨，{PLAYER}{KUN}。\p在海底可能会有\n强大的训练师吗？\p我不能亲自一探究竟。\n首先我不会游泳。\l再说，我没有宝可梦啊…$"

MatchCall_Text_Scott6::
    .string "亚希达：嗨，嗨，{PLAYER}{KUN}！\p你知道吗？\n当你收集到了所有的道馆徽章，\l你就能够挑战宝可梦联盟。\p以你的才能，成为一个\n冠军，并不是天方夜谭。\p但是你要知道。\n这还不是全部。\p现在，\n这就是我想对你说的。\p我要让你有一个\n奋斗的目标。\p那就是，\n在宝可梦联盟中开启一条胜利之路，\l直通荣誉殿堂！$"

MatchCall_Text_Scott7::
    .string "… … … … … …\n… … … … … …\p亚希达看上去\n不在口袋领航员的服务区…$"

MatchCall_Text_Norman1::
    .string "爸爸：在卡那兹市，有一个\n被称作一字斩手的\l男人。\p如果你在那个地方，你\n应该来看看。$"

MatchCall_Text_Norman2::
    .string "爸爸：嗯…一点一滴，\n但的确是与时俱进，\l你是越来越棒了，{PLAYER}。\p你越强，\n你才能超越你的母亲\l和我…\p这种心情真是复杂啊。$"

MatchCall_Text_Norman3::
    .string "爸爸：知道了…\n你已经收集了4个道馆徽章…\p已经无法避免了。\n我会遵守之前的承诺来和你战斗。\p来吧。\n我们会一直等你！$"

MatchCall_Text_Norman4::
    .string "爸爸：{PLAYER}！你最好经常\n去看看你的母亲。\p我得呆在这里\n再加倍强化我的训练。\p战斗之道，深远\n且没有回头路！$"

MatchCall_Text_Norman5::
    .string "爸爸：哦，嗨，{PLAYER}！\p那是什么？火岩徽章？\n我不知道那是什么东西。\p但是从名字上看，这可能\n和火山有关！$"

MatchCall_Text_Norman6::
    .string "爸爸：嘿呀！喝哈！呜哇！\p…哦？{PLAYER}！\p你在我训练宝可梦的中途\n给我打电话做什么！$"

MatchCall_Text_Norman7::
    .string "爸爸：{PLAYER}！\p谁能够想到\n你会成为宝可梦联盟冠军…\p好吧！\n我不会落后的！$"

MatchCall_Text_Norman8::
    .string "爸爸：嗯？{PLAYER}？\n是时候了！\p现在，我要\n挑战你。\p我在橙华市道馆等你。\n随时都可以来！$"

MatchCall_Text_Norman9::
    .string "爸爸：…太了不起了，{PLAYER}。\n你的潜力究竟有多少？$"

MatchCall_Text_Steven1::
    .string "大吾：嗨，{PLAYER}{KUN}！\p你已经到了紫堇市\n了么？\p你应该去自行车商店看看\n买一辆马赫自行车。\p然后，去彻底探索一下岩石\n洞窟吧。\p你会在那里\n有新发现的。$"

MatchCall_Text_Steven2::
    .string "大吾：嗨，{PLAYER}{KUN}！\p目前我已经遇到过了\n各种各样的训练师。\p你虽然也是其中的一个\n但是却与众不同。$"

MatchCall_Text_Steven3::
    .string "大吾：嗨，{PLAYER}{KUN}！\p当你和你的宝可梦一起冒险的时候，\n你在想些什么呢？\p你有想让它们变成\n强大的伙伴么？\p你把他们当作\n有趣的旅伴么？\p你的想法不同\n你的旅程也会发生极大的改变。$"

MatchCall_Text_Steven4::
    .string "大吾：喂？\n{PLAYER}{KUN}？\p我在宇宙中心里\n碰到了一些小麻烦。\p抱歉，不能再说了。\n再见！$"

MatchCall_Text_Steven5::
    .string "大吾：哦！\n{PLAYER}{KUN}！\p没必要多说了。\n再说也是浪费时间。\p你必须相信你自己\n做出正确的选择。$"

MatchCall_Text_Steven6::
    .string "… … … … … …\p大吾似乎没有接\n电话…$"

MatchCall_Text_Steven7::
    .string "大吾：{PLAYER}{KUN}… 祝贺你\n你进入了荣誉殿堂。\p… … … … … …\n… … … … … …\p我希望能在别处 \n再见你！$"

MatchCall_Text_BirchRegisterCall::
    .string "小田卷博士：哦，{PLAYER}{KUN}！\n我已经听说你了！\p看起来你的口袋领航员已经\n经过了对战寻呼的升级。\p好，我也应该注册一下！\p这样，我可以检查你的\n宝可梦图鉴！在你不参加\l战斗的时候也可以。\p… … … … … …$"

MatchCall_Text_RegisteredBirch::
    .string "将小田卷博士的信息\n登录进口袋领航员。$"

MatchCall_Text_UnusedProfBirch::
    .string "小田卷博士：当同时拥有宝可梦图鉴\n和口袋领航员时，学着如何让\l宝可梦变得更快乐，怎么样？$"

MatchCall_Text_MrStone1::
    .string "兹伏奇：哦？{PLAYER}{KUN}！\p既然你给我打电话，那说明\n口袋领航员工作很正常！\p其他人的信息也可以登录，\n试着联系他们把！\p好！好！\n你看上去很开心呀！\p嗯…\n我是怎么知道的？\p因为我从办公室的窗户里\n正看着你呢！\p哇哈哈！\n回头见！$"

MatchCall_Text_MrStone2::
    .string "兹伏奇：哦？{PLAYER}{KUN}！\p出了什么事？你忘了\n我托付给你的小差事吗？\p我想请你帮我送信给\n住在武斗镇的大吾。\p然后，把那个包裹送给\n住在凯那的库斯诺吉馆长。\p你记住了吗？\p现在，作为一个繁忙的董事长，\n我要挂了！再见！$"

MatchCall_Text_MrStone3::
    .string "兹伏奇：哦！{PLAYER}{KUN}！\p啊，你已经见过大吾了！\n我得给你报酬！\p等你再见到卡那兹市之后，\n来我的办公室找我。\p我等你！$"

MatchCall_Text_MrStone4::
    .string "兹伏奇：哦！{PLAYER}{KUN}！\p你知道得文\n正在挖掘卡绿隧道吗？\p我们必须阻止他\n才能保护那里的宝可梦。\p这是不是明智的行为，说实话。\p让宝可梦平静的生活\n比人类自己的利益\l可是重要的多阿。$"

MatchCall_Text_MrStone5::
    .string "兹伏奇：喂，喂，{PLAYER}{KUN}！\p我听从橙华市来的人说\n你是千里的孩子！\p果然是\n虎父无犬子！$"

MatchCall_Text_MrStone6::
    .string "兹伏奇：请问你是谁？\p你和你的父亲战斗\n最后战胜了他？\p太令人吃惊了！\p我从没想过能交到\n你这样的朋友！哇哈哈！$"

MatchCall_Text_MrStone7::
    .string "你好！\n我是得文职员…\l哦，你好，{PLAYER}！\p我们的董事长刚刚\n还在这里的，但是他已经出去了。\p我们的董事长是很忙的，但是你\n看上去一样忙啊，{PLAYER}。$"

MatchCall_Text_MrStone8::
    .string "…啊？…谁谁？\p古拉…什么？…顿？\p断断续续的…\n…听不清…\p沙沙沙…$"

MatchCall_Text_MrStone9::
    .string "…啊？…谁谁？\p海底…是吗？…洞窟…？\p怎么断断续续的…\n…听不见…\p嘶嘶嘶嘶…$"

MatchCall_Text_MrStone10::
    .string "兹伏奇：{PLAYER}{KUN}！是我！\p你明显已经事务缠身，\n但是我，同样很忙，\l却忙得没有头绪！\p无论如何，\n我希望你能在自己选的路上走下去。\p我会站在你这边的！\n保重！$"

MatchCall_Text_MrStone11::
    .string "兹伏奇：… … … … … …\n你真的是{PLAYER}{KUN}？\p你的声音充满了自信，\n我已经认不出来了！\p恩！你一定要来得文看看\n随时可以！$"
