@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
    .string " 非常漂亮！$"

GiddyText_SoDarling::
    .string " 太迷人了！$"

GiddyText_SoRelaxed::
    .string " 太悠闲了！$"

GiddyText_SoSunny::
    .string " 太愉快了！$"

GiddyText_SoDesirable::
    .string " 太合意的了！$"

GiddyText_SoExciting::
    .string " 太令人激动！$"

GiddyText_SoAmusing::
    .string " 太有意思了！$"

GiddyText_SoMagical::
    .string " 太不可思议！$"

GiddyText_Is::
    .string " 是$"

GiddyText_DontYouAgree::
    .string "\n你同意吗？$"

GiddyText_ISoWantToGoOnAVacation::
    .string "我很想去旅行。\n你知道什么好去处么？$"

GiddyText_IBoughtCrayonsWith120Colors::
    .string "我买了一套120色的蜡笔！\n你不觉得很棒么？$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
    .string "你不觉得，\n漂浮在一片泡泡云上很舒服么？$"

GiddyText_WhenYouWriteOnASandyBeach::
    .string "你在沙滩上写好字，\n不久就会被冲掉的。真扫兴。$"

GiddyText_WhatsTheBottomOfTheSeaLike::
    .string "海底是个什么样子？\n我真想去一次，一次就好！$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
    .string "当你看到夕阳的时候，\n是不是会想回家？$"

GiddyText_LyingBackInTheGreenGrass::
    .string "往草地上这么一躺…\n哦，太，太棒了！$"

GiddyText_SecretBasesAreSoWonderful::
    .string "秘密基地真是太棒了！\n你不觉得刺激么？$"
