MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce::
    .string "这个技能只能教你一次\n准备好了吗？$"

MoveTutor_Text_SwaggerTeach::
    .string "嗨！看我的宝可梦多完美！\n它比其它的宝可梦更酷！\p当会长严厉训斥我的时候\n我总是像这样吹牛\l来蒙混过关。\p这会使我们的行动不协调。\p如果你愿意，我会教你的1只宝可梦\n学习虚张声势。$"

MoveTutor_Text_SwaggerDeclined::
    .string "哎？你不能进入\n状态？$"

MoveTutor_Text_SwaggerWhichMon::
    .string "很好，想让哪只宝可梦\n学习虚张声势？$"

MoveTutor_Text_SwaggerTaught::
    .string "我今后不会再吹嘘\n我的宝可梦了。$"

MoveTutor_Text_RolloutTeach::
    .string "你知道怎样沿着一个方向\n从这儿走出很长的距离\l而不变换方向吗？\p我也许能\n这样做。\p你认为你的宝可梦也\n很想滚动，对吗？\p如果你想学滚动\n我可以教你。$"

MoveTutor_Text_RolloutDeclined::
    .string "你不要害羞。\n让我们滚起来！$"

MoveTutor_Text_RolloutWhichMon::
    .string "哦呵呵，当然！你的宝可梦\n变得像我一样就更出色了。$"

MoveTutor_Text_RolloutTaught::
    .string "在草里打滚使我\n非常快乐。来吧，让我们滚起来！$"

MoveTutor_Text_FuryCutterTeach::
    .string "这是一个你连续使用\n就会变得更强壮的技能。\p这是一个虫系的技能，并且\n是很酷的技能。\p这个技能叫做连续切。\n想让我教你的宝可梦吗？$"

MoveTutor_Text_FuryCutterDeclined::
    .string "我们是不可能融洽相处的。$"

MoveTutor_Text_FuryCutterWhichMon::
    .string "耶！\n把要学习的宝可梦交给我。$"

MoveTutor_Text_FuryCutterTaught::
    .string "当我连续击中对手时\n我会觉得很兴奋！$"

MoveTutor_MimicTeach::
    .string "啊，孩子！\p我也是个小孩子，但我在这个镇\n模仿大人们的\l言谈举止。\p你说什么，小朋友？\n如果我能教你模仿\l你就能承认我？$"

MoveTutor_MimicDeclined::
    .string "嘘！我要让你的宝可梦\n学会模仿！$"

MoveTutor_Text_MimicWhichMon::
    .string "噗噗！我当然能！\n让我看看你想要\l学会技能的宝可梦。$"

MoveTutor_Text_MimicTaught::
    .string "模仿是个伟大而深奥的技能。\p你能像我一样\n运用自如吗…？$"

MoveTutor_Text_MetronomeTeach::
    .string "我想要各种各样的事情！\n但是我把钱都花光了…\p你难道不想在你摇动手指时\n给你带来好运\l使你得到很多钱？\p如果你想，我能让你的宝可梦\n学会摇手指。\p前没有出现，但你的宝可梦\n将摇动手指。不是吗？$"

MoveTutor_Text_MetronomeDeclined::
    .string "好的。等你改变主意了\n再来找我。$"

MoveTutor_Text_MetronomeWhichMon::
    .string "好的！我来教你！\n想让哪只宝可梦学习？$"

MoveTutor_Text_MetronomeTaught::
    .string "当宝可梦使用\n摇手指时，各种各样的好事情\l都会发生。\p我们能够使用它\n是很棒的，对不对？$"

MoveTutor_Text_SleepTalkTeach::
    .string "嗯！我的妻子依靠觉醒\n力量激发潜能。\p她正好要像我一样打个盹，\n并且梦话。\p我能让你的宝可梦\n学会梦话。有兴趣吗？$"

MoveTutor_Text_SleepTalkDeclined::
    .string "噢，好，好。你也想用\n催醒来激发潜能…$"

MoveTutor_Text_SleepTalkWhichMon::
    .string "啊，多有眼光的孩子呀！\n你想让我教哪只宝可梦？$"

MoveTutor_Text_SleepTalkTaught::
    .string "我从来都弄不清楚老婆那\n硬币把戏究竟是怎么一回事。\p要是从梦话中知道点什么\n那就太棒了。$"

MoveTutor_Text_SubstituteTeach::
    .string "当我在屋顶上看着\n这广大的世界时…\p我在想如果这个世界\n不只有一个我那该多有趣啊\l所以我喜欢各种各样的生命。\p当然这是不可能的。\n嘿嘿…\p我明白了！\n你想让你的宝可梦学习替身吗？$"

MoveTutor_Text_SubstituteDeclined::
    .string "噢，不？\p宝可梦能将自己本身\n复制出来，你知道的。$"

MoveTutor_Text_SubstituteWhichMon::
    .string "嘿嘿…\n你想让哪只宝可梦\l学会替身？$"

MoveTutor_Text_SubstituteTaught::
    .string "我们人类更应该极度\n珍惜我们的生命！\p我希望你也走上这条路！$"

MoveTutor_Text_DynamicPunchTeach::
    .string "我做不到！\p我完全绝望了！\p我是一名格斗系训练师，\n所以无论我怎么努力尝试\l也不能在绿岭市道馆获胜！\p啊啊啊啊！打！打！打！\n打！打！打！\p什么，在那边看不到我！\n我只能在地面攻击！\p你想让我教你的\n宝可梦学习爆裂拳？$"

MoveTutor_Text_DynamicPunchDeclined::
    .string "该死！连你也来嘲笑我？\n打！打！打！$"

MoveTutor_Text_DynamicPunchWhichMon::
    .string "什么？你想学？你真是个好人啊！\n想要我教哪只宝可梦？$"

MoveTutor_Text_DynamicPunchTaught::
    .string "我希望你能用爆裂拳\n在绿岭市道馆获胜！$"

MoveTutor_Text_DoubleEdgeTeach::
    .string "啊…\p琉璃市道馆馆主确实\n特别可爱。\p但这也意味着我会有很多\n被他吸引的竞争对手。\p他用舍身一击引起别人的注意。\n可他注意不到我。\p那么，让我教你的宝可梦\n学习舍身一击！$"

MoveTutor_Text_DoubleEdgeDeclined::
    .string "噢…\n即使你拒绝我…$"

MoveTutor_Text_DoubleEdgeWhichMon::
    .string "好的，你希望哪只宝可梦\n能学会舍身一击？$"

MoveTutor_Text_DoubleEdgeTaught::
    .string "我不再为爱而活着！\n我要更加坚强！$"

MoveTutor_Text_ExplosionTeach::
    .string "笨蛋，我根本就没打算\n一直呆在这乡下。\p你们瞧着吧，总有一天\n我会离开乡下去大干一番。\p如果你偶然听到的话，我会很乐意\n教你的宝可梦学会大爆炸！$"

MoveTutor_Text_ExplosionDeclined::
    .string "怎么？你拒绝我是因为\n我住在乡下？$"

MoveTutor_Text_ExplosionWhichMon::
    .string "好的！这是大爆炸！\n哪只宝可梦要学？$"

MoveTutor_Text_ExplosionTaught::
    .string "长时间以来，我一直在教宝可梦\n如何使用大爆炸，但是\l我的大爆炸会引起火灾…\p也许这是个深渊，\n但我宁愿留在这…$"
