gText_ObtainedTheItem::
    .string "得到了{STR_VAR_2}！$"

gText_TheBagIsFull::
    .string "背包满了…$"

gText_PutItemInPocket::
    .string "{PLAYER}把{STR_VAR_2}放进了\n{STR_VAR_3}口袋。$"

gText_PlayerFoundOneItem::
    .string "{PLAYER}发现了{STR_VAR_2}！$"

gText_TooBadBagIsFull::
    .string "糟糕！\n背包满了…$"

gText_PlayerPutItemInBag::
    .string "{PLAYER}把{STR_VAR_2}\n放进了背包。$"

gText_ObtainedTheDecor::
    .string "得到了{STR_VAR_2}！$"

gText_NoRoomLeftForAnother::
    .string "糟糕！没有空间再放\n一个{STR_VAR_2}了…$"

gText_TheDecorWasTransferredToThePC::
    .string "{STR_VAR_2}传进了\n电脑里。$"
