gText_WouldYouLikeToRestYourPkmn::
    .string "你好，\n欢迎来到宝可梦中心，\p我们可以为疲劳的\n宝可梦恢复体力。\p要让你的宝可梦休息一下吗？$"

gText_IllTakeYourPkmn::
    .string "好的，\n你的宝可梦暂时由我保管。$"

gText_RestoredPkmnToFullHealth::
    .string "久等了，\n宝可梦的体力都恢复了。$"

gText_WeHopeToSeeYouAgain::
    .string "欢迎下次再来！$"

gText_WelcomeCutShort::
    .string "你好，\n欢迎来到宝可梦中心，\p我们可以为疲劳的\n宝可梦恢复体力。\p你想要…$"

gText_NoticesGoldCard::
    .string "那-那张卡片…\n莫非是…金卡？！\p啊，多么漂亮的金色！\n上面的4颗星星都在闪闪发光！\p我曾经见过几个拥有银卡\n的训练师，但是，{PLAYER}，\l你是我见过的第一个拥有\l金卡的训练师！\p好的，{PLAYER}，能为你\n保管宝可梦是我的荣幸！$"

gText_YouWantTheUsual::
    .string "很高兴见到你，{PLAYER}！\n还像往常一样，是吗？$"

gText_IllTakeYourPkmn2::
    .string "好的，你的宝可梦\n暂时由我保管。$"

gText_ThankYouForWaiting::
    .string "久等了。$"

gText_WeHopeToSeeYouAgain2::
    .string "欢迎下次再来！$"
