gBirchDexRatingText_AreYouCurious::
    .string "小田卷博士：啊，{PLAYER}{KUN}！\p你想知道你的宝可梦图鉴\n是什么水平吗？$"

gBirchDexRatingText_Cancel::
    .string "嗯，你收集的宝可梦还不够多，\n没什么太大的价值啊。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
    .string "唔唔…\p见过了{STR_VAR_1}只宝可梦，\n抓到了{STR_VAR_2}只宝可梦…$"

gBirchDexRatingText_LessThan10::
    .string "多去草丛里转转，\n仔细寻找宝可梦吧。$"

gBirchDexRatingText_LessThan20::
    .string "看来你已经掌握诀窍了，\n但是从现在开始，收集将越来越困难。$"

gBirchDexRatingText_LessThan30::
    .string "有些宝可梦只在\n特定的地域出现，\l你必须坚持去寻找。$"

gBirchDexRatingText_LessThan40::
    .string "啊，现在看上去比较\n像一个宝可梦图鉴了，\l但还有很大的发展空间。$"

gBirchDexRatingText_LessThan50::
    .string "看起来挺好的，\n继续加油吧。$"

gBirchDexRatingText_LessThan60::
    .string "你用过钓竿吗？\n海里有很多宝可梦的。$"

gBirchDexRatingText_LessThan70::
    .string "除了捕捉宝可梦，\n让它们进化也是个不错的主意。$"

gBirchDexRatingText_LessThan80::
    .string "看着它，我就想说，\n真是不错的宝可梦图鉴！$"

gBirchDexRatingText_LessThan90::
    .string "已经收集这么多了…\n你一定有这方面的天赋！$"

gBirchDexRatingText_LessThan100::
    .string "你去过野生原野区了吗？\p听说有些宝可梦\n只有在那里才能抓到。$"

gBirchDexRatingText_LessThan110::
    .string "已经超过100种了，\n真棒的宝可梦图鉴！$"

gBirchDexRatingText_LessThan120::
    .string "使用岩石粉碎也有可能\n找到宝可梦哦。$"

gBirchDexRatingText_LessThan130::
    .string "你可以和其他人交换\n来得到更多的宝可梦。$"

gBirchDexRatingText_LessThan140::
    .string "听说有些宝可梦如果非常\n喜欢自己的训练师，\l它们就会进化。$"

gBirchDexRatingText_LessThan150::
    .string "没想到丰缘地区\n会有这么宝可梦种类。$"

gBirchDexRatingText_LessThan160::
    .string "有的时候宝可梦们会\n成群结队地出现，\l不要错过这样的机会。$"

gBirchDexRatingText_LessThan170::
    .string "看了你的宝可梦图鉴，\n基本就可以了解丰缘地区的\l宝可梦的情况了。$"

gBirchDexRatingText_LessThan180::
    .string "要我说，你已经可以\n被称作宝可梦专家了，\l而且是个优秀的专家！$"

gBirchDexRatingText_LessThan190::
    .string "有了这么完整的宝可梦图鉴，\n你可以成为一个真正的专家了！$"

gBirchDexRatingText_LessThan200::
    .string "我有很强烈的预感，\n你的宝可梦图鉴很快就能完成了！$"

gBirchDexRatingText_DexCompleted::
    .string "恭喜你！\n你做成了完美的宝可梦图鉴！$"

gBirchDexRatingText_OnANationwideBasis::
    .string "唔唔…\n从全国来看…\p见过了{STR_VAR_1}只宝可梦，\n抓到了{STR_VAR_2}只宝可梦…$"
