Questionnaire_Text_FillOut::
    .string "我们有一张问卷调查，\n您愿意填一下吗？$"

Questionnaire_Text_ThankYou::
    .string "谢谢您抽出时间来\n填写我们的调查表，\p您的反馈将成为\n我们的参考。$"

Questionnaire_Text_YouKnowThoseWordsGift::
    .string "啊，你好！\n你认识这些字吗？\p那么说你一定知道\n关于神秘礼物的事情了。\p从现在起，你一定会\n收到神秘礼物！$"

Questionnaire_Text_YouCanAccessMysteryGift::
    .string "你保存游戏的时候，就可以\n连接到神秘礼物。$"

Questionnaire_Text_YouKnowThoseWordsEvent::
    .string "啊，你好！\n你认识这些字吗？\p那么说你一定知道\n关于神秘事件的事情了。$"

Questionnaire_Text_YouCanAccessMysteryEvent::
    .string "你保存游戏的时候，就可以\n连接到神秘事件。$"

MysteryGift_Text_TheresATicketForYou::
    .string "谢谢使用神秘\n事件系统。\p你是{PLAYER}吧，\n这是给你的票。$"

MysteryGift_Text_TryUsingItAtLilycovePort::
    .string "这个可以在\n水静市的港口使用。\p不如去试试会\n到什么地方？$"
