	.align 2
gText_ConfirmSave::
    .string "要保存游戏进度吗？$"

gText_AlreadySavedFile::
    .string "已存在记录数据。\n覆盖原有进度吗？$"

gText_SavingDontTurnOff::
    .string "保存中…\n请不要关闭电源。$"

gText_PlayerSavedGame::
    .string "{PLAYER}已保存进度。$"

gText_DifferentSaveFile::
    .string "警告！\p检测到另一个数据\n已被保存。\p如果保存进度，另一个数据的\n冒险进度，包括物品和宝可梦，\l将会完全丢失。\p你确定要保存游戏进度\n并将原有的数据覆盖吗？$"

gText_SaveError::
    .string "保存失败。\p请换成\n备份进度。$"

gText_SavingDontTurnOffPower::
    .string "保存中…\n请不要关闭电源。$"
