ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere::
    .string "你要向深处去吗？\p那么帮我收集一些浅水盐\n和浅水贝壳怎么样？\p如果有足够的材料的话，\n我可以帮你制作点好东西。$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells::
    .string "如果浅水盐和\n浅水贝壳各有四个的话，\l我就能制作贝壳之铃…\p原材料每天都可以采到。$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell::
    .string "啊，是浅水盐和浅水贝壳！\n数量足够了！\p想要把它们\n做成贝壳之铃吗？$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway::
    .string "好的，我马上帮你\n做贝壳之铃。\p… … … … … … … …\n… … … … … … … …\p好了！做完了！$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell::
    .string "把这个让宝可梦带上的话，\n宝可梦肯定会喜欢上它的。\p啊，贝壳之铃发出的乐声…\n那是多么美妙！\p原料每天都能采到原，\n想要的话我还可以做更多。$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell::
    .string "哎…是吗…\n真想做一个贝壳之铃啊…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag::
    .string "如果我做好了的话\n你的背包里就没有空间了，\p腾出些地方再回来吧。$"

ShoalCave_Text_WasShoalSaltNowNothing::
    .string "这儿原来有浅水盐，\n但现在什么也没有了。$"

ShoalCave_Text_WasShoallShellNowNothing::
    .string "这儿原来有浅水贝壳，\n但现在什么也没有了。$"
