gTrickHouse_Mechadoll_Oddish::
    .string "走路草$"

gTrickHouse_Mechadoll_Poochyena::
    .string "土狼犬$"

gTrickHouse_Mechadoll_Taillow::
    .string "傲骨燕$"

gTrickHouse_Mechadoll_Azurill::
    .string "露力丽$"

gTrickHouse_Mechadoll_Lotad::
    .string "LOTAD$"

gTrickHouse_Mechadoll_Wingull::
    .string "长翅鸥$"

gTrickHouse_Mechadoll_Dustox::
    .string "毒粉蛾$"

gTrickHouse_Mechadoll_Zubat::
    .string "超音蝠$"

gTrickHouse_Mechadoll_Nincada::
    .string "$"

gTrickHouse_Mechadoll_Ralts::
    .string "RALTS$"

gTrickHouse_Mechadoll_Zigzagoon::
    .string "蛇纹熊$"

gTrickHouse_Mechadoll_Slakoth::
    .string "懒人翁$"

gTrickHouse_Mechadoll_Poochyena2::
    .string "土狼犬$"

gTrickHouse_Mechadoll_Shroomish::
    .string "蘑蘑菇$"

gTrickHouse_Mechadoll_Zigzagoon2::
    .string "蛇纹熊$"

gTrickHouse_Mechadoll_Poochyena3::
    .string "土狼犬$"

gTrickHouse_Mechadoll_Zubat2::
    .string "超音蝠利牙鱼$"

gTrickHouse_Mechadoll_Carvanha::
    .string "利牙鱼$"

gTrickHouse_Mechadoll_BurnHeal::
    .string "灼伤药$"

gTrickHouse_Mechadoll_HarborMail::
    .string "港口信件$"

gTrickHouse_Mechadoll_SamePrice::
    .string "同等价钱$"

gTrickHouse_Mechadoll_60Yen::
    .string "$60$"

gTrickHouse_Mechadoll_55Yen::
    .string "$55$"

gTrickHouse_Mechadoll_Nothing::
    .string "啥都没有他们更昂贵。$"

gTrickHouse_Mechadoll_CostMore::
    .string "他们更昂贵。$"

gTrickHouse_Mechadoll_CostLess::
    .string "他们更便宜。$"

gTrickHouse_Mechadoll_SamePrice2::
    .string "同等价钱$"

gTrickHouse_Mechadoll_Male::
    .string "雄性$"

gTrickHouse_Mechadoll_Female::
    .string "雌性$"

gTrickHouse_Mechadoll_Neither::
    .string "都不是$"

gTrickHouse_Mechadoll_ElderlyMen::
    .string "年轻男士$"

gTrickHouse_Mechadoll_ElderlyLadies::
    .string "年轻女士$"

gTrickHouse_Mechadoll_SameNumber::
    .string "一样大$"

gTrickHouse_Mechadoll_None::
    .string "没有$"

gTrickHouse_Mechadoll_One::
    .string "1$"

gTrickHouse_Mechadoll_Two::
    .string "2$"

gTrickHouse_Mechadoll_Two2::
    .string "2$"

gTrickHouse_Mechadoll_Three::
    .string "3$"

gTrickHouse_Mechadoll_Four::
    .string "4$"

gTrickHouse_Mechadoll_Six::
    .string "6$"

gTrickHouse_Mechadoll_Seven::
    .string "7$"

gTrickHouse_Mechadoll_Eight::
    .string "8$"

gTrickHouse_Mechadoll_Six2::
    .string "6$"

gTrickHouse_Mechadoll_Seven2::
    .string "7$"

gTrickHouse_Mechadoll_Eight2::
    .string "8$"
