LilycoveCity_ContestLobby_Text_InterviewRequest::
    .string "你好！你参加过华丽大赛\n是吗？\l你能说些华丽大赛的事吗。\p我是一个记者。我正在做\n一个华丽大赛的节目。\p如果可以的话我问你几个问题\n你能回答我吗？$"

LilycoveCity_ContestLobby_Text_DescribeContest::
    .string "你愿意？\n真是太感谢了。\p简单的说，认为你参加的\n比赛怎么样？$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX::
    .string "哦我知道了。\n听起来非常的有教育意义。\p你对现在的华丽大赛\n似乎很满意。\p我还有一个问题。\p当你听到“{STR_VAR_2}，”\n你是怎么想的？$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview::
    .string "原来是这样！\p这就是你是怎么看待\n“{STR_VAR_2}”的啊。\p谢谢了！\n你给了我一些启发。\p我想我现在能够写一篇\n关于华丽大赛的报道了。\p也许，只的也许\n节目会做到电视上。\l希望你能看到他！$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe::
    .string "哦真糟糕…\p好吧，如果你能想出一篇好点的\n文章的话，请告诉我吧。$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest::
    .string "我很期待你的下一场\n华丽大赛。$"

gTVBravoTrainerText00::
    .string "太好了！\n现在是BRAVO训练师时间！\p今天我们所要介绍的\n主角就是{STR_VAR_1}。\p现在，这个宝可梦在{STR_VAR_2}\n比赛中获得{STR_VAR_3}级别为荣。$"

gTVBravoTrainerText01::
    .string "现在开始介绍{STR_VAR_1}的\n{STR_VAR_2}！\p昵称是{STR_VAR_2}…\p即便昵称也在散发\n一种呼喊“{STR_VAR_3}”的气氛啊！$"

gTVBravoTrainerText02::
    .string "那么，当训练师{STR_VAR_1}\n参加华丽大赛的时候，\l我们获得了一些对于\l可信赖的伙伴的热情对话。$"

gTVBravoTrainerText03::
    .string "后来被问到关于华丽大赛的事时，\n{STR_VAR_1}笑着高兴地回答道：\l“{STR_VAR_2}！”\p当然了，因为{STR_VAR_1}的宝可梦在\n华丽大赛中获得了第{STR_VAR_3}名嘛。\p现在来说，那个台词\n确实非常适合{STR_VAR_1}！$"

gTVBravoTrainerText04::
    .string "后来被问到关于华丽大赛的事时，\n{STR_VAR_1}带着悔恨淡淡地回答道：\l“{STR_VAR_2}！”\p当然了，因为{STR_VAR_1}的宝可梦在\n华丽大赛中获得了第{STR_VAR_3}名嘛。\p{STR_VAR_1}的失望之情\n完全表现其中了！$"

gTVBravoTrainerText05::
    .string "你不想知道{STR_VAR_1}\n希望{STR_VAR_2}会变成什么样吗？\p很想知道吧！\n当然，我们问了！\p答案完美地用一句话概括：\n“{STR_VAR_3}！”\p这就是{STR_VAR_1}印象中的\n{STR_VAR_2}的概念！$"

gTVBravoTrainerText06::
    .string "最后{STR_VAR_1}所使用的\n{STR_VAR_2}也全都是\l“{STR_VAR_3}”！$"

gTVBravoTrainerText07::
    .string "好啊，{STR_VAR_1}！\n妙啊，{STR_VAR_2}！\p希望我们能看到{STR_VAR_1}\n达到一个更高的水平！\p那么这次就到此为止了！\n我们下次再见！$"

gTVBravoTrainerText08::
    .string "下面是{STR_VAR_1}的介绍！$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
    .string "啊！你是刚刚结束\n比赛的训练师吧？\p我正在到处收集对\n训练师的采访。\p您能跟我谈一谈\n有关战斗的感想吗？$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
    .string "你愿意？真的？\n太感谢了！\l这个…\p今天在对战塔\n有什么收获？\p你对战斗还满意吗？\n或者你不怎么开心？$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
    .string "哦…\n很抱歉打扰你了。\p希望你下次来对战塔的\n时候能给我们些采访时间。$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
    .string "好的当然！\p你的脸上流露出了一\n副满意的表情…\p很明显你经历了一场\n奋战。$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
    .string "哦，我知道了…\p想让战斗完全按计划\n进行并不是一件容易的事。$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
    .string "哦我能问你几个问题吗？\p如果你要描述下你\n对于一场战斗的看法的\l话你会说些什么？$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
    .string "太帅了！\p你说得太好了！\n真期待你下一次的战斗。\p那么再见了！$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
    .string "原来是这样啊…\p不过，即使什么都不说\n也还是很帅啊？\p那么，期待下次能再\n跟你分享你的想法了！$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
    .string "我很期待你的下一次\n战斗！$"

gTVBravoTrainerBattleTowerText00::
    .string "太棒了！\n这里是加油训练师时间！\p今天我们将给大家介绍{STR_VAR_1}，\n一位对战塔的挑战者！\p{STR_VAR_1}将要挑战\n实力强劲的{STR_VAR_2}。$"

gTVBravoTrainerBattleTowerText01::
    .string "在{STR_VAR_1}的比赛中，这对组合\n创造了连胜{STR_VAR_2}的新记录！\l做得真好啊！$"

gTVBravoTrainerBattleTowerText02::
    .string "这对组合最终还是屈服在\n{STR_VAR_1}是手上了。\l好样的！\p不过，在挑战赛中这么早\n遇上{STR_VAR_1}还真是倒霉啊。\p我们询问了下关于他们\n和{STR_VAR_1}之间的比赛的感受。$"

gTVBravoTrainerBattleTowerText03::
    .string "这对组合彻底地击败了{STR_VAR_1}\n{STR_VAR_2}，获得了完胜。\l厉害啊！\p连{STR_VAR_1}都被击败了…\n这是对信心的挑战！完全的震惊！\p我们询问了下关于他们\n获胜那一瞬间的感受。$"

gTVBravoTrainerBattleTowerText04::
    .string "比赛结束后，这对组合终于\n向{STR_VAR_1}的{STR_VAR_2}屈服了，\l这就是他们最终的决定。\p好样的！\p你们的发挥非常好。\n我们从来就没有见到过像\l{STR_VAR_1}和{STR_VAR_2}一样出色的搭档。\p我们询问了关于打败那对组合\n后他们的感想。$"

gTVBravoTrainerBattleTowerText05::
    .string "他们的回答是：\n“我很满足！”\p这是不是个很爽快的回答呢？\n不愧是训练师！\p能战斗到完全满足\n不是非常厉害吗？\p训练师的这些话让我\n完全明白了这种满足感：$"

gTVBravoTrainerBattleTowerText06::
    .string "训练师应该是这么说的：\n“我还没满足…”\p我们的训练师在那发表后\n明显心情有些低落。\p不过，想要在完全满意的\n状态下战斗也没那么容易吧？\p不管怎么说，我们的训练师\n总是会以这样一句话来表达懊恼：$"

gTVBravoTrainerBattleTowerText07::
    .string "无$"

gTVBravoTrainerBattleTowerText08::
    .string "无$"

gTVBravoTrainerBattleTowerText09::
    .string "无$"

gTVBravoTrainerBattleTowerText10::
    .string "无$"

gTVBravoTrainerBattleTowerText11::
    .string "“{STR_VAR_1}。”$"

gTVBravoTrainerBattleTowerText12::
    .string "“{STR_VAR_1}。”\n这不是很棒吗？\p这就是{STR_VAR_2}的那些心得。\n我这样认为。\p和{STR_VAR_3}的那场战斗\n…你把他称作\l“{STR_VAR_1}”！$"

gTVBravoTrainerBattleTowerText13::
    .string "“{STR_VAR_1}。”\n现在合适了吗？\p和{STR_VAR_3}的那场战斗\n…你只能够使用{STR_VAR_1}”\l来描述他吗！\p{STR_VAR_2}看起来越来越失望了\n我想是这样的！$"

gTVBravoTrainerBattleTowerText14::
    .string "厉害啊，{STR_VAR_1}！\n厉害啊，{STR_VAR_2}！\p希望下次我们能见识到\n达到更高水平的{STR_VAR_1}！\p这就是我们今天的全部内容！\n下次再见！$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName::
    .string "哇哦！\p很显然你在{STR_VAR_1}上。灌注了很多的爱\p嗯…他叫{STR_VAR_2}。\p能问你一个问题吗？\p我是电视台的，我正在做一个\n宝可梦的专题。\p你能够回答我几个简单的\n问题吗？$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers::
    .string "太棒了谢谢你！\p好吧走这边吧。\n来做个快速问答怎么样？$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon::
    .string "当你第一次碰到{STR_VAR_1}，\n你是什么感觉？\p那时你是怎么描述这种\n感觉的？$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike::
    .string "你的{STR_VAR_1}被你照料得很好啊。\p你如果想把他比喻做\n一样东西的话会是什么呢？$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon::
    .string "这个问题同样关系到你\n的{STR_VAR_1}。\p{STR_VAR_1}的哪一点\n吸引了你？$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou::
    .string "OK是这样的。\p下一个问题呢\n会有一点难。\p这样的话…\p宝可梦对于你来说有什么样的意义呢？$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview::
    .string "我知道了！\p恩…\p好的！\n谢谢你帮我解决了问题。\p和你谈话真是一件\n令人赏心悦目的事情啊。\p有可能的话我们的节目\n会上演的。一定要收看啊\p就这样了。\n再见！$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe::
    .string "哦好的…\p如果你想要说些关于宝可梦\n的事情的话，我会在这里的！$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews::
    .string "我非常喜欢和你一起做\n关于宝可梦的采访。$"

SlateportCity_PokemonFanClub_Text_InterviewRequest::
    .string "嗨，你看起来和你的\n{STR_VAR_1}已经很要好了。\p你知道吗？\n我是一个记者。\p我到处寻找采访者做\n关于宝可梦的采访。\p我想知道你能够分享一些\n关于{STR_VAR_1}的事吗？$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon::
    .string "谢谢你了！\p好的，那么，请告诉我任何\n关于{STR_VAR_1}的事吧。$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2::
    .string "哦…\n这看起来很有趣。\p你的确非常的离不开{STR_VAR_1}，\n是吗？\p现在对于你的想法\n有些了解了应该可以做节目了。\p我保证这将会是我们的下\n一期的节目。\l期待你的关注。\p就这样了l。\n再见！$"

gTVFanClubOpinionsText00::
    .string "我们是宝可梦同好会！\p现在正在直播！\p这期的节目，我们将会听你们的想法，\n我将会从你们的那选一些出来播！\l听起来是不是很奇妙啊？\p今天我们来带的报道是\n在宝可梦同好会遇到\l的。\p所以让我们来看看\n今天宝可梦粉丝？\p… … … … … … … …\p{STR_VAR_1}！\p让我们看看{STR_VAR_1}都是\n怎么谈论{STR_VAR_3} {STR_VAR_2}。\p同时，我将会把这些爱的呼唤\n大声的在电视中播放给大家！\p啊！\p让我们喊出来吧！$"

gTVFanClubOpinionsText01::
    .string "我们问{STR_VAR_1}，“当你第\n一次看到{STR_VAR_2}，你的\l第一感觉是什么？”\p“{STR_VAR_3}！”\p耶！这一声多么强有力的呼喊啊！\p这是不是让你想起了你的\n从前呢？$"

gTVFanClubOpinionsText02::
    .string "我们问了{STR_VAR_1}，“如果用一个词\n来形容{STR_VAR_2}你想会是\l什么呢…”\p… … … … … … … …\p“{STR_VAR_3}！”\p这就是最初了答案了！\p你确定你能感觉到\n训练师们对于\l{STR_VAR_2}的感觉吗。$"

gTVFanClubOpinionsText03::
    .string "让我看看…\n{STR_VAR_2}是怎么\l吸引{STR_VAR_1}的呢？\p… … … … … … … …\p“{STR_VAR_3}！”\p哇！如此惊人的回答！\p训练师对于{STR_VAR_2}\n的喜爱是越来越强烈了！$"

gTVFanClubOpinionsText04::
    .string "应该还有呢。\n我查一下吧！\p让我看看…\p我们这样问{STR_VAR_1}，\n“宝可梦对于你来说有什么意义呢？”\p… … … … … …\p“{STR_VAR_3}！”\p好极了！\p这是我今天听到最棒的呐喊！\p“{STR_VAR_3}！”\p他让你一遍一遍的\n重复着！\p既然我们得到了这么棒的呐喊，\n又到了我们说再见的时候了！\p所以我们再最后一次把它大声喊出来吧！\n现在就一起…\p“{STR_VAR_3}！”$"

gTVFanClubText00::
    .string "我们是宝可梦同好会！\p现在正在直播！\p今天我们将连线到\n宝可梦服务中心。\p除了那些关于训练师和宝可梦的\n花边新闻，今天什么东西会吸引\l我们的眼球呢？\p让我看看…\p这个！\p我们将从这封信来开始！\p这是一封来自{STR_VAR_1}关于\n受人喜爱的{STR_VAR_2}的。\p让我们看看作者是怎样激情的\n表达了对于{STR_VAR_2}的喜爱！\l恩…$"

gTVFanClubText01::
    .string "哇！\n多么令人惊奇的信啊！$"

gTVFanClubText02::
    .string "我很喜欢他所以再来一遍！$"

gTVFanClubText03::
    .string "一封很棒的信是值得\n细细的体会的！$"

gTVFanClubText04::
    .string "那句“{STR_VAR_3}”确实\n有着强烈的情感冲击啊！\p这是一封非常真实\n且很有深度的信！$"

gTVFanClubText05::
    .string "特别是那句“{STR_VAR_3}”！\p我特别的喜欢“{STR_VAR_3}”的使用！$"

gTVFanClubText06::
    .string "顺便说，这并不是很重要，\n但是“{STR_VAR_3}”是这么说的。\p我经常使用“{STR_VAR_3}”\n在最近的交谈中。$"

gTVFanClubText07::
    .string "如果要为这封信评分的话，\n我将会给他{STR_VAR_3}分。\p我非常期待一封更好\n的信，{STR_VAR_1}！\p这次你会看吗？\n是时间说下次再见了！$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest::
    .string "哦？\n你看起来很喜欢宝可梦\p我是负责电视台的网络的。\p我在收集一些有关宝可梦和\n训练师的材料。\p如果你不介意的话\n能谈谈自己的看法吗？$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort::
    .string "我在收集一些有关宝可梦和\n训练师的材料。\p如果你不介意的话\n能谈谈自己的看法吗？$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon::
    .string "你愿意？\n谢谢你！\p那么请你谈谈最近你和\n宝可梦们相处的\l经历。$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory::
    .string "哦，我知道了…\p如果你有个有趣的事情的\n话请告诉我们吧。$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview::
    .string "哦多么令人振奋的故事啊！\p我肯定会把你的故事\n播到电视上的。\p有些时候是需要快奖的，我想，\n请大家密切关注后续的报道。$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory::
    .string "嗯……\n我想我的电视节目已经有内容了。\p我得赶快去写了！$"

gTVRecentHappeningsText00::
    .string "你好，又到了丰缘写真的时间。\p对于训练师来说，每一天都是\n一个故事片。\p我们想要做的就是给大家\n介绍一些宝可梦的奇闻异事。\p今天带给你们故事的是\n{STR_VAR_1}。\p{STR_VAR_1}的故事是什么呢？\n让我查一下。\p让我看看…$"

gTVRecentHappeningsText01::
    .string "这不是很有趣吗？\p这个故事有没有让\n{STR_VAR_1}觉得似曾相识呢。\l就好象我们亲眼目睹了一样！$"

gTVRecentHappeningsText02::
    .string "“{STR_VAR_3}。”\n强调了这点。$"

gTVRecentHappeningsText03::
    .string "“{STR_VAR_3}。”\n那就想一个真实的故事。\l让我们想想这个故事是在哪发生的。$"

gTVRecentHappeningsText04::
    .string "“{STR_VAR_3}”\n这件事的传说有很多种。$"

gTVRecentHappeningsText05::
    .string "{STR_VAR_1}讲述了一个关于\n宝可梦的奇妙故事。\p而现在，{STR_VAR_1}的故事\n也已经深深地刻进了你们心底了吧。\p这就是今天的全部报道。\n下次也要收看哦。$"

gTVMassOutbreakText00::
    .string "大家好！\n这里是宝可梦新闻中心。\p我们今天了解到了一个非常\n罕见的消息。\p根据相关报道称\n在{STR_VAR_1}附近引发了一场\l{STR_VAR_2}的大面积暴乱。\p正如你所知道的\n{STR_VAR_2}是一种非常罕见\l而且很难捕捉的宝可梦。\p听起来这是一个很难得的机会\n让大家了解神秘的\l{STR_VAR_2}的失控事件。\p这就是今天的报道。$"

gTV3CheersForPokeblocksText00::
    .string "主持：希望你今天能够愉快，\n“为能量方块3声加油” ！\p今天，我们来检验一下{STR_VAR_1}\n与其伙伴之间的能量方块吧。\p快点吧，让我喂喂我的，\n美食家宝可梦古平吧。\p… … … … … …\n… … … … … …$"

gTV3CheersForPokeblocksText01::
    .string "古平：古比！古比比！\p主持：这个判决也非常的{STR_VAR_1}！\n古平这么称赞“{STR_VAR_2}！”\p太感谢你了，{STR_VAR_3}！$"

gTV3CheersForPokeblocksText02::
    .string "{STR_VAR_1}的混合式表演\n仍然有很多值得回味的。\p如果训练师安排得更好，\n能量方块是不是会更棒呢。$"

gTV3CheersForPokeblocksText03::
    .string "古平：古比！古比比！\p主持：恩…太{STR_VAR_1}。\n古平这么称赞 “{STR_VAR_2}！”\p看起来{STR_VAR_3}的努力\n不是很有用…$"

gTV3CheersForPokeblocksText04::
    .string "真是太糟糕了 {STR_VAR_1}的\n努力付诸东流了。\p我们希望{STR_VAR_2}下次能\n带给我们一个更加精彩的表演！$"

gTV3CheersForPokeblocksText05::
    .string "下次要来哦！我们的标语是\n “全心全意为能量方块！”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
    .string "这边！\p我是{STR_VAR_1}的超级粉丝。\n你是怎么看待{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
    .string "我知道了我想这就是你对于\n训练师的看法吧。$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
    .string "你完全不记得\n{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
    .string "我是{STR_VAR_1}的超级粉丝。\n你是怎么看待{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
    .string "你对{STR_VAR_1}\n的迅速强大有什么看法？$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
    .string "你完全不记得\n{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
    .string "哦我知道了\n你在什么时候见过{STR_VAR_1}。\l我相信你也会成为一名粉丝的！$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
    .string "我知道，我知道了。\p谢谢你了！\n这对于我们来说太有用了。\p我将会把这个信息和\n{STR_VAR_1}的其他粉丝一起分享的。$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
    .string "这个节目关于\n{STR_VAR_1}的节目很快就播了。\p希望你能准时收看！$"

gTVTrainerFanClubSpecialText00::
    .string "训练师迷俱乐部\n{STR_VAR_1}特别版！\p这是赠给{STR_VAR_1}的粉丝的\n一个特别的礼物！\p今天让我们来进行这个话题大家是\n怎样看待{STR_VAR_1}？”\p让我们连线{STR_VAR_2}\n一位训练师代表。\p我们问，“总的来说你要怎\n么来描述{STR_VAR_1}？”\p回答是：“{STR_VAR_3}。”\p对{STR_VAR_2}的称赞！\n多么富有灵气的回答啊！\p“{STR_VAR_3} {STR_VAR_1}。”\n他是多么的令人羡慕啊！\p{STR_VAR_2}也将{STR_VAR_1}的\n视做完美。$"

gTVTrainerFanClubSpecialText01::
    .string "得分是{STR_VAR_3}点！\n得分相当的高啊！\p{STR_VAR_2}对\n{STR_VAR_1}很敬重啊。$"

gTVTrainerFanClubSpecialText02::
    .string "得分是{STR_VAR_3}点！\n分数相当的高啊。\p{STR_VAR_2}一定把\n{STR_VAR_1}看成了对手。$"

gTVTrainerFanClubSpecialText03::
    .string "得分是{STR_VAR_3}点！\n得分太低了。\p{STR_VAR_2}一定把\n{STR_VAR_1}看成了伙伴。$"

gTVTrainerFanClubSpecialText04::
    .string "得分是{STR_VAR_3}点！\n分数真糟糕。\p{STR_VAR_2}一定把\n{STR_VAR_1}看成自己的属下。$"

gTVTrainerFanClubSpecialText05::
    .string "你们得到了，朋友们！\p我想我们会学到一些\n关于{STR_VAR_1}的新知识。\p在结束时，我会给你\n{STR_VAR_2}的剑。\p{STR_VAR_3} {STR_VAR_1}！$"

gTVNameRaterText00::
    .string "那么现在，到时间…\n姓名占卜师。\p通过你给它的昵称，\n我会告诉你关于你宝可梦的未来。\p我给你的建议会对你\n非常有帮助。\p今天，我就读一读\n{STR_VAR_1}的{STR_VAR_3}昵称\l宝可梦{STR_VAR_2}。\p嗯…\p嗯…\n昵称就是…$"

gTVNameRaterText01::
    .string "一个昵称用许多不同的方式\n来提示天赋。\p我力劝这个训练师打起勇气\n多多接受挑战。$"

gTVNameRaterText02::
    .string "一个昵称配上训练师的名字\n{STR_VAR_1}，就完美无缺了。\p我建议你在适当的时候\n打造一个好的伙伴关系。$"

gTVNameRaterText03::
    .string "一个昵称很适合\n一个独一无二的宝可梦！\p如果饲养得当的话，这个宝可梦\n的独特性就很会快体现起来！$"

gTVNameRaterText04::
    .string "一个昵称会培养出宝可梦的\n人道心和同情心。\p如果饲养得当的话，这个宝可梦将会\n觉醒和展示出真正的热情！$"

gTVNameRaterText05::
    .string "一个好的昵称会暗示\n有好事发生。\p我很有兴趣想知道这个宝可梦\n的将来会是什么样。$"

gTVNameRaterText06::
    .string "一个好的昵称应该会让\n宝可梦精神充沛！\p那个宝可梦应该会长时间的保持健康\n和精神充沛。$"

gTVNameRaterText07::
    .string "一个好的昵称应该会让\n宝可梦非常活跃的！\p我会认为这个宝可梦将会\n在战场上有强有力的表现。$"

gTVNameRaterText08::
    .string "一个吸引人的昵称应该会让\n宝可梦魅力十足！\p我肯定这个宝可梦\n在宝可梦华丽大赛上人见人爱。$"

gTVNameRaterText09::
    .string "昵称{STR_VAR_1}源于\n这个字“{STR_VAR_3}。”\p这个字依托于第一个\n字“{STR_VAR_2}，”，\l这个字赋予了它实际意义。$"

gTVNameRaterText10::
    .string "一个昵称{STR_VAR_1}在令人愉快的意义上是\n非常有条理的。\p字“{STR_VAR_2}”和“{STR_VAR_3}”的存在\n--现在那是非常的好！$"

gTVNameRaterText11::
    .string "这个昵称{STR_VAR_1}--它让人有\n一种连贯，流畅的感觉。\p从第一个字“{STR_VAR_2}”到\n“{STR_VAR_3}”一气呵成。实在太奇妙了$"

gTVNameRaterText12::
    .string "让我们看看别的好昵称的\n例子，好不好？$"

gTVNameRaterText13::
    .string "试试这个例子。\n用训练师名字{STR_VAR_1}的一部分，\l然后再以好的昵称{STR_VAR_2}{STR_VAR_3}结尾。$"

gTVNameRaterText14::
    .string "昵称{STR_VAR_2}{STR_VAR_3}也会\n很有效果。$"

gTVNameRaterText15::
    .string "宝可梦的特别名字\n{STR_VAR_2}能用来作为昵称\l{STR_VAR_1}{STR_VAR_3}的基础。$"

gTVNameRaterText16::
    .string "{STR_VAR_1}{STR_VAR_3}也会是一个有效的\n昵称。$"

gTVNameRaterText17::
    .string "要尽量避免用\n别的宝可梦的种类名称。\p比如说，避免用{STR_VAR_1}{STR_VAR_2}\n的名字来做这个昵称{STR_VAR_1}{STR_VAR_3}。\l这是行不通的。$"

gTVNameRaterText18::
    .string "我得说{STR_VAR_1}是非常\n好的昵称。\p我希望那个训练师会继续\n用爱来对待{STR_VAR_1}。\p今天的表演就到此为止了。\n我们也许会再见面的。$"

gTVPokemonAnglerText00::
    .string "{STR_VAR_2}钓鱼\p主持：你好！今天，我们会得到提示\n在寻找{STR_VAR_2}。\p戈鲁，你可以给点什么建议来\n抓{STR_VAR_2}？\p戈鲁：嗯？抓{STR_VAR_2}？\n好吧，告诉你，要有耐心\l并会等待。那是底线。\p你有没有看见{STR_VAR_1}在那里？\n那个训练师做了个好榜样。\p那个训练师已经把\n{STR_VAR_3}宝可梦送走了。\p但是那个{STR_VAR_1}还等着。没放弃。\n这就是抓{STR_VAR_2}的不二法则。\p主持人：了解…\p哦！{STR_VAR_1}终于到达了一个\n难于定义的{STR_VAR_2}！\p这个训练师看起来就要\n流出喜悦的眼泪了！\p看着这样快乐的表情，我也越发\n的渴望去钓鱼了！\p观众们，为什么不把这个当作是一个暗示\n试试用一些{STR_VAR_2}来钓鱼？\p在我们下一次的广播来到前，那么先再见了，\n祝大家都钓到好东西！$"

gTVPokemonAnglerText01::
    .string "{STR_VAR_2}钓鱼\p主持人：嗨！今天，我们会得都一些提示\n来钓{STR_VAR_2}。\p戈鲁，你会给大家什么样的建议来\n抓住{STR_VAR_2}？\p戈鲁：哦？想抓住{STR_VAR_2}？\n好吧，让我告诉你，用你的钓鱼\l竿和精力！\p你看到{STR_VAR_1}在那边了吗？\n看看这个鱼竿是怎样用的？\p那个训练师已经连续地抓住了\n{STR_VAR_3}。\p主持人：真是不可思议！\n看起来就像一个风暴…\p看这卓越的技巧，我也\n越发的渴望去钓鱼了。\p观众们，为什么不把这个当作是一个暗示\n试试用一些{STR_VAR_2}来钓鱼？\p在我们下一次的广播来到前，那么先再见了\n祝大家都钓到好东西！$"

gTVPokemonTodayFailedText00::
    .string "哈喽！\p是今天的宝可梦的时间了！\p大姐姐：嗨！大家今天过的\n都好吗？\p今天，我们要关注下{STR_VAR_1}的\n宝可梦{STR_VAR_2}！\p大哥哥：是的！这就是我们打算\n去做的！$"

gTVPokemonTodayFailedText01::
    .string "哦！\n说到{STR_VAR_1}…\p大姐姐，我是亲眼见过\n那个训练师！\p大姐姐：哦，你都看到了什么了？\p大哥哥：好吧，我只好旅行到\n{STR_VAR_2}。\p那时我碰巧要穿越\n{STR_VAR_1}，他正在努力去抓住那个\l宝可梦{STR_VAR_3}，可是…$"

gTVPokemonTodayFailedText02::
    .string "那个宝可梦却逃掉了！\p结果浪费了很多\n精灵球：{STR_VAR_2}！\p你应该看见过挫败的\n表情在{STR_VAR_1}的脸上当\l宝可梦逃掉的时候！$"

gTVPokemonTodayFailedText03::
    .string "可是{STR_VAR_1}弄错的话会让\n宝可梦昏厥的！\p结果就是浪费钱\n精灵球：{STR_VAR_2}！\p你应该见过\n惊吓了的又沮丧表情在{STR_VAR_1}的脸上\l当宝可梦昏厥时！$"

gTVPokemonTodayFailedText04::
    .string "大姐姐：嘿，那的！\n这可不友好！\p你不应该笑话别人的\n不幸！\p哦，可怜的{STR_VAR_1}。\n真是可耻！\p大哥哥：说的没错！\n真诚的道歉。$"

gTVPokemonTodayFailedText05::
    .string "大姐姐：呃呃…\p大哥哥：嗨！\n你刚刚也笑了！\p大姐姐：哼？！\p我没有！\n说真的，我没有！\p哦，可怜的{STR_VAR_1}。\n真是可耻！\p大哥哥：…$"

gTVPokemonTodayFailedText06::
    .string "大姐姐：真是有够傻的！\n我们看看今天的宝可梦…\p嗯？\n已经没时间了？\p啊！\n今天我们不能继续分析了！\p大哥哥：下一次再见！\p大姐姐：嘿，结束节目的时候\n别丢下我！$"

gTVPokemonTodaySuccessfulText00::
    .string "大家好！\p是今天的宝可梦的时间了！\p大姐姐：嗨！大家今天过的\n都好吗？\p今天，我们要关注的是{STR_VAR_1}的\n宝可梦{STR_VAR_2}！\p大哥哥：是的！这就是我们打算\n去做的！$"

gTVPokemonTodaySuccessfulText01::
    .string "大姐姐：{STR_VAR_1}给{STR_VAR_2}取了昵称\n{STR_VAR_3}！\p听起来{STR_VAR_3}被照顾的\n非常的好！$"

gTVPokemonTodaySuccessfulText02::
    .string "大哥哥：那个训练师不得不丢\n许多精灵球来抓住它：{STR_VAR_3}！\p终于用了一个{STR_VAR_2}\n抓住它了！$"

gTVPokemonTodaySuccessfulText03::
    .string "大姐姐：如果很容易就抓住的话，\n那一定是命运把\l{STR_VAR_1}和{STR_VAR_2}带到了一起$"

gTVPokemonTodaySuccessfulText04::
    .string "大姐姐：哇！那可真简洁！\p但是你知道人们都说，一个需要花上很大努力\n才可以抓住的宝可梦\l才会得到它的训练师的爱！$"

gTVPokemonTodaySuccessfulText05::
    .string "大姐姐：{STR_VAR_1}的{STR_VAR_2}是一个\n值得纪念的宝可梦因为它需要一个\l无价的掌门球才可以抓住！\p大哥哥：哇！真是帅呆了！\p大姐姐：{STR_VAR_1}一定想\n那个{STR_VAR_2}想疯了，一定的！$"

gTVPokemonTodaySuccessfulText06::
    .string "大哥哥：那么来把这个昵称\n{STR_VAR_3}给{STR_VAR_2}…\p你的确有个好主意\n对{STR_VAR_1}的训练师判断力。\p大姐姐：我赞成这个观点！$"

gTVPokemonTodaySuccessfulText07::
    .string "如果是我的话，我会把那个昵称\n给像{STR_VAR_3}这样的！\p大哥哥：唔哇！那可能是一个新事物的\n开端！$"

gTVPokemonTodaySuccessfulText08::
    .string "{STR_VAR_2}那个{STR_VAR_1}？\n听起来很完美吧？\p这个字母还有一切--它们\n听起起来很配宝可梦\l{STR_VAR_1}！\p大哥哥：是啊，没错，那个！$"

gTVPokemonTodaySuccessfulText09::
    .string "就居我所知，没有一个训练师\n把昵称{STR_VAR_2}给过他们的\l{STR_VAR_1}！\p大哥哥：那展示了那个\n训练师在选昵称上有很\l好的品味！$"

gTVPokemonTodaySuccessfulText10::
    .string "下一次我再抓住宝可梦，\n我会给它命名{STR_VAR_2}。\p大哥哥：哈？我也是！\n我也会用这个昵称{STR_VAR_2}！$"

gTVPokemonTodaySuccessfulText11::
    .string "大姐姐：哦，不！\n看看时间！\p好吧，那么，今天就到这了。\n下次再见！\p大哥哥：记住，下一次就有可能是你的\n宝可梦在这聚光灯下！$"

SmartShopper_Text_Intro::
    .string "大家好！\p又到了今日购物导航的时间了。\p访问记者：你们好吗，电视机前的朋友们？\p今天我们访问了\n{STR_VAR_2}的一家商店。\p让我们调查一下最近\n商店里的热销产品。$"

SmartShopper_Text_ClerkNormal::
    .string "让我们采访一下\n了解情况的职员。\p嘿，你们的工作进度如何？\p营业员：啊，我们做的非常好。\p最近，尤其是{STR_VAR_2}的\n销售情况非常可观。\p为什么，只是因为有一次一个叫{STR_VAR_1}\n的训练师买了{STR_VAR_3}。$"

SmartShopper_Text_RandomComment1::
    .string "访问记者：一个训练师买了\n{STR_VAR_3}个{STR_VAR_2}？这太有鼓动性了！\p我是否可以这样判断，{STR_VAR_1}一定\n是在为一个遥远而长久的旅程\l积攒一些东西。\p对于旅行来说，{STR_VAR_2}实在是\n太重要了！$"

SmartShopper_Text_RandomComment2::
    .string "访问记者：说到{STR_VAR_2}\n这件道具，我最近只买了\l其中的{STR_VAR_3}。\p毕竟，{STR_VAR_2}是个好东西呀！$"

SmartShopper_Text_RandomComment3::
    .string "访问记者：{STR_VAR_2}？！\n是其中的{STR_VAR_3}？！\p我不相信有人能买\n那么多。\p我的女神啊，我只能支付的起\n一到两个啊…$"

SmartShopper_Text_RandomComment4::
    .string "访问记者：有一次，我买下了\n{STR_VAR_2}的全部款式。\p但是它却出了更多。\n我只能放弃这个目标了…\p从那时起，我只买\n我确实必须的东西…\p哎呀！\p和我说话是没有什么好处的！$"

SmartShopper_Text_SecondItem::
    .string "营业员：{STR_VAR_1}也大批量的购买了\n{STR_VAR_2}，取得了{STR_VAR_3}。\p访问记者：干的实在是太漂亮了。\n{STR_VAR_2}也是一个非常好的东西。$"

SmartShopper_Text_ThirdItem::
    .string "营业员：而且，那个训练师也买了\n{STR_VAR_2}中的{STR_VAR_3}。$"

SmartShopper_Text_DuringSale::
    .string "营业员：再加上，他还在热卖中。\n那是一个明智的选购。$"

SmartShopper_Text_OutroNormal::
    .string "访问记者：恩… {STR_VAR_1}听起来\n很像一个精明的生意人！\p那么，{STR_VAR_1}的消费总额是…\p{STR_VAR_2}$？！\n多么另人惊讶的数字！\p哎呀！时间又到了！\n我们下次见吧！$"

SmartShopper_Text_IsVIP::
    .string "营业员：{STR_VAR_1}是一个VIP客人，\n没什么好怀疑的。$"

SmartShopper_Text_ClerkMax::
    .string "让我们采访一下店员\n来获取一些消息。\p嘿，你们的过工作何了？\p营业员：啊，我们的工作情况简直\n另人难以置信。实在是压倒性的顺利。\p最近，一个叫做{STR_VAR_1}的训练师\n大批量的购买了{STR_VAR_2}。\p那个训练师几乎买空了\n我们的{STR_VAR_2}库存。\p我从没想过会有一个客人\n需要这么多的{STR_VAR_2}。\l这是闻所未闻的！\p访问记者：就像卖出去了\n一两百个那么多？\p营业员：啊？不！比那多的多！\p访问记者：啊，我的天那！\n{STR_VAR_1}一定是个很特别的客人！\p营业员：{STR_VAR_1}是一个VIP客人，\n无须怀疑。$"

SmartShopper_Text_OutroMax::
    .string "访问记者：恩…\n太另人惊讶了。\p但是为什么一个训练师\n需要这么多？\p… …\p越来越神秘了，但是我们节目\n结束的时间又到了。\l我们下次节目再见！\p然而，{STR_VAR_1}一定是个不可思议的人…$"

gTVWorldOfMastersText00::
    .string "大师的世界\p你们好，观众朋友。\p也许你们已经听到过\n那个叫{STR_VAR_1}的训练师。\p{STR_VAR_1}是一个出了名的\n宝可梦捕捉大师。\p{STR_VAR_1}对宝可梦的寻求完全依靠\n凭借双脚仔细的寻找。\p在那些值得纪念的日子里，那个训练师\n走过了{STR_VAR_2}的足迹。\p他抓到的宝可梦总数\n达到了让人难忘的{STR_VAR_3}！$"

gTVWorldOfMastersText01::
    .string "这不平凡的功绩绝对不是虚假的，\n因为在那个训练师和{STR_VAR_1}之间，\l是完全的相互信赖。$"

gTVWorldOfMastersText02::
    .string "那个人最后在\n{STR_VAR_2}附近抓到了{STR_VAR_3}。\p那只宝可梦显然很喜欢\n作为记录保持者的地位。\p有经验的训练师应该被鼓励\n去挑战这个记录。\p这就是今天的全部内容。\n请下次再关注本节目。$"

gTVTodaysRivalTrainerText00::
    .string "今天的对手训练师！\p大家好，宝可梦训练师们！\n我们今天要干什么呢？\p今天，象平时一样，\n我们要调查一个对手！$"

gTVTodaysRivalTrainerText07::
    .string "今天的训练师是{STR_VAR_1}，\n现在他在{STR_VAR_3}附近。\p{STR_VAR_1}迄今为止已经在宝可梦图鉴\n注册了{STR_VAR_2}的宝可梦。$"

gTVTodaysRivalTrainerText08::
    .string "今天的训练师是{STR_VAR_1}，\n他现在还是一个秘密基地。\p{STR_VAR_1}迄今为止已经在宝可梦图鉴\n注册了{STR_VAR_2}只宝可梦。$"

gTVTodaysRivalTrainerText09::
    .string "今天的训练师是{STR_VAR_1}。\p迄今为止，{STR_VAR_1}已经在宝可梦图鉴\n注册了{STR_VAR_2}只宝可梦。$"

gTVTodaysRivalTrainerText10::
    .string "今天的训练师是{STR_VAR_1}，\n他现在在码头。\p{STR_VAR_1}迄今为止已经在宝可梦图鉴\n注册了{STR_VAR_2}只宝可梦。$"

	.string "$"

gTVTodaysRivalTrainerText01::
    .string "那么我们的竞争者有多少徽章呢？\n他有{STR_VAR_1}个！$"

gTVTodaysRivalTrainerText02::
    .string "但是我们的竞争者\n还有一个徽章没有拿到！$"

gTVTodaysRivalTrainerText03::
    .string "我们的竞争着没有拿到\n对战开拓区的奖牌。$"

gTVTodaysRivalTrainerText04::
    .string "让我看看我们的挑战者拿到了\n多少对战开拓区的奖牌。\p金色印记：{STR_VAR_1}！\n银色印记：{STR_VAR_2}！$"

gTVTodaysRivalTrainerText05::
    .string "我们的挑战者在对战开拓区\n收集了{STR_VAR_1}点战斗点数。$"

gTVTodaysRivalTrainerText06::
    .string "那么，你怎样才能拥有足以\n和{STR_VAR_1}相比的实力呢？\p去冒险吧！\p去追随训练师！\p让我们去追赶我们的竞争者\n甚至是超越他吧！$"

TrendWatcher_Text_Intro::
    .string "武斗镇流行调查员联络网！\p主持：怎么了？\n我们需要了解那些\l发生在武斗镇的的一些趣闻。\p我们今天的客人就是这位\n被称做武斗镇一切事物\l的权威人士的老家伙。\p老人：很高兴来到这里。\p主持：好的，让我们转入正题吧。\p您觉得目前在武斗镇的\n居民中最流行的是什么？\p老人：{STR_VAR_1}{STR_VAR_2}。\p主持：你说{STR_VAR_1}\n{STR_VAR_2}？\p老人：不。\p{STR_VAR_1}{STR_VAR_2}从来\n就没有出名过。\p你想听听他们的故事吗？\p主持：恩，不了。我们想知道的是\n一些政治性的…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
    .string "老人：{STR_VAR_1}{STR_VAR_2}\n是一个从未白镇来的{STR_VAR_3}\l告诉我的一件新鲜事物…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
    .string "老人：{STR_VAR_1}{STR_VAR_2}\n是一个从未白镇来的{STR_VAR_3}\l告诉我的一件新鲜事物…$"

TrendWatcher_Text_PhraseWasHopeless::
    .string "但是我绝望了。\p{STR_VAR_1}{STR_VAR_2}节！\p{STR_VAR_1}{STR_VAR_2}比赛！\p我试着尽全力去把它\n教给每一个人，但是…\p或许{STR_VAR_1}部分\n并不是正确的…\p主持：恩，打扰一下，先生，我需要\n听一些政治性的…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
    .string "老人：{STR_VAR_3}！\n那么，请你告诉我一些\l比{STR_VAR_1}{STR_VAR_2}更重要的事吧！$"

TrendWatcher_Text_FemaleTellMeBigger::
    .string "老人：{STR_VAR_3}！\n那么，请你告诉我一些\l比{STR_VAR_1}{STR_VAR_2}更重要的事吧！$"

TrendWatcher_Text_Outro::
    .string "主持：…恩…这样，那都是你的想法，\n你的兴趣，别在这里说！\p{STR_VAR_1}{STR_VAR_2}…恩…\n我们没有得到关于武斗镇的趣闻啊！\p我可没时间去理解你的胡言乱语！\p老人：{STR_VAR_1}{STR_VAR_2}！$"

gTVHoennTreasureInvestigatorsText00::
    .string "丰缘宝藏挖掘者！\p嗨，大家！\n最近记下什么秘密了么？\p一直以来，我们都在从各地的\n目击者报告里找寻各种秘密！\p让我们从这封信开始。\n信中说道，“发现{STR_VAR_1}！”$"

gTVHoennTreasureInvestigatorsText01::
    .string "喔，我们必须要仔细看看这封信！\n我来为你们读一下。\p…亲爱的挖掘者，\n我希望你很好。\p我最近在{STR_VAR_3}附近的一些地方\n看到了{STR_VAR_2}。\p那个训练师找到了\n{STR_VAR_1}。这让我很嫉妒。\p…好的，这很不错，{STR_VAR_2}！\p观众们，就让这件事激发你们的\n探索欲望吧！\p我会一直等待你们\n给我激动人心的消息的！$"

gTVHoennTreasureInvestigatorsText02::
    .string "喔，我们必须要仔细看看这封信！\n我来为你们读一下。\p…亲爱的挖掘者，\n我希望你很好。\p我最近再码头看到{STR_VAR_2}了。\p那个训练师找到了\n{STR_VAR_1}。那让我很嫉妒。\p…好的，这很不错，{STR_VAR_2}！\p观众们，就让这件事激发你们的\n探索欲望吧！\p我会一直等待你们\n给我激动人心的消息的！$"

gTVFindThatGamerText00::
    .string "寻找玩家！\p嘿，玩家们！\n你们的{STR_VAR_2}转的如何？\p象往常一样，我们会关注\n那个稀有的训练师，也就是第一个\l访问游戏中心的人！\p今天，我们的No.1玩家是…\n{STR_VAR_1}！$"

gTVFindThatGamerText01::
    .string "{STR_VAR_1}玩过{STR_VAR_2}游戏\n并赢得了珍贵的{STR_VAR_3}代币。\p“当{STR_VAR_1}来到时，我们要确定\n我们有足够的代币。”\p这就是游戏中心的职员\n在我们的玩家玩游戏时的碎碎念！\p观众们，你们最好像{STR_VAR_1}一样看一看\n你们的代币，如果你去了游戏\l中心并且玩了{STR_VAR_2}游戏。\p这就是游戏中心里的生活--\n一个你能随时感到刺激的地方！\p今天的节目到此为止！$"

gTVFindThatGamerText02::
    .string "{STR_VAR_1}玩了{STR_VAR_2}游戏\n并输了{STR_VAR_3}的代币。\p“当{STR_VAR_1}来的时候，我们的代币\n销售看起来增大了。”\p这就是游戏中心的职员\n在我们的玩家玩游戏时的碎碎念！$"

gTVFindThatGamerText03::
    .string "观众们，你们最好像{STR_VAR_1}一样看一看\n你们的代币，如果你去了游戏\l中心并且玩了{STR_VAR_2}游戏。\p这就是游戏中心里的生活--\n一个你能随时感到刺激的地方！\p今天的节目到此为止！$"

gTVBreakingNewsText00::
    .string "重大新闻！$"

gTVBreakingNewsText01::
    .string "珍奇的{STR_VAR_2}被\n{STR_VAR_1}捉住了！\p我们住在\n{STR_VAR_3}的附近！\p{STR_VAR_1}再这里成功的\n捕获了稀有的{STR_VAR_2}！$"

gTVBreakingNewsText02::
    .string "当{STR_VAR_1}遭遇了稀有的\n{STR_VAR_2}，训练师把那只\l宝可梦送给了{STR_VAR_3}。$"

gTVBreakingNewsText03::
    .string "在战斗中，被训练师扔出的\n精灵球的数量是{STR_VAR_1}。\p稀有的宝可梦被抓住\n最后用了{STR_VAR_2}个。$"

gTVBreakingNewsText04::
    .string "很直接的，{STR_VAR_2}用\n{STR_VAR_1}成功的欢快叫声\l进行了回击。\p我不能否认我有些嫉妒\n{STR_VAR_1}。我也想大叫。\p…这种喜悦\n感染了全场！$"

gTVBreakingNewsText05::
    .string "{STR_VAR_1}没有捕获到\n{STR_VAR_2}！\p我们住在\n{STR_VAR_3}附近！\p这是{STR_VAR_1}捕获珍奇的{STR_VAR_2}\n失败的地方！$"

gTVBreakingNewsText06::
    .string "当{STR_VAR_1}遭遇了稀有的\n{STR_VAR_2}，训练师把那只\l宝可梦送给了{STR_VAR_3}。$"

gTVBreakingNewsText07::
    .string "训练师让{STR_VAR_2}\n使用了{STR_VAR_1}。\p没有任何犹豫，那个训练师\n另那稀有宝可梦晕倒了…$"

gTVBreakingNewsText12::
    .string "但是，{STR_VAR_1}被稀有的{STR_VAR_2}\n的眼神吓坏了。\p混乱中，训练师又安排\n{STR_VAR_3}来攻击。\p没有丝毫犹豫，训练师\n另稀有的宝可梦眩晕了。$"

gTVBreakingNewsText08::
    .string "刻不容缓，{STR_VAR_2}\n又用{STR_VAR_1}的尖叫声\l进行回击…$"

gTVBreakingNewsText09::
    .string "但是，{STR_VAR_1}似乎又从\n精灵球里跑出来了。\p训练师必须中断\n和{STR_VAR_2}的战斗。\p接下来，{STR_VAR_3}\n又用{STR_VAR_1}的尖叫声\l进行回击…$"

gTVBreakingNewsText10::
    .string "但是，{STR_VAR_2}毫无预兆的\n逃跑了。\p接下来，{STR_VAR_3}\n又用{STR_VAR_1}的尖叫声\l进行回击…$"

gTVBreakingNewsText11::
    .string "我必须说我很同情{STR_VAR_1}。\n为什么，那让我也想尖叫了。\p…这忧郁的气氛\n渲染了全场！$"

gTVSecretBaseVisitText00::
    .string "嘿，大家好！\n又是参观秘密基地的\l时间了。\p今天，我们要参观的秘密基地\n是{STR_VAR_1}的！\p{STR_VAR_1}如何将自己的秘密基地\n个性化设计的？\p让我们拭目以待！\n… … … … … …$"

gTVSecretBaseVisitText01::
    .string "哦！\n多么不可思议啊！\p这是{STR_VAR_2}…\n这种东西，任何人也想不到，\l会在这里发现吧！$"

gTVSecretBaseVisitText02::
    .string "哇！\n多么值得称赞！\p这不仅仅是\n单纯的家具或者内饰！\p凡人是不敢奢望\n模仿这么大胆的设计的！\p多么简单，却多么令人冲动\n是啊，令人心中充满了野性的冲动！\p我要对你脱帽致敬了，{STR_VAR_1}。\n只有你才能做得这么好！$"

gTVSecretBaseVisitText03::
    .string "哦，原来如此！\n我清楚地看见了\p这里的{STR_VAR_2}\n多么有效！$"

gTVSecretBaseVisitText04::
    .string "哦，原来如此！\n我清楚地看见了！\p这里故意没有摆放\n内饰物品！\p多么有效！$"

gTVSecretBaseVisitText05::
    .string "哇呼！\p这里有一对{STR_VAR_2}\n和{STR_VAR_3}！\p相对于只有一个，\n这简直是梦幻的结合！$"

gTVSecretBaseVisitText06::
    .string "哇塞！\p在这里摆放的{STR_VAR_2}…\p它的存在感充满了\n整个秘密基地！$"

gTVSecretBaseVisitText07::
    .string "呵呵！\p这里什么都没有……\p但是这里的空白\n却为整个秘密基地填上了有用的一笔。$"

gTVSecretBaseVisitText08::
    .string "哦！\n{STR_VAR_1}来了！\l让我们赶快开始对战！\p… … … … … …\n… … … … … …$"

gTVSecretBaseVisitText09::
    .string "唉…\n我要把它给{STR_VAR_1}。\p这个训练师的宝可梦实在\n值得授予冠军头衔。\p它们足够证明{STR_VAR_1}\n作为训练师的实力之强。\p这{STR_VAR_2}会\n{STR_VAR_3}这个技能…\p他显示了你是如何一个训练师\n{STR_VAR_1}。\p我实在是学到了很多！$"

gTVSecretBaseVisitText10::
    .string "哎呀！\n我要把它给{STR_VAR_1}。\p这个训练师的宝可梦\n像怪物一样强！\p它们充分地证明了{STR_VAR_1}\n作为训练师的顽强。\p那个{STR_VAR_2}竟然会\n{STR_VAR_3}这个技能…\p它说明了你到底是个什么样\n的训练师，{STR_VAR_1}。\p我实在学到了很多！$"

gTVSecretBaseVisitText11::
    .string "哎呀！\n我要把它给{STR_VAR_1}。\p这个训练师的宝可梦很明显地\n是被培养成了具有很平均的风度。\p它们充分地证明了{STR_VAR_1}的\n作为训练师的思维缜密。\p那个{STR_VAR_2}竟然会\n{STR_VAR_3}这个技能…\p它说明了你到底是个什么样的训练师\n，{STR_VAR_1}。\p我实在学到了很多！$"

gTVSecretBaseVisitText12::
    .string "好啊，好啊！\n我要把它给{STR_VAR_1}。\p这个训练师的宝可梦展现了\n对未来成长的决心。\p它们代表了{STR_VAR_1}的\n希望和梦想。\p那个{STR_VAR_2}竟然会\n{STR_VAR_3}这个技能…\p它说明了你到底是个什么样的训练师\n，{STR_VAR_1}。\p我实在学到了很多！$"

gTVSecretBaseVisitText13::
    .string "我必须说，超级的秘密基地\n就是这样的！\p参观者们，如果你有机会，\n一定要参观一下{STR_VAR_1}的秘密基地。\p希望还能再见！$"

gTVPokemonLotteryWinnerFlashReportText00::
    .string "多么令人激动！\n多么具有戏剧性！\p这是宝可梦彩票\n赢家快速报导！\p大家好！这是在水静市\l商业大厦一楼的\n宝可梦彩票中心的\l现场直播！\p就像以前一样，今天出现了幸运的训练师！\p这个训练师是…\n{STR_VAR_1}！\p{STR_VAR_1}得了{STR_VAR_2}等奖\n他获得了{STR_VAR_3}！\p{STR_VAR_1}！\n恭喜！\p观众们，不要只是在电视机前观看，\n加入我们吧！\p水静市商业大厦的我们\n期待着你的下次来访！\p这是来自水静市商业大厦\n的现场直播，\l给你提供，在丰缘能买到的\l最好的商品！$"

gTVThePokemonBattleSeminarText00::
    .string "这里是宝可梦对战研讨会！\p我们研究战斗，来发现\n我们能从别人那里学到什么。\p今天我们来研究一下{STR_VAR_1}的\n战斗。\p{STR_VAR_1}的{STR_VAR_2}正在\n与{STR_VAR_3}战斗…$"

gTVThePokemonBattleSeminarText01::
    .string "然后它对{STR_VAR_2}\n使用了{STR_VAR_3}这个技能…\p哼哼… {STR_VAR_1}！\n你不能这样做！$"

gTVThePokemonBattleSeminarText02::
    .string "{STR_VAR_1}也会这个……$"

gTVThePokemonBattleSeminarText03::
    .string "{STR_VAR_1}，{STR_VAR_2}，\n和{STR_VAR_3}这几个技能。$"

gTVThePokemonBattleSeminarText04::
    .string "{STR_VAR_1}和\n{STR_VAR_2}这两个技能。$"

gTVThePokemonBattleSeminarText05::
    .string "{STR_VAR_2}这个技能。$"

gTVThePokemonBattleSeminarText06::
    .string "在这个状况下，\n这训练师用了什么技能呢？\p… … … … … …\n{STR_VAR_1}！\p{STR_VAR_1}这技能一定会\n比{STR_VAR_2}好。\p观众们，我强烈希望你能从这次战斗学到什么，\n下次要更聪明的战斗哦！\p下次再见，拜拜！$"

gTVTrainerFanClubText00::
    .string "大家注意了！\n这里是训练师迷俱乐部！\p主持：大家状态都好吗？\n今天，我们聚集了众所周知\l的训练师，{STR_VAR_1}的支持者！\p酱油众：哦！\p酱油众：{STR_VAR_1}！\p主持：大家！\n你们对{STR_VAR_1}的感觉是？！\p酱油众：我们爱{STR_VAR_1}！\p主持：你们怎么会爱\n{STR_VAR_1}的？！$"

gTVTrainerFanClubText01::
    .string "酱油众：他们帅呆了地扔精灵球！$"

gTVTrainerFanClubText02::
    .string "酱油众：他们跑步时那美丽的样子！$"

gTVTrainerFanClubText03::
    .string "酱油众：这些训练师在他们想要变强时，\n他们就变强了！$"

gTVTrainerFanClubText04::
    .string "酱油众：这个训练师对宝可梦的渊博知识！$"

gTVTrainerFanClubText05::
    .string "酱油众：这个训练师对所有宝可梦的温柔！$"

gTVTrainerFanClubText06::
    .string "酱油众：这个训练师那\n令人惊异的骑车技术。$"

gTVTrainerFanClubText07::
    .string "酱油众：这个训练师那\n令人印象深刻的购物方式！$"

gTVTrainerFanClubText08::
    .string "酱油众：这个训练师给宝可梦起的\n那些迷人的名字！$"

gTVTrainerFanClubText09::
    .string "酱油众：这个训练师那漂亮的\n装饰秘密基地的方式！$"

gTVTrainerFanClubText10::
    .string "酱油众：这个训练师大胆地\n使用技能机器！$"

gTVTrainerFanClubText11::
    .string "主持：就像你们看见的那样，{STR_VAR_1}\n真流行！简直就像没法触碰一样，哇呼！\p在{STR_VAR_1}的酱油众中\n有一个特别的口号！\p主持：当我说{STR_VAR_1}，\n你们说…\p酱油众：{STR_VAR_2}！\p酱油众：{STR_VAR_3}！\p酱油众：{STR_VAR_2}！\p酱油众：{STR_VAR_3}！\p主持：就是这样。当一个人对你说\n“{STR_VAR_1}”时…\p一定要回应， “{STR_VAR_2}\n{STR_VAR_3}！”\p这是独一无二的环！\n我能理解为什么人们成为了\l{STR_VAR_1}的酱油众！\p电视机前的观众们，加入我们吧！\n大家注意！\p主持：当我说{STR_VAR_1}，\n你说…\p酱油众：{STR_VAR_2}！\p酱油众：{STR_VAR_3}！\p酱油众：{STR_VAR_2}！\p酱油众：{STR_VAR_3}！\p主持：感谢大家的参与，\n狂野的{STR_VAR_1}的酱油众们！\l节目结束！下次再见！\p主持：当我说{STR_VAR_1}，\n你就说…\p酱油众：{STR_VAR_2}！\p酱油众：{STR_VAR_3}！$"

TVSpotTheCuties_Text_Intro::
    .string "抓住可爱的一瞬！\n宝可梦戴缎带！\p我亲爱的观众们，你们好！\p我知道你们都同意，形容戴着缎带\n的宝可梦就只有一个词：美丽！\p今天，我想和观众们分享\n一个当我在城里散步时看见的宝可梦。\p今天的可爱的宝可梦\n是{STR_VAR_1}的{STR_VAR_2}。$"

TVSpotTheCuties_Text_RibbonsLow::
    .string "由{STR_VAR_2}戴着的\n缎带数是{STR_VAR_3}。\p这告诉了我们\n{STR_VAR_1}有多么爱他的宝可梦。$"

TVSpotTheCuties_Text_RibbonsMid::
    .string "{STR_VAR_2}带着令人惊讶的\n{STR_VAR_3}缎带！\p它清楚地展现了{STR_VAR_1}\n对于宝可梦的执著！$"

TVSpotTheCuties_Text_RibbonsHigh::
    .string "{STR_VAR_2}戴着令人难以置信的\n{STR_VAR_3}缎带！\p它们展现了{STR_VAR_1}\n作为收集者的奉献！$"

TVSpotTheCuties_Text_RibbonIntro::
    .string "让我们仔细地看看这些\n由{STR_VAR_2}戴着的缎带。$"

TVSpotTheCuties_Text_RibbonChampion::
    .string "冠军缎带真是\n太漂亮啦。\p{STR_VAR_2}在进入名人纪念馆时\n获得了这款缎带。\p它见证了\n{STR_VAR_2}的勇敢。\p{STR_VAR_2}和冠军缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonCool::
    .string "帅气缎带真是\n太漂亮啦。\p{STR_VAR_2}因赢得了帅气华丽大赛\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的帅气。\p{STR_VAR_2}和帅气缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonBeauty::
    .string "漂亮缎带真是\n太漂亮啦。\p{STR_VAR_2}因赢得了漂亮华丽大赛\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的漂亮。\p{STR_VAR_2}和漂亮缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonCute::
    .string "可爱缎带真是\n太漂亮啦。\p{STR_VAR_2}因赢得了可爱华丽大赛\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的可爱。\p{STR_VAR_2}和可爱缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonSmart::
    .string "聪明缎带真是\n太漂亮啦。\p{STR_VAR_2}因赢得了聪明华丽大赛\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的聪明。\p{STR_VAR_2}和聪明缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonTough::
    .string "强壮缎带真是\n太漂亮啦。\p{STR_VAR_2}因赢得了强壮华丽大赛\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的强壮。\p{STR_VAR_2}和强壮缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonWinning::
    .string "胜利缎带真是\n太漂亮啦。\p{STR_VAR_2}因其在作战大厦的杰出表现\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的力量。\p{STR_VAR_2}和胜利缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonVictory::
    .string "优胜缎带真是\n太漂亮啦。\p{STR_VAR_2}因其在对战塔的杰出表现\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的惊人力量。\p{STR_VAR_2}和优胜缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonArtist::
    .string "艺术缎带真是\n太漂亮啦。\p{STR_VAR_2}因给艺术家做模特\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的明星气质。\p{STR_VAR_2}和艺术缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_RibbonEffort::
    .string "勤勉缎带真是\n太漂亮啦。\p{STR_VAR_2}因其投入的工作态度\n而获得了这款缎带。\p它见证了\n{STR_VAR_2}的决心。\p{STR_VAR_2}和勤勉缎带！\n多么契合的组合啊！$"

TVSpotTheCuties_Text_Outro::
    .string "…唉…\p缎带和宝可梦…\n真是太相称了！\p在我陶醉得晕倒之前，\n先向各位道声再会！$"

gTVPokemonNewsBattleFrontierText00::
    .string "大家好！\n现在是宝可梦新闻时间。\p我们将为大家带来战斗前线上\n最令人振奋的消息。$"

gTVPokemonNewsBattleFrontierText01::
    .string "训练师{STR_VAR_1}在\n对战塔单人斗室的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText02::
    .string "训练师{STR_VAR_1}在\n对战塔双人斗室的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText03::
    .string "训练师{STR_VAR_1}在\n对战塔多人斗室的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText04::
    .string "训练师{STR_VAR_1}在\n对战塔多人联机斗室的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText05::
    .string "训练师{STR_VAR_1}在\n在对战巨蛋单人作战比赛中\l创造了{STR_VAR_2}战连续冠军\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText06::
    .string "训练师{STR_VAR_1}在\n在对战巨蛋双人作战比赛中\l创造了{STR_VAR_2}战连续冠军\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText07::
    .string "训练师{STR_VAR_1}在\n对战工厂战斗交换单人挑战赛中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText08::
    .string "训练师{STR_VAR_1}在\n对战工厂战斗交换双人挑战赛中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText09::
    .string "训练师{STR_VAR_1}在\n对战水管战斗选择挑战赛中\l创造了{STR_VAR_2}间连续清关\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText10::
    .string "训练师{STR_VAR_1}在\n对战竞技场回合制KO比赛中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText11::
    .string "训练师{STR_VAR_1}在\n在对战宫殿单人战斗大厅的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText12::
    .string "训练师{STR_VAR_1}在\n在对战宫殿双人战斗大厅的挑战中\l创造了{STR_VAR_2}战全胜\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText13::
    .string "训练师{STR_VAR_1}在\n对战金字塔挑战赛中\l创造了{STR_VAR_2}层连续清关\l的记录。\p让我们祝贺{STR_VAR_1}的胜利！$"

gTVPokemonNewsBattleFrontierText14::
    .string "对于这三只宝可梦，{STR_VAR_1}，\n{STR_VAR_2}和{STR_VAR_3}！\p向你们卓越的表现\n表示祝贺！$"

gTVPokemonNewsBattleFrontierText15::
    .string "对于这两只宝可梦，\n{STR_VAR_1}和{STR_VAR_2}！\p向你们卓越的表现\n表示祝贺！$"

gTVPokemonNewsBattleFrontierText16::
    .string "{STR_VAR_1}！\p{STR_VAR_2}！\p{STR_VAR_3}！$"

gTVPokemonNewsBattleFrontierText17::
    .string "{STR_VAR_1}！\p向你卓越的表现\n表示祝贺！$"

gTVPokemonNewsBattleFrontierText18::
    .string "让我们期待{STR_VAR_1}及其忠心耿耿的宝可梦\n创下更多永垂青史的\l壮举吧！\p宝可梦新闻到此结束！$"

gTVWhatsNo1InHoennTodayText00::
    .string "今天丰缘的No.1是谁呢？\n对啦，又到这个时间啦！\p观众们，大家好！各位平时不论做什么\n是否都会倾注全力呢？\p让我们来看看\n今天最最努力的训练师吧！\p今天的No.1训练师\n非{STR_VAR_1}莫属啦！$"

gTVWhatsNo1InHoennTodayText01::
    .string "一天之内，{STR_VAR_1}在游戏中心转了\n{STR_VAR_2}次角子。\p玩的时候，{STR_VAR_1}自言自语道：\n“怎么轮到我的时候，\l转也不转呢…”\l哈，他多有趣啊！$"

gTVWhatsNo1InHoennTodayText02::
    .string "一天之内，{STR_VAR_1}在游戏中心\n玩了{STR_VAR_2}次\l轮盘赌。\p玩的时候，{STR_VAR_1}大喊道：\n“就让彩球来决定吧！”\p训练师目不转睛，\n脸上写满了专注。$"

gTVWhatsNo1InHoennTodayText03::
    .string "一天之内，{STR_VAR_1}同\n野生宝可梦战斗了{STR_VAR_2}次！\p很显然，{STR_VAR_1}的宝可梦\n已经成长得无比强大。\p它们看起来渴望\n随时随地投入战斗！$"

gTVWhatsNo1InHoennTodayText04::
    .string "一天之内，{STR_VAR_1}开动了\n{STR_VAR_2}次树果搅拌机！\p到最后，{STR_VAR_1}自己\n都有点晕晕乎乎的。\p训练师走路踉踉跄跄\n就像个搅拌机！$"

gTVWhatsNo1InHoennTodayText05::
    .string "一天之内，{STR_VAR_1}种了\n{STR_VAR_2}棵果树！\p结果搞得{STR_VAR_1}\n满身灰土。\p训练师种上树的地方，\n无数花朵竞相绽放。\p据说这种花朵\n有平复情绪的效果。$"

gTVWhatsNo1InHoennTodayText06::
    .string "一天之内，{STR_VAR_1}拾了\n{STR_VAR_2}枚树果！\p{STR_VAR_1}的包包装满了\n树果，训练师真是\l举步维艰啊！$"

gTVWhatsNo1InHoennTodayText07::
    .string "一天之内，{STR_VAR_1}获得了\n{STR_VAR_2}个对战点数！\p之后发现{STR_VAR_1}正在犹豫\n是否要用对战点数兑换\l酷酷的装备或\l靓靓的装饰。\p据说训练师考虑的时候\n咧嘴直笑。$"

gTVWhatsNo1InHoennTodayText08::
    .string "哇，这难道不值得庆贺吗！\p{STR_VAR_1}！\n你是今天的No.1训练师也！\p观众朋友们，\n让我们学习{STR_VAR_1}的勇气和信心！\l你们，也能成为每天的No.1！$"

TVSecretBaseSecrets_Text_Intro::
    .string "秘密基地大揭秘！\p训练师在秘密基地\n都做些什么呢？\p今天，让我们来调查一下{STR_VAR_1}的\n秘密基地吧。\p哦？看起来{STR_VAR_2}已经\n捷足先登啦。\p让我们来瞧一眼！\p{STR_VAR_2}会做些什么？$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
    .string "{STR_VAR_2}接下来会做什么？$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
    .string "现在，{STR_VAR_2}又会干什么呢？$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
    .string "最后，离开之前，{STR_VAR_2}\n在{STR_VAR_1}的秘密基地里\l逛了{STR_VAR_3}步。$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
    .string "嗯…\p看起来{STR_VAR_1}的秘密基地\n并没有引起{STR_VAR_2}的兴趣…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
    .string "{STR_VAR_2}看起来对{STR_VAR_1}的\n秘密基地非常喜爱。$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
    .string "{STR_VAR_2}看起来成了\n{STR_VAR_1}秘密基地的\l骨灰级粉丝啦。$"

TVSecretBaseSecrets_Text_Outro::
    .string "观众们是不是对\n{STR_VAR_1}的秘密基地也有兴趣呢？\p请继续锁定这个频道，和我们一同参观其他\n秘密基地！非常感谢您的收看！$"

TVSecretBaseSecrets_Text_StoppedMoving1::
    .string "游客停下了脚步！\p完全不想离开！\p{STR_VAR_1}的秘密基地\n真的这么吸引人吗？$"

TVSecretBaseSecrets_Text_StoppedMoving2::
    .string "游客停了下来！\p完全不能动弹！\p他累了吗？\n会越来越累吗？$"

TVSecretBaseSecrets_Text_UsedChair::
    .string "他在椅子上坐了下来！\n确实坐下了！\p他看起来很高兴！\p那把椅子坐起来\n一定很舒服！$"

TVSecretBaseSecrets_Text_UsedBalloon::
    .string "他向气球冲去！\p气球爆了！\n啪的一声，噢，天呐！\p吓了\n他一跳！$"

TVSecretBaseSecrets_Text_UsedTent::
    .string "游客走进了帐篷！\p他四处奔跑！\p噢，我的天，他竟然胡跑乱闹！\p他对帐篷的巨大\n还真是感到吃惊呢！$"

TVSecretBaseSecrets_Text_UsedPlant::
    .string "游客在\n观赏盆栽！\p原来他还有这么\n高雅的情趣啊！$"

TVSecretBaseSecrets_Text_UsedGoldShield::
    .string "游客在金色的盾前\n观赏起来！\p他的眼睛散发出\n闪耀的光芒！$"

TVSecretBaseSecrets_Text_UsedSilverShield::
    .string "游客在银色的盾前\n观赏起来！\p他把眼睛睁得大大的！$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
    .string "游客在玻璃装饰品前\n观赏起来！\p噢，不！\p他上去摸了！\p那样会在上面\n粘满指纹的…$"

TVSecretBaseSecrets_Text_UsedTV::
    .string "游客在看电视！\p看来我们有个狂热的电视迷！$"

TVSecretBaseSecrets_Text_UsedMudBall::
    .string "游客在泥球上跳舞！\p他看起来挺开心的！$"

TVSecretBaseSecrets_Text_UsedBag::
    .string "…哦？\p游客将手伸进背包\n找呀找呀！\p拿出了\n{STR_VAR_2}！\p看他举着{STR_VAR_2}\n笑的样子！\p活像在做电视广告！$"

TVSecretBaseSecrets_Text_UsedCushion::
    .string "游客抓起一个垫子并且…$"

TVSecretBaseSecrets_Text_HitCushion::
    .string "…开始摔打！\p他有非常大的压力吗？$"

TVSecretBaseSecrets_Text_HuggedCushion::
    .string "…紧紧地抱着它！\p难道他有什么值得\n高兴的事？$"

TVSecretBaseSecrets_Text_BattledWon::
    .string "游客在和{STR_VAR_1}\n说些什么！\p他们好像要\n进行对战了！\p接下来…\p游客胜利了！\n他在客场赢得了比赛！\p游客跳起了\n胜利之舞！$"

TVSecretBaseSecrets_Text_BattledLost::
    .string "游客在和{STR_VAR_1}\n说些什么！\p他们好像要\n进行对战了！\p接下来…\p胜者是{STR_VAR_1}！\n游客输掉了！\p他显得十分沮丧！$"

TVSecretBaseSecrets_Text_DeclinedBattle::
    .string "游客在和{STR_VAR_1}\n说些什么！\p他们好像要\n进行对战了！\p接下来…\p噢，游客拒绝了！\p他们并没有战斗！\p他认为{STR_VAR_1}没有\n吸引力了吗？$"

TVSecretBaseSecrets_Text_UsedPoster::
    .string "游客正聚精会神地\n盯着一张海报！\p那是他喜欢的\n海报吗？\p…但是… 他的眼神中\n带着一丝不安。$"

TVSecretBaseSecrets_Text_UsedNoteMat::
    .string "游客站在了音符地毯上！\p…唔…\n他谱写出了一段不可思议的乐章！$"

TVSecretBaseSecrets_Text_BattledDraw::
    .string "游客在和{STR_VAR_1}\n说些什么！\p他们好像要\n进行对战了！\p接下来…\p是个平局！\n什么都没解决！\p两个训练师\n似乎都很懊悔！$"

TVSecretBaseSecrets_Text_UsedSpinMat::
    .string "游客登上了\n旋转铺垫！\p看起来晕晕乎乎的！\p他在那摇摇晃晃的！\n当心！$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
    .string "游客拿出来\n一个沙制装饰品！\p噢！\p它碎掉了！\n已经散架了！\p游客觉得\n很羞愧！$"

TVSecretBaseSecrets_Text_UsedDesk::
    .string "游客用手来\n擦桌子！\p显然，他不允许\n有灰尘存在！\p他还真是出人意料的\n爱干净呢！$"

TVSecretBaseSecrets_Text_UsedBrick::
    .string "游客正盯着砖块看呢！\p也许他正在考虑\n与这个砖块相配的物品呢。$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
    .string "游客直接穿过\n了固体板。\p他一直低着头。\p他还真是出人意料地\n害羞和谨慎啊！$"

TVSecretBaseSecrets_Text_UsedFence::
    .string "游客聚精会神地\n看着围栏！\p突然闪现了\n制作陷阱的灵感？$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
    .string "游客登上了\n闪烁的铺垫！\p他摆出了各种各样\n的姿势！\p他在幻想着\n自己是个偶像吧！$"

TVSecretBaseSecrets_Text_UsedTire::
    .string "游客紧紧\n凝视着轮胎！\p他是在考虑那是\n用于何种汽车的吗？$"

TVSecretBaseSecrets_Text_UsedStand::
    .string "游客爬上了高台！\p他从上面纵览着\n{STR_VAR_1}的BASE！\p而且…\p朝下面喊了起来！$"

TVSecretBaseSecrets_Text_BrokeDoor::
    .string "游客面向\n一扇易碎门！\p大声地笑着！$"

TVSecretBaseSecrets_Text_UsedDoll::
    .string "游客在和玩偶说话！\p…稍微有点恐怖…$"

TVSecretBaseSecrets_Text_UsedSlide::
    .string "游客爬上了\n滑梯！\p并且…\p滑了下来！\p看来他度过了\n快乐的时光！$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
    .string "游客爬上了\n滑梯！\p而且…\p顺着梯子\n又回来了！\p他害怕了吗？$"

TVSecretBaseSecrets_Text_UsedJumpMat::
    .string "游客登上了\n跳床！\p跳一下！\p两下！\p完美着陆！\p为他鼓掌！\n多棒的个人演出！$"

gTVSafariFanClubText00::
    .string "原野区爱好者俱乐部！\p采访者：怎么，\n开始扔原野球了？\p我现在就在充满了\n珍稀宝可梦的原野区里！\p来吧\n一起去找饲养员谈谈！\p你觉得原野区的\n训练师都怎么样啊？$"

gTVSafariFanClubText01::
    .string "导游：大家都十分\n努力。\p特别是{STR_VAR_1}。\p为什么？因为{STR_VAR_1}抓住了\n{STR_VAR_2}宝可梦。$"

gTVSafariFanClubText02::
    .string "在那时用{STR_VAR_2}，我觉得\n那个训练师对能量方块很精通。$"

gTVSafariFanClubText03::
    .string "连一个能量方块\n都没有用！\p真是太厉害了。$"

gTVSafariFanClubText04::
    .string "采访记者：这样啊\p听起来{STR_VAR_1}是个\n非常稳重的捕获专家呢！\p导游：我希望训练师能够回来\n让我们欣赏到强大的技能。$"

gTVSafariFanClubText05::
    .string "导游：这次各位的表现\n不是很好。\p尤其是{STR_VAR_1}，相当糟糕。\p为什么，因为他仅仅\n抓到了{STR_VAR_2} 宝可梦。$"

gTVSafariFanClubText06::
    .string "导游：这次各位的表现\n不是很好。\p尤其是{STR_VAR_1}，相当糟糕。\p为什么？因为他没有抓到\n宝可梦。一只也没有！$"

gTVSafariFanClubText07::
    .string "那个训练师确实有使用能量方块。\n我想那时是用了{STR_VAR_2}。\p不过，我倒是希望那个训练师\n变得更擅长这个。$"

gTVSafariFanClubText08::
    .string "我想那个训练师用能量方块\n的话运气会好些，可惜\l那时他完全不用。$"

gTVSafariFanClubText09::
    .string "采访者：是吗？\p似乎我们的{STR_VAR_1}\n想要原野区特训啊。\p导游：希望那个训练师能\n多来几次，慢慢掌握窍门。$"

gTVSafariFanClubText10::
    .string "采访者：没错！\n勇敢面对挑战是最重要的！\p电视机前的观众们，\n快来挑战原野区活动吧！\p下次节目同一时间，再会！$"

ContestLiveUpdates_Text_Intro::
    .string "“宝可梦华丽大赛结果速报！”\p主持：好的！\p{STR_VAR_1}华丽大赛的会场报告，\l结果刚刚出来了。\n会场似乎还有很多观众\n还不想离开的样子。\p观众：{STR_VAR_2}！\p观众：{STR_VAR_3}！\p主持：正如你们所听到的，\n获胜的是{STR_VAR_3}的宝可梦\l{STR_VAR_2}。\p观众：{STR_VAR_2}！\n你是最棒的！\p观众：{STR_VAR_3}！\n了不起！\p主持：好的，现在我们来听听看\n观众们对这场华丽大赛的感想。$"

ContestLiveUpdates_Text_WonBothRounds::
    .string "观众：{STR_VAR_2}在第一和第二阶段\n的审查都是第一！\p{STR_VAR_2}获得了胜利！$"

ContestLiveUpdates_Text_BetterRound2::
    .string "观众：{STR_VAR_2}在第一阶段\n表现的不是很好，但是\l在第二阶段又扳了回来！\p奇迹降临在了\n{STR_VAR_2}的身上。好耶！$"

ContestLiveUpdates_Text_EqualRounds::
    .string "观众：{STR_VAR_2}在第一和\n第二阶段\l始终都表现得很好。\p{STR_VAR_3}和{STR_VAR_2}，\n真是一对好搭档！$"

ContestLiveUpdates_Text_BetterRound1::
    .string "观众：从{STR_VAR_1}的角度来看，\n{STR_VAR_2}很杰出。\p我希望下次它能\n更有吸引力。$"

ContestLiveUpdates_Text_GotNervous::
    .string "观众：当{STR_VAR_2}紧张时，\n我就会不停的\l呐喊，鼓励它。\p我会向{STR_VAR_2}\n说，“恭喜了！”$"

ContestLiveUpdates_Text_StartledFoes::
    .string "观众：{STR_VAR_2}的吸引力\n真让人吃惊！\p{STR_VAR_2}，你真棒！$"

ContestLiveUpdates_Text_UsedCombo::
    .string "观众：{STR_VAR_2}的连续技\n有着极为出色的吸引力！\p它震动了我的心！$"

ContestLiveUpdates_Text_ExcitingAppeal::
    .string "观众：{STR_VAR_2}的吸引力\n大幅度上升啦！$"

ContestLiveUpdates_Text_WasCool::
    .string "{STR_VAR_2}！\n太帅了！$"

ContestLiveUpdates_Text_WasBeautiful::
    .string "{STR_VAR_2}！\n好漂亮啊！$"

ContestLiveUpdates_Text_WasCute::
    .string "{STR_VAR_2}！\n真可爱！$"

ContestLiveUpdates_Text_WasSmart::
    .string "{STR_VAR_2}！\n真聪明！$"

ContestLiveUpdates_Text_WasTough::
    .string "{STR_VAR_2}！\n好强壮啊！$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
    .string "观众：{STR_VAR_2}让我的心\n到现在还怦怦直跳！$"

ContestLiveUpdates_Text_VeryCool::
    .string "{STR_VAR_2}！\n你是最帅气的！$"

ContestLiveUpdates_Text_VeryBeautiful::
    .string "{STR_VAR_2}！\n你是最漂亮的！$"

ContestLiveUpdates_Text_VeryCute::
    .string "{STR_VAR_2}！\n你是最可爱的！$"

ContestLiveUpdates_Text_VerySmart::
    .string "{STR_VAR_2}！\n你是最聪明的！$"

ContestLiveUpdates_Text_VeryTough::
    .string "{STR_VAR_2}！\n你是最强壮的！$"

ContestLiveUpdates_Text_TookBreak::
    .string "观众：就算在{STR_VAR_2}\n表演结束后休息的时候，\l我也忍不住一直看着它。\p我完全被{STR_VAR_2}吸引住了。$"

ContestLiveUpdates_Text_GotStartled::
    .string "观众：看到{STR_VAR_2}被\n别的宝可梦吓到，\l我都快要哭了。\p{STR_VAR_2}，你没问题的！\n打起精神来！$"

ContestLiveUpdates_Text_MoveWonderful::
    .string "观众：啊…\n是{STR_VAR_2}的{STR_VAR_3}！\l{STR_VAR_2}的{STR_VAR_3}！\l{STR_VAR_2}的{STR_VAR_3}！\l多么完美的表演啊！$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
    .string "主持人：看啊，观众席上\n到处都是{STR_VAR_1}的支持者！\p另外还有另一只宝可梦\n{STR_VAR_2}的{STR_VAR_3}，\l给我留下了不错的印象。\p{STR_VAR_2}的{STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
    .string "在比赛的第二阶段，由于它\n过于紧张，什么也没有做出来。\p希望下回能看到\n{STR_VAR_1}的表现。$"

ContestLiveUpdates_Text_LastInBothRounds::
    .string "在比赛的第一和第二阶段\n它都成为了最后一名，\p希望{STR_VAR_1}能够再练习一下\n{STR_VAR_2}，下回能够一雪前耻，\l取得佳绩。$"

ContestLiveUpdates_Text_NotExcitingEnough::
    .string "它没能作出合适的表演，\n抓住观众的心。\p希望下回{STR_VAR_1}能够学会\n如何抓住观众，\l点燃他们的热情。$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
    .string "虽然它在第一阶段取得了\n第一名，但第二阶段的表演\l却并不顺利。\p看来这对它自己来说\n也是一种屈辱。\p我想{STR_VAR_1}也正在学习\n如何能作出更加吸引人的表演吧。$"

ContestLiveUpdates_Text_NeverExciting::
    .string "在第二阶段中，观众在它表演时\n从未表现出激动的情绪。\p希望它能不再担心\n其它宝可梦的演出，并\l学习一下如何能使自己更加吸引观众。$"

ContestLiveUpdates_Text_LostBySmallMargin::
    .string "虽然只差一点，但它还是\n输给了{STR_VAR_1}的{STR_VAR_2}。\p在距成功如此近的地方\n跌倒，一定很不甘心。\p就算{STR_VAR_3}现在哭了，\n我想也是情理之中吧。$"

ContestLiveUpdates_Text_RepeatedAppeals::
    .string "它一遍遍地重复同样的表演，\n令裁判很失望。\p无论在什么华丽大赛中，这样的错误\n都是不可原谅的。\l而现在，它已经付出了代价。\p对这样拙劣的表演，\n{STR_VAR_1}自己也感觉罪孽深重吧。$"

ContestLiveUpdates_Text_ValiantEffortButLost::
    .string "{STR_VAR_1}显然已经付出了极大的努力\n但是…\p到了最后，却还是一无所获。\p但愿{STR_VAR_1}能从这次的失败中学到\n一些知识，今后好好地利用它们。$"

ContestLiveUpdates_Text_Outro::
    .string "在节目的最后，让我们\n像以前一样欢送胜利者吧！\p这次的胜者是\n{STR_VAR_1}和{STR_VAR_2}！\p主持：大家准备好了吗？\n好，开始！\p观众：{STR_VAR_1}！{STR_VAR_2}！\n恭喜你们！\l你们是华丽大赛的优胜者！$"

gTVPokemonBattleUpdateText00::
    .string "“宝可梦对战速递！”\p为你即时播报宝可梦\n对战的信息！$"

gTVPokemonBattleUpdateText01::
    .string "训练师{STR_VAR_1}和{STR_VAR_2}\n在{STR_VAR_3}战斗中相遇了，\p比赛以{STR_VAR_1}的胜利而结束！$"

gTVPokemonBattleUpdateText02::
    .string "对战中，{STR_VAR_1}的{STR_VAR_2}使用{STR_VAR_3}时\l发挥出了可怕的力量！$"

gTVPokemonBattleUpdateText03::
    .string "{STR_VAR_1}的{STR_VAR_2}表现得\n不尽人意。$"

gTVPokemonBattleUpdateText04::
    .string "恭喜你取得了胜利，\n{STR_VAR_1}！\p这次打败了{STR_VAR_2}，\n希望下次你还能取得更好的成绩！\p我们“宝可梦对战速递！”的\n篇章到此结束！$"

gTVPokemonBattleUpdateText05::
    .string "{STR_VAR_1}队和{STR_VAR_2}队\n在多人对战中相遇了。\p这场比赛以{STR_VAR_1}队的胜利结束。$"

gTVPokemonBattleUpdateText06::
    .string "在对战中，{STR_VAR_1}队的{STR_VAR_2}\n使用{STR_VAR_3}时\l发挥出了可怕的力量。$"

gTVPokemonBattleUpdateText07::
    .string "{STR_VAR_2}队的{STR_VAR_3}不尽人意的表现\n导致了队伍的失败。\p恭喜你的队伍取得胜利，\n{STR_VAR_1}！\p而对于{STR_VAR_2}队，虽然这次失败了，\n但希望下次你们能取得更好的成绩！\p我们“宝可梦对战速递！”的\n环节到此结束！$"

GabbyAndTy_Text_GabbyPreFirstBattle::
    .string "玛丽：啊！我们在这里发现了\n一名看上去非常强大的训练师！\p好的，镜头转过来！\n采访开始。$"

GabbyAndTy_Text_GabbyIntro::
    .string "玛丽：啊！你是{PLAYER}！你好啊！\n还记得我们吧？\p能告诉我们你已经成长到\n多么强了吗？好的，说几句吧！$"

GabbyAndTy_Text_GabbyDefeatFirstTime::
    .string "玛丽：我的眼睛并没有说谎！\n我的确发现了一位惊人的训练师！$"

GabbyAndTy_Text_WhoAreYouInterview::
    .string "玛丽：真厉害！真厉害！\n能告诉我你是谁吗？\p一看到你我就知道\n我们发现了一位非凡的人！\p啊，我解释一下。\n我们四处旅行，采访\l各式各样的训练师。\p能占用你一些时间\n做一次采访吗？$"

GabbyAndTy_Text_QuoteFromLastInterview::
    .string "玛丽：“{STR_VAR_1}！”\p记得吗？上次的对战结果揭晓的时候\n你就是这么说的。\p我永远、永远都不会忘记的！$"

GabbyAndTy_Text_YouStompedUsInterviewAgain::
    .string "上次我们战斗的时候，还没等我们\n整好攻势就被你打败了…\p不管怎样，你今天愿意\n再接受我们的采访吗？$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain::
    .string "记不记得上次我们战斗的时候\n你对我们扔精灵球？\p我们吓了一跳！那之后我们就\n把这都告诉了大家！\p不管怎样，你今天愿意\n再接受我们的采访吗？$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain::
    .string "上次我们战斗的时候，你使用道具\n得心应手的感觉给了我们很深的印象。\p不管怎样，你今天愿意\n再接受我们的采访吗？$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain::
    .string "上次我们战斗的时候，\n我们干得似乎还不错。\p不管怎样，你今天愿意\n再接受我们的采访吗？$"

GabbyAndTy_Text_InterviewAgain::
    .string "不管怎样，你今天愿意\n再接受我们的采访吗？$"

GabbyAndTy_Text_DescribeYourFeelings::
    .string "真的可以吗？\n谢谢！\p好的，那就讲讲对我们战斗的\n感想吧。请尽量简短一点。\l开始吧！$"

GabbyAndTy_Text_PerfectWellBeSeeingYou::
    .string "玛丽：嗯，好！\n完美的总结啊！\p我直觉地感到这次的节目\n会非常成功。\p肯定有机会让电视台\n播放它的，注意一下吧！\p好了！\n下回再见！$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut::
    .string "玛丽：唔…\p那好吧，不过别放弃！\n我们会一直看着你的！$"

GabbyAndTy_Text_KeepingAnEyeOutForYou::
    .string "玛丽：我们会\n一直看着你的！$"

GabbyAndTy_Text_GabbyNotEnoughMons::
    .string "玛丽：哪里有带着很多宝可梦的\n强大的训练师呢？$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime::
    .string "玛丽：哇，你果然不一般啊！\p自从上次我们战斗以来，你\n成长了不少——确实不少。\p看来我们选中你的时候\n并没有看错。\p那，不管怎样，\n这一回你愿意接受\l我们的采访吗？$"

GabbyAndTy_Text_GabbyDefeat::
    .string "玛丽：真是激烈的战斗啊！\n都拍下来了吧？$"

GabbyAndTy_Text_TyPreFirstBattle::
    .string "达伊：嘿，看！看上去是个\n很强的训练师！\l镜头转过去了！$"

GabbyAndTy_Text_TyIntro::
    .string "达伊：嘿，这儿！\n我记得你！\p我会把这里的战斗\n用这台相机记录下来的！$"

GabbyAndTy_Text_TyPostBattle::
    .string "达伊：你是个天才！\n这肯定是最棒的镜头了！$"

GabbyAndTy_Text_TyNotEnoughMons::
    .string "达伊：你只带了这一只宝可梦吗？\p要是有更多宝可梦的话，\n就能拍出好镜头了…$"

GabbyAndTy_Text_TyDefeatFirstTime::
    .string "达伊：哈，我们发现了厉害的训练师！\n这样我们又有头条了！$"

GabbyAndTy_Text_TyDefeat::
    .string "达伊：哈，成了！\n整场战斗都拍下来了！$"

gTVInSearchOfTrainersText00::
    .string "搜寻训练师…\p玛丽：大家好！现在我们\n正在{STR_VAR_1}周边地区，\p我们正在寻找拥有天分\n和发展潜力的人。\p今天，我们的镜头将指向\n训练师{PLAYER}。\p这位训练师\n引发了我们的好奇心。$"

gTVInSearchOfTrainersText01::
    .string "我们以前也跟{PLAYER}进行过对战，\n可以明显地看出这位训练师\l较之前有了极大的进步。\p当我们发现这位训练师的时候，\n我们就确定这一定会是一位不凡的人！$"

gTVInSearchOfTrainersText02::
    .string "要看出一个训练师有多么强大，\n最好的办法就是…\p啊，也是最快的办法，就是对战。\n于是我们就开始了调查！\p… …\p就这样，我们在对战中\n输给了{PLAYER}。\p在那决定性的一击中，\n我们被打得体无完肤！\p毫无疑问，{PLAYER}非常强…\p下面是我们跟这位训练师\n对战后的感想。$"

gTVInSearchOfTrainersText03::
    .string "{STR_VAR_1}和{STR_VAR_3}的组合\n可以用完美来形容！\p看看他们吧——{STR_VAR_1}和\n{STR_VAR_3}——在激烈的战斗中\l无私地互相支持着对方…\p这是多么完美的一幕！\p{STR_VAR_2}是这位训练师\n在对战中最后使用的一个技能，\p{STR_VAR_2}就是{STR_VAR_1}\n和{STR_VAR_3}的友谊的证明！$"

gTVInSearchOfTrainersText04::
    .string "…经过那一战，我对自己\n都没什么信心了，\p我们还没展开进攻\n就已经被打败了。\l啊…呜呜…\p无论如何，{PLAYER}的战斗\n是非常值得一看的，\p希望能有勇敢的训练师\n向{PLAYER}发起挑战。$"

gTVInSearchOfTrainersText05::
    .string "在这里我只有一句话要说\n不要在训练师对战中\l扔精灵球！\p{PLAYER}确实很强，但却好像\n没有理解对战的基本规则。\p在此，我要向我的观众们请求一件事情：\p如果你们见到{PLAYER}，请一定要\n告诫一下这位训练师！$"

gTVInSearchOfTrainersText06::
    .string "{PLAYER}非常擅长阅读\n对手的行动。\p使用道具的时机\n非常合理有效！$"

gTVInSearchOfTrainersText07::
    .string "老实说，我觉得\n其实我也挺强的。\p虽然最后输了，\n也不失为一场精彩的比赛。\p不过对我都要陷入苦战的话，\n{PLAYER}，你要走的路还很长呢！$"

gTVInSearchOfTrainersText08::
    .string "战斗结束后，我们请{PLAYER}\n做了简短的感想。\p训练师答道：“{STR_VAR_1}。”\p{PLAYER}的宝可梦{STR_VAR_2}和\n{STR_VAR_3}…\l还有“{STR_VAR_1}”…\p嗯，真是意味深长\n的发言啊！\p确实好的训练师\n就能作出好的发言！\p今天就到这里为止了！\n下次同一时间，再见！$"

ContestLadyShow_Text_Intro::
    .string "“宝可梦华丽大赛结果速报！”\p主持：现在插播一则消息！\p我们从会场现场为你带来\n刚刚结束的{STR_VAR_1}大赛的结果！\p观众：？！！！！\p主持：华丽大赛参与者\n似乎正往这边走过来了！\p电视机前的朋友们，现在我就\n为你们进行即时的采访！\p观众：？！！！！\n？！！！！$"

ContestLadyShow_Text_Won::
    .string "主持：打扰了！\p恭喜您获得了优胜！\n今天您获胜的决定性因素是什么呢？\p美女：我们今天尽了最大努力，\n我，还有我的{STR_VAR_2}！\p但若不是有选美前大家\n对我们的协助，我们也无法\l走到现在这一步！\p主持：您最想与之分享\n您的快乐的人是谁呢？\l请在这里大声说出来吧！\p美女：喂！\p{STR_VAR_3}！你在看吗？\n我们做到了！\l谢谢你！$"

ContestLadyShow_Text_Lost::
    .string "主持：打扰了！\p这次真是遗憾呢！\n您有什么评论要说吗？\p美女：真的非常可惜…\n我和我的{STR_VAR_2}都已经尽力了…\p但我还是觉得我们辜负了\n期待着我们的人。\p主持：嗯，确实着色上\n是有些不理想。\p美女：{STR_VAR_3}，对不起…\n下次我一定会更努力的…\l呜…呜呜…哇啊…\p观众：(议论纷纷)\p主持：啊，哦…惨了…\p那么今天的节目到此结束！\n感谢您的收看，再见！$"

ContestLadyShow_Text_LostBadly::
    .string "主持：打扰了！\n欢迎收看电视直播！\p你认为今天华丽大赛的表现怎样呢？\p美女：什么都不顺利啊…\n因为某种原因，我的{STR_VAR_2}\l完全吸引不到任何人的目光。\p主持：抱歉这么说，不过你的宝可梦\n好像还缺少些特色。\p美女：… … … … … …\n呜…呜呜…哇啊…\p观众：(议论纷纷)\p主持：啊，哦…惨了…\p那么今天的节目到此结束！\n感谢您的收看，再见！$"
