SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
    .string "海底火山爆发后，\n从深海中升起，\p火山口露出海面，\n被雨水填满。\p琉璃市的历史\n就由此开端。$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
    .string "连接琉璃市和外界的\n洞窟…\p就好像那洞窟是为了\n防止什么离开而建造的。\p这只是我的想象吗？$"

