PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
    .string "千里是镇子上新的\n道馆馆主，\p他把全家\n从很远的地方叫来了。$"

PetalburgCity_House2_Text_BattledNormanOnce:
    .string "我曾经挑战过千里，\n但是，唉，他太强了。\p怎么说呢？\p我感觉他是\n为宝可梦而生的。$"

