PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
    .string "旅行太美妙了！\p我年轻的时候\n经常去游泳登山！$"

PetalburgCity_House1_Text_GoOnAdventure:
    .string "哎…\p我要是能和宝可梦\n一起去探险多好…\p爬过潮湿的草丛…\n攀登崎岖的高山…\p穿越波涛汹涌的大海…\n在黑暗的洞窟里散步…\p然后，偶尔泛出点\n乡愁…\p旅行真的太美妙了！$"

