BattleFrontier_Lounge1_MapScripts::
	.byte 0

@ NPC that rates pokemon based on their IVs
BattleFrontier_Lounge1_EventScript_Breeder::
	lock
	faceplayer
	call_if_unset FLAG_MET_BATTLE_FRONTIER_BREEDER, BattleFrontier_Lounge1_EventScript_BreederIntro
	call_if_set FLAG_MET_BATTLE_FRONTIER_BREEDER, BattleFrontier_Lounge1_EventScript_AlreadyMetBreeder
	setflag FLAG_MET_BATTLE_FRONTIER_BREEDER
	goto BattleFrontier_Lounge1_EventScript_ChooseMonToShowBreeder
	end

BattleFrontier_Lounge1_EventScript_ChooseMonToShowBreeder::
	special ChoosePartyMon
	waitstate
	compare VAR_0x8004, 255
	goto_if_ne BattleFrontier_Lounge1_EventScript_ShowMonToBreeder
	compare VAR_0x8004, 255
	goto_if_eq BattleFrontier_Lounge1_EventScript_CancelMonSelect
	end

BattleFrontier_Lounge1_EventScript_BreederIntro::
	msgbox BattleFrontier_Lounge1_Text_PokemonBreederIntro, MSGBOX_DEFAULT
	return

BattleFrontier_Lounge1_EventScript_AlreadyMetBreeder::
	msgbox BattleFrontier_Lounge1_Text_LetsLookAtYourPokemon, MSGBOX_DEFAULT
	return

@ BufferVarsForIVRater buffers the following values
@ VAR_0x8005: Sum of the mons IVs
@ VAR_0x8006: Stat id of highest IV stat
@ VAR_0x8007: IV of the highest IV stat
BattleFrontier_Lounge1_EventScript_ShowMonToBreeder::
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq BattleFrontier_Lounge1_EventScript_ShowEggToBreeder
	special BufferVarsForIVRater
	compare VAR_0x8005, 90   @ Average of 15
	goto_if_le BattleFrontier_Lounge1_EventScript_AverageTotalIVs
	compare VAR_0x8005, 120  @ Average of 20
	goto_if_le BattleFrontier_Lounge1_EventScript_AboveAverageTotalIVs
	compare VAR_0x8005, 150  @ Average of 25
	goto_if_le BattleFrontier_Lounge1_EventScript_HighTotalIVs
	compare VAR_0x8005, 151  @ Average of > 25
	goto_if_ge BattleFrontier_Lounge1_EventScript_VeryHighTotalIVs
	end

BattleFrontier_Lounge1_EventScript_ShowEggToBreeder::
	msgbox BattleFrontier_Lounge1_Text_EvenICantTell, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_ChooseMonToShowBreeder
	end

@ Comment on the highest IV stat
BattleFrontier_Lounge1_EventScript_HighestIVStat::
	compare VAR_0x8006, STAT_HP
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVHP
	compare VAR_0x8006, STAT_ATK
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVAtk
	compare VAR_0x8006, STAT_DEF
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVDef
	compare VAR_0x8006, STAT_SPEED
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVSpeed
	compare VAR_0x8006, STAT_SPATK
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVSpAtk
	compare VAR_0x8006, STAT_SPDEF
	goto_if_eq BattleFrontier_Lounge1_EventScript_HighestIVSpDef
	end

@ Comment on the highest IV value
BattleFrontier_Lounge1_EventScript_HighestIVValue::
	compare VAR_0x8007, 15
	goto_if_le BattleFrontier_Lounge1_EventScript_HighestIVLow
	compare VAR_0x8007, 25
	goto_if_le BattleFrontier_Lounge1_EventScript_HighestIVMid
	compare VAR_0x8007, 30
	goto_if_le BattleFrontier_Lounge1_EventScript_HighestIVHigh
	compare VAR_0x8007, 31
	goto_if_ge BattleFrontier_Lounge1_EventScript_HighestIVMax
	end

BattleFrontier_Lounge1_EventScript_EndBreederComments::
	release
	end

BattleFrontier_Lounge1_EventScript_AverageTotalIVs::
	msgbox BattleFrontier_Lounge1_Text_AverageAbility, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVStat
	end

BattleFrontier_Lounge1_EventScript_AboveAverageTotalIVs::
	msgbox BattleFrontier_Lounge1_Text_BetterThanAverageAbility, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVStat
	end

BattleFrontier_Lounge1_EventScript_HighTotalIVs::
	msgbox BattleFrontier_Lounge1_Text_ImpressiveAbility, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVStat
	end

BattleFrontier_Lounge1_EventScript_VeryHighTotalIVs::
	msgbox BattleFrontier_Lounge1_Text_OutstandingAbility, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVStat
	end

BattleFrontier_Lounge1_EventScript_HighestIVHP::
	msgbox BattleFrontier_Lounge1_Text_BestAspectHP, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVAtk::
	msgbox BattleFrontier_Lounge1_Text_BestAspectAtk, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVDef::
	msgbox BattleFrontier_Lounge1_Text_BestAspectDef, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVSpeed::
	msgbox BattleFrontier_Lounge1_Text_BestAspectSpeed, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVSpAtk::
	msgbox BattleFrontier_Lounge1_Text_BestAspectSpAtk, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVSpDef::
	msgbox BattleFrontier_Lounge1_Text_BestAspectSpDef, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_HighestIVValue
	end

BattleFrontier_Lounge1_EventScript_HighestIVLow::
	msgbox BattleFrontier_Lounge1_Text_StatRelativelyGood, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_EndBreederComments
	end

BattleFrontier_Lounge1_EventScript_HighestIVMid::
	msgbox BattleFrontier_Lounge1_Text_StatImpressive, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_EndBreederComments
	end

BattleFrontier_Lounge1_EventScript_HighestIVHigh::
	msgbox BattleFrontier_Lounge1_Text_StatOutstanding, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_EndBreederComments
	end

BattleFrontier_Lounge1_EventScript_HighestIVMax::
	msgbox BattleFrontier_Lounge1_Text_StatFlawless, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge1_EventScript_EndBreederComments
	end

BattleFrontier_Lounge1_EventScript_CancelMonSelect::
	msgbox BattleFrontier_Lounge1_Text_NoTimeForMyAdvice, MSGBOX_DEFAULT
	release
	end

BattleFrontier_Lounge1_EventScript_Boy1::
	msgbox BattleFrontier_Lounge1_Text_SaidMyMonIsOutstanding, MSGBOX_NPC
	end

BattleFrontier_Lounge1_EventScript_Boy2::
	msgbox BattleFrontier_Lounge1_Text_DidntDoAnythingSpecialRaisingIt, MSGBOX_NPC
	end

BattleFrontier_Lounge1_Text_PokemonBreederIntro:
    .string "我培养宝可梦有70年了！\n我被人们尊为传奇性的\l顶级宝可梦饲养员！\p当你变得和我一样成熟时，\n你就能一眼看出宝可梦\l的能力。\p你是一个训练师。难道你\n没兴趣知道你的宝可梦的\l能力吗？\p来吧！\n让我们看看你的宝可梦！$"

BattleFrontier_Lounge1_Text_AverageAbility:
    .string "…嗯…\p这一只，总而言之，我的评价\n是能力一般。$"

BattleFrontier_Lounge1_Text_BetterThanAverageAbility:
    .string "…嗯…\p这一只，总而言之，我的评价\n是能力较好。$"

BattleFrontier_Lounge1_Text_ImpressiveAbility:
    .string "…嗯…\p这一只，总而言之，我要说\n能力相当不错！$"

BattleFrontier_Lounge1_Text_OutstandingAbility:
    .string "…嗯…\p这一只，总而言之，我要说\n能力非凡的杰出！$"

BattleFrontier_Lounge1_Text_BestAspectHP:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的HP…$"

BattleFrontier_Lounge1_Text_BestAspectAtk:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的攻击…$"

BattleFrontier_Lounge1_Text_BestAspectDef:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的防御…$"

BattleFrontier_Lounge1_Text_BestAspectSpAtk:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的特攻…$"

BattleFrontier_Lounge1_Text_BestAspectSpDef:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的特防…$"

BattleFrontier_Lounge1_Text_BestAspectSpeed:
    .string "顺便提一句，它最出色的方面，\n我认为，是它的速度…$"

BattleFrontier_Lounge1_Text_StatRelativelyGood:
    .string "这能力较好。\n…嗯…这是我对它的评价。$"

BattleFrontier_Lounge1_Text_StatImpressive:
    .string "这能力相当不错。\n…嗯…这是我对它的评价。$"

BattleFrontier_Lounge1_Text_StatOutstanding:
    .string "这能力非常出色！\n…嗯…这是我对它的评价。$"

BattleFrontier_Lounge1_Text_StatFlawless:
    .string "无可挑剔！完美无缺！\n…嗯…这是我对它的评价。$"

BattleFrontier_Lounge1_Text_NoTimeForMyAdvice:
    .string "什么？\n你没时间听取我的建议？\p你应该要热切地学习\n年长者的经验！$"

@ Unused
BattleFrontier_Lounge1_Text_HaveBusinessNeedsTending:
    .string "是的，现在有什么事？\p我有一些事情要处理！\n下次再说咯！$"

BattleFrontier_Lounge1_Text_LetsLookAtYourPokemon:
    .string "哦，年轻人！你对你的\n宝可梦的能力很有兴趣吗？\p来，来！\n让我们来看一下你的宝可梦！$"

BattleFrontier_Lounge1_Text_EvenICantTell:
    .string "虽然我是专家，但对于还没有\n孵化出的宝可梦我也不能说什么！\p给我看一只宝可梦！\n一只宝可梦才是我要看的！$"

BattleFrontier_Lounge1_Text_SaidMyMonIsOutstanding:
    .string "他说我的宝可梦很出色！\n我很高兴我能精心培养它！$"

BattleFrontier_Lounge1_Text_DidntDoAnythingSpecialRaisingIt:
    .string "他说我的宝可梦很出色！\n但是我培养它时没有任何\l特殊照顾…$"

