FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
    .string "说到宝可梦图鉴，\n我想起来了，\p我寻找稀有石头的时候\n遇到了那个叫大吾的训练师。\p哈，他带着一些\n奇妙的宝可梦，\p它们不止是强大，\n还在训练中发挥到了极致！\p他也许比这镇上的\n道馆馆主还要强…$"

FortreeCity_House3_Text_OhYouHavePokedex:
    .string "你拿着的那是什么？\p… … … … … …\p哦？它叫宝可梦图鉴？\n真奇妙！$"

