SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
    .string "给你看看我从馆主亚当那里\n学到的超凡的技术！$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
    .string "请原谅我，亚当…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
    .string "看看踩碎所有地板后\n会发生什么吧。$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
    .string "你一路到这儿来，\n但却不可能见到亚当，\p因为你会输给我！$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
    .string "你真强！\n我被你可爱的外表骗过了！$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
    .string "你也许能够躲过\n被亚当一击打倒的命运。$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
    .string "亚当战斗时的\n样子…\p我被那令人心醉的美丽吸引，\n才决定成为训练师。$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
    .string "你的战斗比我\n更加美丽…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
    .string "你的战斗\n非常优雅。\p啊…跟宝可梦在一起\n真幸运。$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
    .string "让我告诉你\n战斗的严酷吧。$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
    .string "啊，\n你很强。$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
    .string "告诉你一件事吧。\p如果你想走到亚当那儿，\n就得在每块地板上走过一次。$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
    .string "丰缘地区最高水平的\n宝可梦道馆…\p就是琉璃市道馆。$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
    .string "你的水平更高！$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
    .string "比起成为强大的道馆的一员，\n我想在其他地方训练会\l让你变得更强。\l但无论如何，那都更有趣一些。$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
    .string "我和亚当一起\n训练宝可梦，\p别以为你能轻易打倒我。$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
    .string "我被打败了…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
    .string "看来你有潜力，\n为何不和我们一起训练呢？$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
    .string "优雅地滑过冰面，\n道路却没有交叉…\p能做到这一点的训练师\n才拥有最高雅的美丽！$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
    .string "啊，打扰了。$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
    .string "很明显，\n一个训练师有多强\l与年龄并无关系。$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
    .string "我和宝可梦在一起的时候，\n时光在“呀”地意识到之前已经飞逝！$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
    .string "呀！$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
    .string "真想忘掉这次\n连“呀”也来不及喊出来的失败！$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
    .string "我的稀有宝可梦\n也会和我一起战斗。$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
    .string "哎呀！你仔细看过\n我的宝可梦了吗？$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
    .string "我来到这道馆只因\n亚当会欣赏我亲爱的宝可梦。\p啊，如果我还年轻的时候\n就碰到了亚当多好…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
    .string "嘻嘻…\n你那严肃的面孔真迷人。$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
    .string "呀，天啊，\n我太小看你了。$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
    .string "你根本不可能擦到亚当，\n嘻嘻，我肯定…$"

