MossdeepCity_Mart_MapScripts::
	.byte 0

MossdeepCity_Mart_EventScript_Clerk::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart MossdeepCity_Mart_Pokemart
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
MossdeepCity_Mart_Pokemart:
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_NET_BALL
	.2byte ITEM_DIVE_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	.2byte ITEM_X_ATTACK
	.2byte ITEM_X_DEFENSE
	.2byte ITEM_NONE
	release
	end

MossdeepCity_Mart_EventScript_Woman::
	msgbox MossdeepCity_Mart_Text_ReviveIsFantastic, MSGBOX_NPC
	end

MossdeepCity_Mart_EventScript_Boy::
	msgbox MossdeepCity_Mart_Text_MaxRepelLastsLongest, MSGBOX_NPC
	end

MossdeepCity_Mart_EventScript_Sailor::
	msgbox MossdeepCity_Mart_Text_NetAndDiveBallsRare, MSGBOX_NPC
	end

MossdeepCity_Mart_Text_ReviveIsFantastic:
    .string "元气药片太神奇了！\p把它给昏倒的宝可梦的话，\n宝可梦就会醒来。\p但要小心，元气药片并不能恢复\n技能被用掉的PP。$"

MossdeepCity_Mart_Text_MaxRepelLastsLongest:
    .string "黄金喷雾器能赶走所有弱小的宝可梦。\p所有的喷雾器之中，\n它的持续时间最久。$"

MossdeepCity_Mart_Text_NetAndDiveBallsRare:
    .string "撒网球和潜水球是\n只有绿岭市才卖的稀有精灵球。\p撒网球捉虫系和\n水系宝可梦很有效，\p潜水球则容易捉\n海底的宝可梦。$"

