DewfordTown_Gym_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, DewfordTown_Gym_OnTransition
	.byte 0

DewfordTown_Gym_OnTransition:
	call DewfordTown_Gym_EventScript_SetFlashRadius
	end

DewfordTown_Gym_EventScript_SetFlashRadius::
	goto_if_defeated TRAINER_BRAWLY_1, DewfordTown_Gym_EventScript_SetLightsOn
	call DewfordTown_Gym_EventScript_CountTrainersDefeated
	copyvar VAR_0x8001, VAR_0x8000
	compare VAR_0x8000, 0
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius7
	compare VAR_0x8000, 1
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius6
	compare VAR_0x8000, 2
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius5
	compare VAR_0x8000, 3
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius4
	compare VAR_0x8000, 4
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius3
	compare VAR_0x8000, 5
	goto_if_eq DewfordTown_Gym_EventScript_SetFlashRadius2
	goto DewfordTown_Gym_EventScript_SetFlashRadius1

DewfordTown_Gym_EventScript_SetLightsOn::
	setflashradius 0
	return

DewfordTown_Gym_EventScript_SetFlashRadius1::
	setflashradius 1
	return

DewfordTown_Gym_EventScript_SetFlashRadius2::
	setflashradius 2
	return

DewfordTown_Gym_EventScript_SetFlashRadius3::
	setflashradius 3
	return

DewfordTown_Gym_EventScript_SetFlashRadius4::
	setflashradius 4
	return

DewfordTown_Gym_EventScript_SetFlashRadius5::
	setflashradius 5
	return

DewfordTown_Gym_EventScript_SetFlashRadius6::
	setflashradius 6
	return

DewfordTown_Gym_EventScript_SetFlashRadius7::
	setflashradius 7
	return

DewfordTown_Gym_EventScript_BrightenRoom::
	call DewfordTown_Gym_EventScript_CountTrainersDefeated
	nop1
	compare VAR_0x8000, VAR_0x8001
	goto_if_eq DewfordTown_Gym_EventScript_NoLightChange
	copyvar VAR_0x8001, VAR_0x8000
	compare VAR_0x8000, 1
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash1Trainer
	compare VAR_0x8000, 2
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash2Trainers
	compare VAR_0x8000, 3
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash3Trainers
	compare VAR_0x8000, 4
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash4Trainers
	compare VAR_0x8000, 5
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash5Trainers
	compare VAR_0x8000, 6
	goto_if_eq DewfordTown_Gym_EventScript_AnimateFlash6Trainers

DewfordTown_Gym_EventScript_NoLightChange::
	return

@ NOTE: A little confusingly, a larger animateflash param value is a smaller flash radius
DewfordTown_Gym_EventScript_AnimateFlash1Trainer::
	playse SE_SWITCH
	animateflash 6
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlash2Trainers::
	playse SE_SWITCH
	animateflash 5
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlash3Trainers::
	playse SE_SWITCH
	animateflash 4
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlash4Trainers::
	playse SE_SWITCH
	animateflash 3
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlash5Trainers::
	playse SE_SWITCH
	animateflash 2
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlash6Trainers::
	playse SE_SWITCH
	animateflash 1
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_AnimateFlashFullBrightness::
	playse SE_SWITCH
	animateflash 0
	call DewfordTown_Gym_EventScript_SetFlashRadius
	return

DewfordTown_Gym_EventScript_CountTrainersDefeated::
	setvar VAR_0x8000, 0
	goto_if_not_defeated TRAINER_TAKAO, DewfordTown_Gym_EventScript_CheckJocelyn
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckJocelyn::
	goto_if_not_defeated TRAINER_JOCELYN, DewfordTown_Gym_EventScript_CheckLaura
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckLaura::
	goto_if_not_defeated TRAINER_LAURA, DewfordTown_Gym_EventScript_CheckBrenden
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckBrenden::
	goto_if_not_defeated TRAINER_BRENDEN, DewfordTown_Gym_EventScript_CheckCristian
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckCristian::
	goto_if_not_defeated TRAINER_CRISTIAN, DewfordTown_Gym_EventScript_CheckLilith
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckLilith::
	goto_if_not_defeated TRAINER_LILITH, DewfordTown_Gym_EventScript_StopCountingTrainers
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_StopCountingTrainers::
	return

DewfordTown_Gym_EventScript_Brawly::
	trainerbattle_single TRAINER_BRAWLY_1, DewfordTown_Gym_Text_BrawlyIntro, DewfordTown_Gym_Text_BrawlyDefeat, DewfordTown_Gym_EventScript_BrawlyDefeated, NO_MUSIC
	specialvar VAR_RESULT, ShouldTryRematchBattle
	compare VAR_RESULT, TRUE
	goto_if_eq DewfordTown_Gym_EventScript_BrawlyRematch
	goto_if_unset FLAG_RECEIVED_TM08, DewfordTown_Gym_EventScript_GiveBulkUp2
	msgbox DewfordTown_Gym_Text_BrawlyPostBattle, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_BrawlyDefeated::
	call DewfordTown_Gym_EventScript_AnimateFlashFullBrightness
	message DewfordTown_Gym_Text_ReceivedKnuckleBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis, MSGBOX_DEFAULT
	setflag FLAG_DEFEATED_DEWFORD_GYM
	setflag FLAG_BADGE02_GET
	addvar VAR_PETALBURG_GYM_STATE, 1
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	setvar VAR_0x8008, 2
	call Common_EventScript_SetGymTrainers
	call DewfordTown_Gym_EventScript_GiveBulkUp
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox DewfordTown_Gym_Text_RegisteredBrawly, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_BRAWLY_MATCH_CALL
	setvar VAR_ROXANNE_CALL_STEP_COUNTER, 0
	setflag FLAG_ENABLE_ROXANNE_FIRST_CALL
	release
	end

DewfordTown_Gym_EventScript_GiveBulkUp::
	giveitem ITEM_TM08
	compare VAR_RESULT, 0
	goto_if_eq Common_EventScript_BagIsFull
	msgbox DewfordTown_Gym_Text_ExplainBulkUp, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM08
	return

DewfordTown_Gym_EventScript_GiveBulkUp2:
	giveitem ITEM_TM08
	compare VAR_RESULT, 0
	goto_if_eq Common_EventScript_ShowBagIsFull
	msgbox DewfordTown_Gym_Text_ExplainBulkUp, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM08
	release
	end

DewfordTown_Gym_EventScript_BrawlyRematch::
	trainerbattle_rematch_double TRAINER_BRAWLY_1, DewfordTown_Gym_Text_BrawlyPreRematch, DewfordTown_Gym_Text_BrawlyRematchDefeat, DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons
	msgbox DewfordTown_Gym_Text_BrawlyPostRematch, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_Takao::
	trainerbattle_single TRAINER_TAKAO, DewfordTown_Gym_Text_TakaoIntro, DewfordTown_Gym_Text_TakaoDefeat, DewfordTown_Gym_EventScript_TakaoBrightenRoom
	msgbox DewfordTown_Gym_Text_TakaoPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_TakaoBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Jocelyn::
	trainerbattle_single TRAINER_JOCELYN, DewfordTown_Gym_Text_JocelynIntro, DewfordTown_Gym_Text_JocelynDefeat, DewfordTown_Gym_EventScript_JocelynBrightenRoom
	msgbox DewfordTown_Gym_Text_JocelynPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_JocelynBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Laura::
	trainerbattle_single TRAINER_LAURA, DewfordTown_Gym_Text_LauraIntro, DewfordTown_Gym_Text_LauraDefeat, DewfordTown_Gym_EventScript_LauraBrightenRoom
	msgbox DewfordTown_Gym_Text_LauraPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_LauraBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Brenden::
	trainerbattle_single TRAINER_BRENDEN, DewfordTown_Gym_Text_BrendenIntro, DewfordTown_Gym_Text_BrendenDefeat, DewfordTown_Gym_EventScript_BrendenBrightenRoom
	msgbox DewfordTown_Gym_Text_BrendenPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_BrendenBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Cristian::
	trainerbattle_single TRAINER_CRISTIAN, DewfordTown_Gym_Text_CristianIntro, DewfordTown_Gym_Text_CristianDefeat, DewfordTown_Gym_EventScript_CristianBrightenRoom
	msgbox DewfordTown_Gym_Text_CristianPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_CristianBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Lilith::
	trainerbattle_single TRAINER_LILITH, DewfordTown_Gym_Text_LilithIntro, DewfordTown_Gym_Text_LilithDefeat, DewfordTown_Gym_EventScript_LilithBrightenRoom
	msgbox DewfordTown_Gym_Text_LilithPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_LilithBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_DEWFORD_GYM, DewfordTown_Gym_EventScript_GymGuidePostVictory
	msgbox DewfordTown_Gym_Text_GymGuideAdvice, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_GymGuidePostVictory::
	msgbox DewfordTown_Gym_Text_GymGuidePostVictory, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_LeftGymStatue::
	lockall
	goto_if_set FLAG_BADGE02_GET, DewfordTown_Gym_EventScript_GymStatueCertified
	goto DewfordTown_Gym_EventScript_GymStatue
	end

DewfordTown_Gym_EventScript_RightGymStatue::
	lockall
	goto_if_set FLAG_BADGE02_GET, DewfordTown_Gym_EventScript_GymStatueCertified
	goto DewfordTown_Gym_EventScript_GymStatue
	end

DewfordTown_Gym_EventScript_GymStatueCertified::
	msgbox DewfordTown_Gym_Text_GymStatueCertified, MSGBOX_DEFAULT
	releaseall
	end

DewfordTown_Gym_EventScript_GymStatue::
	msgbox DewfordTown_Gym_Text_GymStatue, MSGBOX_DEFAULT
	releaseall
	end

DewfordTown_Gym_Text_GymGuideAdvice:
    .string "嗨，怎么样，向冠军的目标\n冲刺的{PLAYER}？\p武斗镇的道馆馆主藤树\n使用的是格斗系宝可梦。\p想用一般系\n宝可梦对付他是自找麻烦。\p格斗宝可梦会对\n一般宝可梦造成极大伤害，\l要小心！\p更麻烦的是，道馆里就像\n海底一样黑暗，\p但随着打败一路上的训练师，\n室内会越来越明亮。\p好了，加油吧！$"

DewfordTown_Gym_Text_GymGuidePostVictory:
    .string "哇！这里变亮了！\p你的未来也是一片光明！$"

DewfordTown_Gym_Text_TakaoIntro:
    .string "力量决定一切！\n来吧！$"

DewfordTown_Gym_Text_TakaoDefeat:
    .string "力量还不够…$"

DewfordTown_Gym_Text_TakaoPostBattle:
    .string "你的技术胜过了我的力量！\n我欣赏你的实力！$"

DewfordTown_Gym_Text_JocelynIntro:
    .string "没必要让\n藤树出手！\p我就能对付你！$"

DewfordTown_Gym_Text_JocelynDefeat:
    .string "但…怎么会？\n怎么会这么快就输了？$"

DewfordTown_Gym_Text_JocelynPostBattle:
    .string "我不会浪费这次失败，\n我要用它来激励我继续训练！\p总有一天，我会成为道馆馆主…\p不，是成为宝可梦联盟\n冠军！$"

DewfordTown_Gym_Text_LauraIntro:
    .string "你胆敢无视我吗！\n把你打哭了别怪我！$"

DewfordTown_Gym_Text_LauraDefeat:
    .string "哇啊啊啊！\n我输了！$"

DewfordTown_Gym_Text_LauraPostBattle:
    .string "我在黑暗中战斗，\n训练我的胆量。\p但这里实在太暗，\n我甚至看不清藤树的样子…$"

DewfordTown_Gym_Text_LilithIntro:
    .string "哼哼哼…\n你在黑暗中跌跌撞撞地摸索吗？$"

DewfordTown_Gym_Text_LilithDefeat:
    .string "哎，你…\n真不想见到你！$"

DewfordTown_Gym_Text_LilithPostBattle:
    .string "尽管你可能迷路了，\n但最后还会回到出口的！$"

DewfordTown_Gym_Text_BrendenIntro:
    .string "让你看看\n水手的智慧！$"

DewfordTown_Gym_Text_BrendenDefeat:
    .string "这怎么可能？\n我怎么会这样输掉！$"

DewfordTown_Gym_Text_BrendenPostBattle:
    .string "啊，没错！你有能力\n去见我们的道馆馆主。$"

DewfordTown_Gym_Text_CristianIntro:
    .string "你想过去的话，\n先过我这一关！$"

DewfordTown_Gym_Text_CristianDefeat:
    .string "咕呜！\n完全失败了！$"

DewfordTown_Gym_Text_CristianPostBattle:
    .string "你赢了！\n去争取徽章吧！$"

DewfordTown_Gym_Text_BrawlyIntro:
    .string "我是藤树！\n武斗镇的道馆馆主！\p我曾与这里汹涌的巨浪搏斗，\n在漆黑的山洞中训练\l让自己变得更强！\p你想挑战我吗？\n让我看看你的力量！$"

DewfordTown_Gym_Text_BrawlyDefeat:
    .string "哇，你着实让我\n大吃一惊！\p你的力量压过了我！\p好吧，是你赢了，\n这个道馆徽章归你了！$"

DewfordTown_Gym_Text_ReceivedKnuckleBadge:
    .string "{PLAYER}从藤树处\n得到了拳击徽章。$"

DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis:
    .string "拳击徽章能使包括交换得来的\n所有30级以下的宝可梦\l听从指挥，\p而且你也可以在战斗以外的时刻\n使用秘传机器闪光。\p喜欢的话，这个\n技能机器也给你吧。$"

DewfordTown_Gym_Text_ExplainBulkUp:
    .string "技能机器08里面是健美，\p是可以提升攻击\n和防御的技能。\p… … … … … …$"

DewfordTown_Gym_Text_RegisteredBrawly:
    .string "把道馆馆主藤树的信息\n登记进口袋领航员里。$"

DewfordTown_Gym_Text_BrawlyPostBattle:
    .string "我预言总有一天，你的天赋\n会成为一波巨浪，在训练师之中\l掀起震撼的暴风雨！$"

DewfordTown_Gym_Text_GymStatue:
    .string "武斗镇宝可梦道馆$"

DewfordTown_Gym_Text_GymStatueCertified:
    .string "武斗镇宝可梦道馆\p藤树认可的训练师：\n{PLAYER}$"

DewfordTown_Gym_Text_BrawlyPreRematch:
    .string "藤树：波浪可能会暂时消退，\n但最终还会冲上海岸。\p拥有极高的天赋的你这一波巨浪…\n我知道迟早会回来的！\p就让我看看你现在\n有多么强了！$"

DewfordTown_Gym_Text_BrawlyRematchDefeat:
    .string "哇！\n又被你打倒了！$"

DewfordTown_Gym_Text_BrawlyPostRematch:
    .string "藤树：战斗就像丰缘地区\n的大海一样，广阔而又深沉，\l永远无法看到它的底部！$"

DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons:
    .string "藤树：波浪可能会暂时消退，\n但最终还会冲上海岸。\p拥有极高的天赋的你这一波巨浪…\n我知道迟早会回来的！\p哦？你只有一只可以\n战斗的宝可梦。\p但我希望你至少\n带两只宝可梦来。$"
